.travis.yml, cmake/FreecivDependencies.cmake, tools/fcmp/download.cpp, tools/fcmp/download.h, tools/fcmp/mpcli.cpp, tools/fcmp/mpgui_qt.cpp, tools/fcmp/mpgui_qt.h, tools/fcmp/mpgui_qt_worker.cpp, tools/fcmp/mpgui_qt_worker.h, utility/CMakeLists.txt, utility/netfile.cpp, utility/netfile.h
Use Qt Network instead. This means that downloading modpacks from local files or eg ftp servers doesn't work anymore. Local files are maybe annoying, but nowadays http is ruling the Web.
This ended up mixed with some cleanup of the modpack installer code. It had clearly been written by someone not very familiar with C++.
=> Remove last traces of libcurl

client/global_worklist.cpp, common/effects.cpp
It fixes governor crash
and assert fail - it removess assert but it was introduced with 6f5d4f4 when adding "utype_build_shield_cost" which has only those arguments(const struct city *pcity, const struct unit_type *punittype) and homeless units have no way to find pplayer by pcity.
=> Fixed governor crash and assert fail

ai/default/aiguard.h, client/client_main.cpp, client/update_queue.cpp, cmake/FreecivBackward.cmake, cmake/FreecivDependencies.cmake, common/aicore/cm.cpp, common/aicore/path_finding.cpp, common/city.cpp, dependencies/backward-cpp-1.5/LICENSE.txt, dependencies/backward-cpp-1.5/README, dependencies/backward-cpp-1.5/backward.hpp, server/advisors/advchoice.h, server/civserver.cpp, server/fcdb.cpp, server/generator/mapgen.cpp, server/sanitycheck.h, server/srv_main.cpp, server/techtools.cpp, tools/civmanual.cpp, tools/ruledit/ruledit.cpp, tools/ruleup.cpp, utility/CMakeLists.txt, utility/cmake_fc_config.h.in, utility/cmake_freeciv_config.h.in, utility/fcbacktrace.cpp, utility/fcthread.h, utility/log.cpp, utility/log.h
This adds support for `FREECIV_DEBUG` when compiled in `Debug` mode. The stack trace printed on `log_error` and failed asserts has been improved to support more systems and backends.
`FREECIV_NDEBUG` has been removed because failed asserts are not uncommon even in "stable" versions; removing them with `FREECIV_NDEBUG` would harm stability.
Closes #51.
=> FREECIV_DEBUG support

cmake/FreecivBackward.cmake
A misunderstanding of the pkg_search_module interface prevented cmake from finding the most juicy stack unwinding libraries. I had the variables set in my cmake cache so I overlooked the issue.
=> Fix stack traces in debug builds

server/server.cpp, server/stdinhand.cpp
When quitting with "quit", the server was still reading input after the connections were closed, causing a use-after-free. Move closing the connections to the server destructor, and use `QCoreApplication::quit()` to exit.
=> Fix a crash on server exit

client/gui-qt/citydlg.cpp
After closing city dialog, unit with last focus was recalled - but it could be eg fortified unit or with 0 moves. Fixed.
=> Unit focus city dialog fix

cmake/FreecivBackward.cmake
Otherwise build fails when the `CAN_UNWIND_STACK` is false.
Reported by @ec429.
=> Always define BACKWARD_HAS_DW and BACKWARD_HAS_BACKTRACE_SYMBOLS

tools/fcmp/mpcli.cpp, tools/fcmp/mpgui_qt.cpp
Initializing the rest may print log messages.
Closes #107.
=> fcmp: initialize logging first

client/gui-qt/citydlg.cpp, common/aicore/cm.cpp, common/featured_text.cpp, server/diplomats.cpp
Reported with the [aviation ruleset](https://github.com/ec429/fc-aviation/tree/fc21) commit `a2d2f9e5`. It's still completely broken but at least it doesn't crash.
=> Fix the server sending trash and the client crashing on Investigate city

utility/fcbacktrace.cpp
Traces are useless for most users and should therefore be disabled by default. They can still be selectively enabled using `QT_LOGGING_RULES`.
=> Print stack traces with qDebug (was qInfo)

common/networking/packets.cpp, common/networking/packets.def
fixed compilation of packet statistics - it must be set in source file ( it wasnt updated for ages, replaced log_debugs with printfs there)
enable is-game-info for packet diplstate
=> Reduced packet diplstate

client/gui-qt/page_pregame.cpp, client/gui-qt/page_pregame.ui
Mutlimenu pick in pregame:
Allows selecting many players at once and moving to 1 team or setting their difficulty with single click.
=> Allow multi pick players in pregame

client/tilespec.cpp
Check if any city dialog is open before searching cities near tile.
=> do easy check first before costly one

client/gui-qt/fc_client.cpp, client/gui-qt/gui_main.cpp
Use configure_fonts() to pick fonts when freeciv settings were lost or jsut need to be created.
=> Reconfigure fonts if freeciv settings are lost

client/control.cpp, client/mapview_common.cpp, client/mapview_common.h, client/tilespec.cpp, client/tilespec.h
This always selects the correct tiles when in the city screen.
=> Fix drawing blocked tiles and grid in city mode

CMakePresets.json
Added 3 simple example presets
use:
cmake --preset=clazy
cmake --build build-clazy -j10000
=> Added CMakePresets CMake 3.19 is required to use them

cmake/EnableCompilerWarnings.cmake
There are millions of warnings, disable them all so windows users dont panic thier kernels.
=> Set no warnings for clang-cl

utility/fcintl.h
Resetting asprintf/vasprintf as macros is probably non-conformant but it
is the case on MSYS. It conflicts with QString methods of the same name.
Unset the macros.
Closes issue #273
=> Unset asprintf/vasprintf if libintl.h defines them

utility/registry_ini.cpp
Ruleset encoding issues (#280) prevented the server from even starting up. Fix by using `qUtf8Printable()` instead of `qPrintable()` for the relevant string conversion.
=> Fix server startup on Windows

client/connectdlg_common.cpp, client/gui-qt/icons.cpp, client/gui-qt/menu.cpp, client/gui-qt/themes.cpp, client/options.cpp, server/gamehand.cpp, server/ruleset.cpp, tools/fcmp/download.cpp, tools/fcmp/modinst.cpp, tools/fcmp/mpdb.cpp, utility/shared.cpp, utility/shared.h
Qt abstracts it away so we don't need to worry about it.
Fixes #279
=> Always use the forward slash (/) as dir separator

server/CMakeLists.txt
GCC was complaining that some warning didn't apply to C code. Now it's C++.
Closes #263
=> Rename null.c into null.cpp

client/tilespec.cpp
When loading a tileset, the client tries every possible format for every graphics file. This is very inefficient on Windows. Make sure that png is always tried out first, to match what all shipped files use. A rough estimate of the speedup is 3x for hexamplio (from ~15s to ~5s in my VM).
=> Speed up tileset loading on Windows (3x)

client/client_main.cpp
KDE scales without it but Windows wants it ( and gnome mutter probably too)
=> Enable HiDPI scaling by default

client/packhand.cpp, common/city.cpp, common/city.h, common/networking/packets.def, server/cityhand.cpp, server/citytools.cpp, server/cityturn.cpp, server/savegame/savegame3.cpp, utility/fc_version.h
Fix #310 
Set 50% penalty when buying units/improvements and changing to somethign else later.
=> ❤️ Penalize buying without building

.travis.yml, client/citybar.h, client/gui-qt/fonts.h, client/themes_common.h, cmake/FreecivDependencies.cmake, utility/genlist.cpp, utility/rand.h, utility/shared.cpp, utility/shared.h
This change is done primarily because the Qt5 shipped in Homebrew appears to be
configured to use C++ 17 and breaks the build on Travis.
C++ 17 is available on Debian Buster (already our minimal requirement for Qt),
MSYS and OS X. Using it brings nice new features without significant pitfalls.
MSVC should also support it.
Closes #321
=> Bump the required C++ version to C++ 17

.travis.yml
A weekly Travis run will be instated to:
* Follow Coverity defects more closely
* Make sure the build doesn't break due to updated dependencies as was recently the case for OS X (#321).
Closes #328
=> Weekly Travis builds including Coverity

.travis.yml
This is needed for weekly builds to work.
Closes #330
=> Allow running Coverity on master

client/connectdlg_common.cpp, client/gui-qt/menu.cpp, client/gui-qt/themes.cpp, client/options.cpp, cmake/FreecivBuildOptions.cmake, common/fc_interface.cpp, server/gamehand.cpp, server/savegame/savegame3.cpp, server/server.cpp, server/stdinhand.cpp, utility/cmake_fc_config.h.in, utility/shared.cpp, utility/shared.h
This PR moves freeciv21 user-specific files (saves, scenarios, …) to the standard location `.local/share/freeciv21` on Linux and similar locations on other systems. There is still room for improvement: settings and challenge files should be moved to other locations (`~/.config` and `~/.cache/freeciv21` respectively).
This is part of *QString everywhere* because some `char*` code was reworked in the process.
Closes #347.
=> Move Freeciv21 files outside of .freeciv

tools/fcmp/modinst.h
Points to https://github.com/longturn/modpacks
Closes #350.
Depends on #351.
=> Change the default modpack repo

client/client_main.cpp, server/generator/mapgen.cpp, server/savegame/savecompat.h, server/savegame/savegame2.cpp, server/savegame/savegame3.cpp, server/server.cpp, server/srv_main.cpp, utility/genlist.cpp, utility/rand.cpp, utility/rand.h
Use an implementation from the standard library. The random generator is
constrained to use a well defined algorithm and produce the same results across
implementations. Seed it by pulling the state from the high-entropy
std::random_device: it has so many bits that it's likely very hard to figure
out the state. (Of course only if the implementation of std::random_device is
correct. I trust it more than anything I could write myself.)
The main drawback is that the state might be saved in an implementation defined
way, the reference isn't very clear about this. Work around this by generating
a new, truly random seed if loading the state fails. The main reason for saving
the state is to have deterministic results when loading a save several times,
so one can't "cheat" by reloading unit a …
=> Replace the random number generator

client/gui-qt/page_network.cpp
Was the case on the network page.
Closes #363.
=> Fix username field being called "password"

utility/rand.cpp
Generated numbers were out of the requested range, which created crashes.
Fixes #378.
=> Fix the number generator

cmake/FreecivDependencies.cmake
`FindIntl.cmake` is buggy and cannot find the correct link flags, breaking the build.
Closes #383.
=> Prevent enabling NLS on CMake 3.20.0

ai/default/aitech.cpp, client/audio_sdl.cpp, client/helpdata.cpp, client/options.cpp, common/networking/connection.cpp, common/research.cpp, common/research.h, server/stdinhand.cpp, server/techtools.cpp, server/unittools.cpp, tools/ruleutil/rulesave.cpp, utility/registry_ini.cpp, utility/registry_ini.h
`qUtf8Printable(...)` returns a pointer to the data of a temporary `QByteArray` that is freed at the end of the statement, and therefore the returned pointer shouldn't be saved as it's going to be dangling immediately. This PR fixes all such cases I could find by turning the saved variable into a `QString`.
=> Fix use-after-free related to qUtf8Printable()

client/gui-qt/citydlg.cpp, client/gui-qt/sidebar.cpp
The map has to be shown first so the widgets inside get a layout. Also fix a similar issue when switching tab while the city screen is on.
Fixes #232.
=> Fix opening the city screen from the city list

common/unit.cpp
The old code checked if the current unit fits, so you could end up with
an impossible unit on the transport.
See hrm Bug #921691
Closes #248.
=> Check if the new unit fits in transport when upgrading transported unit

ai/default/ailog.h, client/citybar.cpp, client/client_main.cpp, client/clinet.cpp, client/connectdlg_common.cpp, client/gui-qt/helpdlg.cpp, server/civserver.cpp, server/sernet.cpp, server/server.cpp, server/srv_log.h, tools/civmanual.cpp, tools/fcmp/download.cpp, tools/fcmp/modinst.cpp, tools/ruleup.cpp, utility/inputfile.cpp, utility/log.cpp, utility/registry_ini.cpp, utility/section_file.cpp
On Windows, qPrintable() may return a string in the local code page, while the code expects UTF-8 everywhere.
Unfortunately, console I/O on Windows is still a broken mess.
Closes #280.
=> Replace usage of qPrintable() with qUtf8Printable()

client/gui-qt/hudwidget.cpp, client/gui-qt/menu.cpp, client/gui-qt/menu.h, client/packhand.cpp, client/text.cpp, common/networking/packets.def, common/unit.h, server/savegame/savegame3.cpp, server/unithand.cpp, server/unittools.cpp, utility/fc_version.h
This would be useful eg in a WWII scenario with Pearl Harbour ships called by their historical names. Changes the network protocol. Requested by @jwrober.
Closes #281.
=> Give names to units

server/sernet.cpp
The server was disconnecting all signals from all existing sockets, resulting in an unusable server. Remove the offending code.
Closes #394.
=> Fix cutting connections on the server side

client/control.cpp
`find_city_near_tile()` is a bad function.
Closes #386.
=> Restore selecting any tile from the city screen

client/citybar.cpp
Add one extra pixel to give some more room.
Closes #400.
=> Avoid text wrapping in the city bar

client/gui-qt/menu.cpp, utility/shared.cpp
There was a bug in `fileinfoname` and an oversight in the "Load another tileset" box.
Closes #399.
=> Don't list tilesets, sound sets and music sets twice

server/rscompat.cpp
The direction of the comparisons had been flipped when converting to `std::vector`.
Closes #441.
=> Fix loading 3.0 rulesets

ai/default/daimilitary.cpp
The danger variable can be larger than sqrt(INT_MAX) and overflow 32 bits when
squared. Cast to long (64 bits are enough for any 32 bits number squared).
Closes #445.
=> Fix AI division by 0 when a city is in danger

common/combat.cpp, server/ruleset.cpp, server/unittools.cpp
With the ability to limit Combat_Rounds, it now makes sense to have full combat between units even when the defender's defence strength or FirePower is zero, as it might still survive if the attacker runs out of rounds.
Against a defender with D=0, you simply need to rack up enough rounds to take out its HP, because every shot hits.
Against a defender with D>0 but FP=0, combat becomes a bit like bombardment: you might not hit every round (you have to roll A/(A+D)), but you don't take damage when you miss.  This represents a unit that's unarmed but difficult to hit (e.g. high-flying aeroplane).
I have tested this patch with the following cases:
* A1 FP1 CR3 vs D0 FP1 HP4.  Defender took 3 HP of damage.  Attacker took none.
* A1 FP1 CR3 vs D1 FP0 HP4.  Defender sometimes took 1 HP of …
=> Combat_Rounds-related enhancements

utility/netfile.cpp
Fixes #464.
Use NoLessSafeRedirectPolicy to prevent https -> http redirects.
=> Ask Qt to follow redirects when downloading

client/client_main.cpp, client/client_main.h, client/clinet.cpp, client/clinet.h, client/connectdlg_common.cpp, client/connectdlg_common.h, client/gui-qt/fc_client.cpp, client/gui-qt/page_load.cpp, client/gui-qt/page_network.cpp, client/gui-qt/page_scenario.cpp, client/options.cpp, client/update_queue.cpp
This allows to connect immediately using a command of the form:
freeciv21-client user:password@host:port -a
URL syntax is easier to remember than the combination of the -n -s -p options
that was previously needed (and is still supported), and as a side-effect
allows to give a password as well. Supporting URLs also brings us closer to
setting the system handler for fc21:// links to the client (so websites can
give a fc21:// link to help users connect to a server).
Closes #468.
Internally, a single static QUrl is used to pass connection information instead
of several static field. This will allow using the path part for a
WebSocket-backed protocol and eventually WS-based encryption.
=> Client positional argument to connect to URL

.gitattributes
The folder is very large and not really useful to compile.
Closes #473.
=> Exclude data/graphics from tarball

utility/rand.cpp
The RDRAND instruction is broken on certain AMD processors and always returns
-1. libstdc++ trusts it for the default behaviour of its std::random_device,
which obviously results in a very bad seed.
This patch switches to QRandomGenerator for seeding. QRandomGenerator
implements a workaround since Qt 5.12.6, disabling hardware random generation
if it looks broken.
See GCC bug #100444 at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100444
See QTBUG-69423 at https://bugreports.qt.io/browse/QTBUG-69423
See issue #455
=> Workaround for lack of random_device randomness

utility/rand.cpp
Reported and investigated by panch93.
Closes #477.
=> Fix fc_rand(0) returning negative numbers

.travis.yml
The free minutes available on Travis have been drastically reduced, with
Windows and Mac counting more than Linux. Windows takes 20 minutes to
complete and OS X takes over 40 minutes. The two Linux builds together
are about 20 minutes.
Disable Windows and Mac so we still have a CI while looking for
alternatives.
Closes #498.
See #499.
=> Disable Travis on Windows and Mac

client/gui-qt/page_network.cpp
Since the migration to QUrl, the password sent by the client to auth-enabled
servers was always empty.
Closes #518.
=> Actually send the password entered by the user

server/commands.cpp, server/stdinhand.cpp
**document-me**: The `playernation` server command can now be used to select a random nation.
Closes #520.
=> Allow setting a random nation in /playernation

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation-request.md, .github/ISSUE_TEMPLATE/feature_request.md
The bug and feature templates are adapted from the Github defaults.
The documentation template was created from scratch.
Closes #553.
=> Add issue templates

AUTHORS, client/packhand.cpp, client/plrdlg_common.cpp, client/text.cpp, client/text.h, common/networking/connection.cpp, common/networking/connection.h, common/networking/packets.def, server/connecthand.cpp, server/edithand.cpp, server/sernet.cpp, server/sernet.h, server/server.cpp, server/stdinhand.cpp
Closes #558. The corresponding columns have been removed from the nations screen.
=> Stop broadcasting client IP and ping times

client/gui-qt/hudwidget.cpp, client/text.cpp
As requested in #550, show unit ID for the selected unit and on middle click for all units. Here is an example for the middle click popup:
Closes #550.
=> Show unit IDs in the client

.github/workflows/build.yaml
Two builds were occurring when creating a new release from the Github UI: one
on the push event and another on the release event. Keep only the push event to
save free CPU time.
Closes #609.
=> Build only once when doing a new release

client/gui-qt/messagewin.cpp
This is for instance the case at the beginning of a turn. The code was resizing
every row for each recieved message, resulting in O(N^2) complexity. Change it
to resize only the new row for O(N) complexity.
Closes #615.
=> Fix a performance issue when the server sends many messages

client/gui-qt/menu.cpp
Sub-menus are bad for usability. The settings were hidden under a submenu of
the Game menu, which was very short. Inline them instead, resulting in a
slightly longer menu but making the entries more accessible.
Closes #569.
=> Flatten the "Game" menu

cmake/FreecivDependencies.cmake
The CMake version on the server (Debian Buster) doesn't like it.
Closes #644.
=> Don't use target_include_directories on an IMPORTED target

client/servers.cpp
If it's different from 0 (and invalid) when the scan is destroyed, we get a
segfault. This wouldn't have happened with proper RAII semantics...
Closes #640.
=> Initialize scan->servers in server_scan_begin

client/client_main.cpp
People using -a probably want to get to the game faster and won't spend ages in
the menus. Disable the menu music in that case. Keep it when disconnecting from
a game.
Closes #626.
=> Disable menu music when autoconnecting

data/alio/hills.spec, data/hexemplio/hills.spec, data/hexemplio/mountains.spec
The client was showing warnings when loading them because of the unused entry
spec.artists. The client looks at info.artists, so add the [info] section
markers.
Closes #298.
=> Fix info.artists entries in shipped tilesets

client/gui-qt/messagewin.cpp, client/gui-qt/messagewin.h, client/update_queue.cpp, client/update_queue.h, data/themes/gui-qt/Classic/resource.qss, data/themes/gui-qt/Necrophos/resource.qss, data/themes/gui-qt/NightStalker/resource.qss, data/themes/gui-qt/System/resource.qss, data/themes/gui-qt/TheLastLaserMaster/resource.qss
This goes from O(n^3) complexity to mostly O(n). Layout of the message widget was the dominant contribution in profiles when connecting to LTEx24. After these changes, it becomes invisible.
=> Optimize connecting to a server with many messages

client/gui-qt/citydlg.cpp
The grid layout showing city output info in the city screen allowed rows to
shrink below their preferred size, which created overlap when there were many
units in a city. Not setting the row weights to 0 prevents this with no
apparent negative consequence.
Closes #665.
=> Don't allow the city info grid to become squeezed

client/tilespec.cpp
When using citybar style "simple", the "city is occupied" icon was always
shown. Only show it when the city is actually occupied.
Closes #437.
=> Only show the occupied icon for occupied cities

client/options.cpp
This makes the build work again on Windows/MinGW with GCC 11.2.0.
Closes #697
=> Give a name to the union in client_option

client/layer.h
The absence of a virtual destructor meant that data from subclasses wasn't freed properly.
Found by Coverity.
See #388.
=> Fix a memory leak when destroying layer objects

client/gui-qt/citydlg.cpp
It was possible to drag-and-drop unit icons within the lists in the city dialog. This allowed one to seemingly duplicate units.
The reason for this was that QListView defaults to allowing drag and drop when in icon mode.
Closes #708.
=> Disallow drag-and-drop in the city dialog lists

client/governor.cpp, client/governor.h
It was used only in the SDL client, which we dropped.
Closes #719.
=> Drop cma_apply_result()

client/gui-qt/fonts.cpp
Use the same as for city production, since this list at least doesn't include Comics Sans MS.
Closes #564.
=> Change the default tech tree font

client/gui-qt/menu.cpp, client/gui-qt/page_load.cpp, client/gui-qt/page_scenario.cpp, cmake/FreecivDependencies.cmake, common/game.h, server/savegame/savemain.cpp, server/settings.cpp, server/stdinhand.cpp, utility/cmake_fc_config.h.in
Zstandard is as fast as gzip and as good as xz. This makes it a good candidate for savegame compression. Support it when KArchive is recent enough.
Leaving the default to xz for now, but we might want to revisit this in the future.
Closes #713.
Test plan (you need KArchive 5.82 or later built with zst support):
1. `set compresstype zstd`
2. Save game
3. Load game just saved
=> Add support for Zstandard compression

client/gui-qt/page_pregame.cpp, client/gui-qt/page_pregame.ui
And since I spotted this, don't force a bold font on the user.
Closes #747.
=> Don't allow editing server output in pregame

client/tilespec.cpp
Since the same square tilesets work for both iso and non-iso maps, this check isn't required. It was actually preventing tileset selection when using an iso map.
Closes #740.
=> Don't check TF_ISO when setting square tilesets

common/ai.cpp, common/game.cpp
Collection of patches related to Freeciv(.org)'s new AI types "threaded" and "tex" that are not supported in fc21. Basically we always fall back to the classic AI, and only mention "classic" in our scenarios.
Closes #746.
Test plan:
* Save old Europe 1900 scenario somewhere else
* Checkout and build new code
* Load old Europe 1900
* Load new Europe 1900
=> Fix loading WWI scenario

client/gui-qt/minimap.cpp, client/gui-qt/widgetdecorations.cpp
Closes #751.
Test plan:
* Start game
* Move widgets around, trying to make them leave the visible area:
* Minimap
* Upper left info widget
* Chat
* Unit info
=> Prevent moving panels out of sight

docs/Playing/index.rst, docs/Playing/turn-change.rst
=> Document the TC

client/gui-qt/sidebar.cpp
See Coverity CID 1466477
See Issue #388
Test plan: No-op change, only checks that a pointer is not null before dereferencing it. A null pointer would have lead to a crash, which I didn't see.
=> Fix a possible null pointer dereference in sidebar.cpp

client/citybar.cpp, client/gui-qt/canvas.cpp, client/gui-qt/chatline.cpp, client/gui-qt/citydlg.cpp, client/gui-qt/civstatus.cpp, client/gui-qt/fc_client.cpp, client/gui-qt/fonts.cpp, client/gui-qt/fonts.h, client/gui-qt/gui_main.cpp, client/gui-qt/helpdlg.cpp, client/gui-qt/hudwidget.cpp, client/gui-qt/mapview.cpp, client/gui-qt/menu.cpp, client/gui-qt/notifyreport.cpp, client/gui-qt/plrdlg.cpp, client/gui-qt/sidebar.cpp, client/gui-qt/sidebar.h, client/gui-qt/unitreport.cpp, client/gui-qt/unitselect.cpp, client/include/canvas_g.h
In a manner similar to #745, fonts in fcFonts were being modified from the
outside. Expose them only by value so this can't happen.
Closes #712.
Test plan: combination of zoom in, zoom out, enable and disable View > Scale fonts, and change fonts.
=> Make fcFonts more const-correct

ai/default/daimilitary.cpp
Taking the square of danger creates too large numbers in some cases. The
previous workaround - casting to long - is not guaranteed to work by the
standard and indeed it doesn't work on Windows.
This reverts commit c67fc6a2058028582ecdaca48d847bfdb4db1112. The succint
commit message there says that making danger quadratic is in line with defense.
But danger is already quadratic in assess_danger, so I guess that commit was a
mistake. In the worst case this restores the 2.6 formula, and AI didn't behave
that bad there.
=> Fix integer overflow leading to division by zero

client/helpdata.cpp, data/helpdata.txt
This will help new modders immensely.
Closes #772.
Test plan:
* Navigate to Help > About Freeciv21
* Check that the paths make sense
=> Add the data folder location to the in-game help

client/client_main.cpp, client/tilespec.cpp, data/3d.tilespec, data/alio.tilespec, data/amplio.tilespec, data/amplio2.tilespec, data/cimpletoon.tilespec, data/hex2t.tilespec, data/hexemplio.tilespec, data/isophex.tilespec, data/isotrident.tilespec, data/toonhex.tilespec, data/trident.tilespec, docs/Modding/Tilesets/compatibility.rst, docs/Modding/index.rst
This closes #777.
I unhardcoded a few extra elements that happened to be defined nearby. Feature flags were added.
Edit `amplio2/select.spec` as follows:
```py
tiles = { "row", "column", "tag"
0, 0, "unit.select0"
0, 1, "unit.select1"
0, 2, "unit.select2"
0, 3, "unit.select3"
0, 3, "unit.select4"
0, 2, "unit.select5"
0, 1, "unit.select6"
0, 0, "unit.select7"
}
```
Uncomment the `select_step_ms` line in `amplio2.tilespec` and set it to something unreasonable (tested 1 and 1000).
Read the new documentation.
Ideally one would also test the other sprites.
=> Unhardcode sprite counts

client/client_main.cpp, client/gui-qt/diplodlg.cpp, client/gui-qt/mapview.cpp, client/gui-qt/page_game.cpp, client/gui-qt/sciencedlg.cpp, client/gui-qt/sidebar.cpp, client/gui-qt/sidebar.h
Resulted from misuse of the Qt APIs. Use them more as intended.
Closes #782.
Test plan:
* Start game
* Check CPU usage (should be << 100%)
* Check that the sidebar still updates correctly
=> Break infinite update() loop in sidebar

client/gui-qt/citydlg.cpp, client/gui-qt/citydlg.h, client/gui-qt/citydlg.ui, client/helpdata.cpp, client/tilespec.cpp
The core of this PR is a fix for #665 in the third commit:
heightForWidth() was reporting inconsistent results. Turns out it's not needed:
drop it.
Closes #665.
The symptoms described there (overlapping QLabels) sill happen when the window
is resized to a size too small for the contents, but this will be solved later
when we get rid of absolute positioning.  (This time, I hope, for good.)
Other commits are small fixes here and there that aren't worth commenting IMHO.
Test plan:
* Make a save with many units owned by the same city
* Reproduce #665
* Apply patch
* Observe that #665 is harder to reproduce
=> Solve layout issues in the city screen right panel

client/gui-qt/unitreport.cpp
Closes #792.
* `/set unitwaittime 9999`
* Move a bunch of units (the more the better)
* F2
* Check that all items in the list can be seen by scrolling
* Check that sorting by clicking on the headers works as expected
=> Fix bugs in the UWT panel (F2)

common/effects.cpp
The "not X" would only show for negated effects after the first.
Got confirmation from soundnfury that this worked.
Closes #811.
=> Fix Help > Effects when the first req is negated

common/scriptcore/CMakeLists.txt, common/scriptcore/luascript_types.h, dependencies/sol2/CMakeLists.txt, server/scripting/CMakeLists.txt, server/scripting/script_fcdb.cpp
Closes #810.
**Test plan:**
1. Try to reproduce #810
2. Don't reproduce #810 with the patch
3. Generate a lua error by doing something illegal, for instance `variable_that_doesnt_exist[0]`
4. Check that the error is printed to stderr
=> Fix sol2 code and interoperability with tolua

client/layer_background.h, client/layer_base_flags.h, client/layer_darkness.h, client/layer_special.h, client/layer_terrain.cpp, client/layer_terrain.h
I screwed up, this was my fault to begin with.
Closes #807.
=> Fix memory leaks on zoom

client/gui-qt/civstatus.h
Clang gives a warning, this should silence it.
```
freeciv21/client/gui-qt/civstatus.h:28:8: warning: 'moveEvent' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
void moveEvent(QMoveEvent *event);
^```
=> Add override statement for moveEvent

ai/default/daieffects.cpp, common/effects.cpp, common/effects.h, data/alien/effects.ruleset, data/civ1/effects.ruleset, data/civ2/effects.ruleset, data/civ2civ3/effects.ruleset, data/classic/effects.ruleset, data/experimental/effects.ruleset, data/granularity/effects.ruleset, data/multiplayer/effects.ruleset, data/royale/effects.ruleset, data/sandbox/effects.ruleset, data/stub/effects.ruleset, data/webperimental/effects.ruleset, docs/Modding/Rulesets/effects.rst, server/rscompat.cpp, server/rscompat.h, server/ruleset.cpp, server/ruleset.h, server/unittools.cpp
Replace the hardcoded extra healing in `hp_gain_coord()` with a new bonus `EFT_HP_REGEN_MIN`, which supplies the minimum (as a percentage of unittype's HP) to clamp to.
This PR currently includes updates to the Classic ruleset to replicate the old hardcoded behaviour, but does not (yet) update the other rulesets, nor touch ruleup.
Testing: build only so far.
Closes longturn#593.
=> Unhardcode unit healing

ai/default/aihand.cpp, client/governor.cpp, common/aicore/cm.cpp, common/aicore/cm.h, server/cityturn.cpp, server/cityturn.h
Use std::unique_ptr to prevent memory leaks or double free (there was a double
free in result_came_from_server). Also don't trust that the server sends CMA
results before PACKET_PROCESSING_FINISHED.
Closes #803.
=> Rewrite cm.{h,cpp} for more memory safety

client/gui-qt/citydlg.cpp, client/gui-qt/citydlg.h
The condition in most if(can_issue_orders()) was reversed.
Closes #819.
------------
Remains to be seen if I'm the only one not getting the context menu at all. If not, I'll also add the fix to this PR.
=> Fix performing actions from the city screen

data/alien/effects.ruleset, data/granularity/effects.ruleset
These syntax errors in 'alien' and 'granularity' effects prevented
loading those rulesets.
Fixes: 1afb74e570 ("HP regen softcoding for all other bundled rulesets")
=> Remove broken empty reqs vectors

ai/default/daieffects.cpp, common/effects.h, data/alien/effects.ruleset, data/civ1/effects.ruleset, data/civ2/effects.ruleset, data/civ2civ3/effects.ruleset, data/classic/effects.ruleset, data/experimental/effects.ruleset, data/granularity/effects.ruleset, data/multiplayer/effects.ruleset, data/royale/effects.ruleset, data/sandbox/effects.ruleset, data/stub/effects.ruleset, data/webperimental/effects.ruleset, docs/Modding/Rulesets/effects.rst, server/rscompat.cpp, server/ruleset.h, server/unittools.cpp
Closes #731.
In my testing it appears that if there's no limit specified (so the min is 0), bombing a unit down to 0HP doesn't kill it immediately but it dies on the next TC (with the message "Your <unit_type> has run out of hitpoints").
=> Bombard limit effect

client/citybar.cpp, client/client_main.cpp, client/gui-qt/canvas.cpp, client/gui-qt/citydlg.cpp, client/gui-qt/citydlg.h, client/gui-qt/dialogs.cpp, client/gui-qt/fc_client.h, client/gui-qt/hudwidget.cpp, client/gui-qt/mapctrl.cpp, client/gui-qt/mapview.cpp, client/gui-qt/mapview.h, client/gui-qt/menu.cpp, client/gui-qt/page_game.cpp, client/gui-qt/qtg_cxxside.h, client/gui-qt/sprite.cpp, client/gui_interface.cpp, client/gui_interface.h, client/include/sprite_g.h, client/layer_background.cpp, client/layer_terrain.cpp, client/packhand.cpp, client/tilespec.cpp, client/tilespec.h
It no longer reloads the tileset every time, resulting in much faster zooms. Instead, zoom is handled at the mapview level by pretending that the canvas is smaller (or larger) than it really is, and scaling the drawn canvas afterwards. The main drawback is that drawing the map when zoomed out is rather slow. It is, however, quite fast when zoomed in.
City names and production aren't as sharp as they used to be when zooming. Text layers will need to be taken into account when designing the next-gen renderer.
This started as a test to see how far it could go but it turned out to be rather easy so I went ahead.
Closes #295.
Closes #296.
Closes #729.
Closes #864
(I think).
* Play with zoom in and zoom out.
* Watch out for possible offsets between the tile hovered with the mouse and the tile …
=> Improve zoom

cmake/AutoRevision.cmake
Every git command can fail, we need to take this into account.
Closes #875.
=> Do more error checking in AutoRevision.cmake

.github/workflows/build.yaml
The Mac builds started taking very long (over 3 hours) because Qt is rebuilt
every time (#874). Meanwhile there was a new upstream release and caching is
mentioned in the release notes. Update, hoping that it will make things fast
again.
Tested in my fork, caching appears to work.
=> Update the run-vcpkg action to the latest version

CMakeLists.txt
=> Conditionally write fc_version.h and fc_version

client/gui-qt/fc_client.cpp, client/gui-qt/minimap.cpp, client/gui-qt/minimap.h, client/mapview_common.cpp, client/overview_common.cpp, client/overview_common.h
Removes zooming and panning of minimap view, but adds wraparound for viewport rectangle.
=> Remove the minimap thread.

ai/default/daidomestic.cpp, ai/default/daieffects.cpp, common/effects.cpp, common/effects.h, common/fc_types.h, common/traderoutes.cpp, docs/Modding/Rulesets/effects.rst, server/settings.cpp
I've tested a game with `CBS_DISTANCE` and some Avi adjustments including `Trade_Revenue_Exponent -250`.  It seems to behave sensibly enough.
=> More flexible trade revenue bonus

server/rscompat.cpp
The migrations were always run, run them only when the controlling capabilities
are missing.
Closes #901.
@ec429 can confirm that it works?
=> Fix capability-driven ruleset migrations

client/client_main.cpp, client/clinet.cpp, client/clinet.h, client/connectdlg_common.cpp, client/gui-qt/fc_client.cpp, client/gui-qt/fc_client.h, client/gui-qt/gui_main.cpp, client/gui-qt/page_network.cpp, client/gui-qt/qtg_cxxside.h, client/gui_interface.cpp, client/gui_interface.h, client/include/gui_main_g.h, common/networking/connection.cpp, common/networking/connection.h, server/civserver.cpp, server/connecthand.cpp, server/connecthand.h, server/sernet.cpp, server/sernet.h, server/server.cpp, server/server.h, server/srv_main.h
This PR does two things:
* Fix the `--bind` server parameter
* Implement local sockets and use them to communicate with the server spawned by the client for local games
Code is a bit ugly because Qt doesn't leverage OO programming enough in its `QIODevice` hierarchy.
=> Local sockets

client/gui-qt/canvas.cpp, client/gui-qt/canvas.h, client/gui-qt/citydlg.cpp, client/gui-qt/dialogs.cpp, client/gui-qt/helpdlg.cpp, client/gui-qt/hudwidget.cpp, client/gui-qt/qtg_cxxside.cpp, client/gui-qt/qtg_cxxside.h, client/gui-qt/sciencedlg.cpp, client/gui-qt/spaceshipdlg.cpp, client/gui-qt/unitselect.cpp, client/gui_interface.cpp, client/gui_interface.h, client/include/canvas_g.h, client/mapview_common.cpp, client/overview_common.cpp
=> More qtg_ indirection removal

client/options.cpp, client/packhand.cpp
This solves the following:
* Options (harmful bug)
* `Trying to put 728194712 into 8 bits` (harmless apart from exposing one byte from the stack to a malicious server)
The following harmless warning is fixed in #888:
* `QObject::disconnect: Unexpected null parameter` (harmless)
I don't understand the warnings related to `mapview_unsafe_goto`.
=> Solve some warnings from #909

.github/workflows/build.yaml, .gitignore, cmake/FreecivDependencies.cmake, data/CMakeLists.txt, data/tests/CMakeLists.txt, data/tests/rulesets.cpp.in, docs/Contributing/eval-pull-request.rst, server/CMakeLists.txt, server/server.cpp, server/server.h, server/stdinhand.cpp, server/tests/CMakeLists.txt, server/tests/cli.cpp.in, server/tests/cli/comment.serv, server/tests/cli/reread.serv, server/tests/cli/set.serv, server/tests/cli/unknown.serv
Also made me fix issues with the server CLI.
The tests pass on Windows when run from the MSYS terminal, but not in Github actions. The issue is that the server never reacts to the `quit` command sent by the test; `stdin` on Windows is a disaster.
=> Add "unit" tests checking that shipped rulesets load

ai/default/daidomestic.cpp, client/text.cpp, common/aicore/caravan.cpp, common/traderoutes.cpp, common/traderoutes.h, server/unithand.cpp
When trying to calculate the bonus from doing Enter Marketplace, the client was
using code that assumed absolute knowledge of the target city.  Of course the
client doesn't have this for foreign cities, so it was crashing.
Closes #903.
@ec429 may find this useful to continue his game.
=> Fix a client crash when Enter Marketplace is possible

client/gui-qt/canvas.cpp, client/gui-qt/helpdlg.cpp, client/gui-qt/qtg_cxxside.cpp, client/gui-qt/qtg_cxxside.h, client/gui_interface.cpp, client/gui_interface.h, client/include/canvas_g.h, client/mapview_common.cpp, client/overview_common.cpp, client/reqtree.cpp
This brings `QPainter` into the core drawing code, removing the indirection layer and shaving another 400 lines of code.
The affected areas in the clients are:
* The main map (sprites, goto lines, trade routes, … virtually everything but city names)
* The minimap (visible area polygon)
* The tech tree (everything)
* The spaceship report
=> Remove qtg_ indirection for remaining canvas functions

client/layer_terrain.cpp, client/layer_terrain.h, client/tilespec.cpp, docs/Modding/Tilesets/compatibility.rst
The existing "corner" method doesn't work well in hexagonal mode because for N
matching groups ("match type"), it requires N^4 sprites. It gues without saying
that this explodes very quickly. In hexagonal mode, each corner is the meeting
point of only three tiles, making a O(N^3) method a better match.
This patch implements such a method, requiring 2 * N^3 sprites for N groups. It
is limited to ISO|HEX to prevent keep code complexity under control.
The sprite names take the following form:
t.l[N].hex_cell_[left|right]_[g]_[g]_[g],
where the [g] are the first letters of the matching groups. It is expected that
the sprites are cut along the dotted lines in the following schema, which also
shows what `left` and `right` correspond to:
____
.:..\...:.
: R \__:_
.:.../..:.
_:__/ L :
.:..\...:. …
=> Hex corner terrain sprite type

common/player.cpp, utility/shared.cpp
Testing plan:
* Try to use fancy usernames with any characters. Letters and numbers should be allowed, punctuation etc should not. Things like chat should still behave as expected.
* Try to copy a ruleset as `ruleset@abcd` and load it. Should work.
=> Allow @ in filenames and valid UTF letters in usernames

.github/workflows/build.yaml, .github/workflows/coverity.yaml
Also remove a duplicated dep from the normal CI builds.
Closes #927.
=> Add missing QtSvg dependency to Coverity build

server/CMakeLists.txt, server/server.cpp, server/server.h, server/stdinhand.cpp, server/stdinhand.h
On Windows, there is apparently no unified non-blocking API to wait for 
input on stdin.  Thus, call the blocking API from a worker thread.
Tested the following use cases (*before rebasing*):
* Starting from the Windows console
* Starting from Windows Explorer (should be the same, but who knows)
* Starting from the client (I guess stdin is a named pipe in this case)
* Starting from the MSYS console (no idea what it uses, maybe a file)
The thread is only used on Windows, no reason for the extra overhead to
propagate to sane OSes.
Closes #850.
This should also be tested on Linux even though I don't expect differences there.
=> Try once again to fix stdin handling on Windows

server/civserver.cpp, server/sernet.cpp, server/srv_main.h
This allows to bind the server to a specific address, which is often safer.
Support for this option was broken when porting to Qt sockets.
**Test plan**
* Get a list of IP addresses for your machine (`inet` and `inet6` lines in the output of `ip addr`)
* Start a server with `--bind longturn.net`: fails with error
* Start a server, passing any address of the loopback interface (`lo`) to `--bind`: succeeds and client can connect
* Start a server, passing the address of your machine on any other interface (`eth`, `enps`, `wlan`, …): succeeds and client fails to connect for me, but YMMV I'm no networking expert. Client from another machine might be able to connect with this address if it's in the same network.
* Start a server, passing a random address (for instance `123.45.67.89`) fails very …
=> Restore --bind <address> functionality

client/connectdlg_common.cpp
The --bind server option no longer takes hostnames (how to know which IP to
listen to?), but the client was passing "--bind localhost" when starting a
local server. Switch to "--bind 127.0.0.1", which is totally equivalent for
virtually every system out there.
Closes #935.
=> Fix starting the server from the client

client/gui-qt/dialogs.cpp
User Action 1 through 3 may be defined by the ruleset, allow ordering
them through the action selection dialog.
Action Target Kind depends on the ruleset, so dispatch on it at
runtime to determine the semantics of qv2.
Closes #936.
=> Support ruleset-defined custom actions in client

common/scriptcore/api_game_methods.cpp
If lua Tile:is_enemy() is called on a tile with neither enemy units nor
a city, the call to city_owner() will be passed a NULL pcity.
Clearly the ptile != NULL guard was supposed to check pcity instead, so
do that.
=> Fix assertion in api_methods_enemy_tile()

client/control.cpp
The GUI was reacting to each click twice: the first time for the mouse down
event and the second for mouse up (why we're using both for click-like actions
is beyond me). Make sure that we only use mouse down.
Closes #933.
**Test plan:** select worked tiles in the city screen.
=> Fix selecting city worked tiles

.github/workflows/automation.yaml, docs/Contributing/eval-pull-request.rst
By commenting on a PR with a message that contains "Auto clang-format",
maintainers and PR authors can trigger an automated run of clang-format.  This
can be used to fix PRs when their author isn't willing to do so or is simply
not responding.
The action posts a message reminding to avoid this for complex PRs: this action
is mainly intended at PRs with a single commit where the reformatting can be
squashed easily.  Anything more complex should be handled by a human.
Developed and tested in https://github.com/lmoureaux/freeciv21/pull/1.
See https://github.com/longturn/freeciv21/pull/923, https://github.com/longturn/freeciv21/pull/947 for PRs that would [have] benefited from this action.
See https://github.com/longturn/freeciv21/pull/924 for an example where I think use of this action not …
=> Add clang-format automation

.github/workflows/build.yaml
Closes #959.
~This also sends a bot message to the PR with some instructions when `clang-format` fails.~ edit: not possible without heavy workarounds.
=> Run clang-format before starting build checks

common/aicore/citymap.cpp
Use vectors instead of realloc
Tested with 500 turns autogame with ASAN, seems to work well for me.
=> Fix alloc-dealloc mismatch

ai/aitraits.cpp, client/cityrepdata.cpp, client/cityrepdata.h, client/gui-qt/cityrep.cpp, common/player.cpp, common/player.h, server/generator/mapgen_utils.cpp
Changed a few easy reallocs to vectors
=> Begone realloc

server/unittools.cpp
When transforming a non-fuel-using unit to a fueled unit, fill up the
tanks.  When transforming between units with different fuel, add the
difference between their fuel values (thus keeping the ullage constant
and ensuring that a unit that was fully fueled before is fully fueled
after), except never reduce fuel below 1.
If a unit is converting in the same turn it runs out of fuel, and the
conversion would either increase fuel or turn it into a non-fueled
unit, then don't kill the unit; conceptually, let the conversion
happen before the fuel exhaustion.  This makes for a less confusing UX
as players can start converting on the turn that the unit shows as
'low on fuel'.
=> Handle fuel effects of unit conversion/upgrade

ai/default/daieffects.cpp, common/effects.cpp, common/effects.h, common/fc_types.h, common/metaknowledge.cpp, common/reqtext.cpp, common/requirements.cpp, common/requirements.h, common/research.cpp, data/alien/effects.ruleset, data/civ1/effects.ruleset, data/civ2/effects.ruleset, data/civ2civ3/effects.ruleset, data/classic/effects.ruleset, data/experimental/effects.ruleset, data/granularity/effects.ruleset, data/multiplayer/effects.ruleset, data/royale/effects.ruleset, data/sandbox/effects.ruleset, data/stub/effects.ruleset, data/webperimental/effects.ruleset, docs/Modding/Rulesets/effects.rst, server/citytools.cpp, server/cityturn.cpp, server/maphand.cpp, server/rscompat.cpp, server/rssanity.cpp, server/ruleset.h, server/unittools.cpp, tools/ruledit/univ_value.cpp
Add a requirement type `Vision_Layer` that allows `Unit_Vision_Radius_Sq` or `City_Vision_Radius_Sq` effects to apply to `Subsurface` or `Stealth` layers instead of `Main`; make those bonuses apply _after_ subs/invis vision range is capped to 2; and fix a couple of bugs in vision handling.
Add a ruleset effects capability `+Vision_Layer`; and compatibility for old rulesets to retain existing behaviour.  Update the shipped rulesets to retain their old behaviour (except in the case of `stub` where we omit the req on city vision for simplicity).
Closes #893.
=> Unit subsurface vision (sonar)

ai/default/aiferry.cpp, common/aicore/path_finding.cpp, common/aicore/path_finding.h
It improves performance in places a default copy constructor is used instead (Fixes #989)
Additionally, Remove the implementation of some constructors and use the default keyword instead
=> Add move constructor and move assignment for PFPath

ai/CMakeLists.txt, ai/classic/CMakeLists.txt, ai/default/CMakeLists.txt, client/CMakeLists.txt, client/gui-qt/CMakeLists.txt, client/luascript/CMakeLists.txt, common/CMakeLists.txt, common/aicore/CMakeLists.txt, common/networking/CMakeLists.txt, common/scriptcore/CMakeLists.txt, tools/fcmp/CMakeLists.txt, tools/ruledit/CMakeLists.txt, tools/ruleutil/CMakeLists.txt, tools/shared/CMakeLists.txt, utility/CMakeLists.txt
The headers were added because Microsoft Visual Studio's "Solution" view
doesn't show the headers.  However, VS' built-in CMake handling doesn't use the
solution view and is based on folders (much like CMake itself).  There is no
recommendation from the CMake side on how to handle this problem with CMake's
built-in generators for Visual Studio.
Following the VS documentation and the instructions added in #999, one can get
(at least) decent VS support with IntelliSense working.  This doesn't require
keeping the headers in the CMakeLists, so remove them for more idiomatic CMake
code.
This reverts part of commit 6e38a15ac21b75dc616c0c30cec760d026f2598a.
See #1005.
=> Don't include headers in CMakeLists.txt after all

client/gui-qt/page_game.cpp, client/gui-qt/page_game.h, client/gui-qt/top_bar.cpp, client/gui-qt/top_bar.h, data/themes/gui-qt/Classic/resource.qss, data/themes/gui-qt/Necrophos/resource.qss, data/themes/gui-qt/NightStalker/resource.qss, data/themes/gui-qt/System/resource.qss, data/themes/gui-qt/TheLastLaserMaster/resource.qss, data/themes/gui-qt/Web/resource.qss, data/themes/gui-qt/Web/resource.scss
The top bar widget that shows the current treasury and gold income gains two features:
* It turns red when the income is negative.
* Its outline turns red when low on funds.
This should help newbies figure out when something is wrong.
Closes #983.
Changes with respect to the proposed solution in the issue:
* The whole text turns red when income is negative (for a technical reason), and
* The global observer state is not implemented because the economy screen doesn't exist in that mode.
Only Nightstalker is implemented pending UI comments.
Screenshots of the new states:
=> Make the gold indicator widget more informative

.github/workflows/build.yaml, README.md, docs/General/install.rst
The main development target is still 20.04, but testing on 22.04 as well is a
first step towards a complete switch.  I don't expect any breakage since some
of us have been using Arch for development (-> newer versions of everything).
Include a single configuration for now, building with GCC in debug mode to
avoid using too many free Github CPU cycles.
=> Add Ubuntu 22.04 (Jammy) to CI builds

common/style.cpp
` -Werror=maybe-uninitialized` is somehow included into my asan builds after updating my compiler, and this line breaks testing. This commit fixes it.
=> Fix uninitialized variable

server/server.cpp, server/server.h
Server may not shutdown the process, it gets stuck in a loop, waiting for input to the console.
=> Fix: server does not terminate the process

client/layer.h, client/layer_special.cpp, client/layer_special.h, client/tilespec.cpp
Some cached data needs to be updated when the ruleset changes and the tileset
remains the same.  Add a new virtual method in the layer class to trigger this
reset.
Fixes #974.
=> Reset tileset data when the ruleset changes

server/unittools.cpp
A converting unit may (e.g. Submersibles in Aviation ruleset) save
itself from fuel exhaustion by conversion.  In that case, there is
no need to override the unit's existing orders at turn-end and
auto-move it to a nearby refueling point (city, carrier, etc.).
So, condition that auto-move code on !converting_fuel_rescue().
=> Don't auto-return units to refuel if they're converting

server/cityturn.cpp
Units built by cities, including when the city gets disbanded
in the process, were given zero movement initially. That meant
them to be unable to escape to neighboring tiles if the
disappearance of the city made the tile non-native for them.
Ported from: https://github.com/freeciv/freeciv/commit/7b284230005a9cc458d255edb3ecefe3c161ac76
Fixes #1014
I also removed some unused header files.
=> Give cities disbanded to units movement to escape the spot

.github/workflows/release.yaml
Direct pushes to master are forbidden by branch protection rules. Have the
automation create a PR instead, so we can approve it and enable automerge. It's
a bit less convenient than a push but good enough for now. It also lets us
check that the action is working is intended. If this works well, we could
consider enabling automerge from within the action (or pushing directly as it
looks like it's supported via an access token [1]).
Closes #955.
[1] https://github.com/stefanzweifel/git-auto-commit-action/issues/87
=> Untested: Have Autorevision create a PR instead of trying to push

CMakePresets.json
Fixes warning, _FORTIFY_SOURCE requires compiling with optimization
Also change the build type to RelWithDebInfo
=> Fix: Optimize code in ASan build

common/traderoutes.h
It can happen that not all trade partners of a city are known when we draw
trade routes. In such cases we should ignore the unknown trade partner instead
of trying (and failing) to draw the trade route line.
Closes #1059.
=> Check that the trade partner is known

client/minimap.cpp, client/minimap.h
The minimap had logic that allowed the user to drag it around. Remove it to
make sure it stays in the layout.
Closes #1063.
=> Prevent moving the minimap

ai/default/aidata.cpp, ai/default/daidiplomacy.cpp, common/player.cpp, common/player.h, common/research.cpp, server/advisors/advdata.cpp, server/connecthand.cpp, server/edithand.cpp, server/gamehand.cpp, server/maphand.cpp, server/plrhand.cpp, server/plrhand.h, server/report.cpp, server/sanitycheck.cpp, server/savegame/savecompat.cpp, server/savegame/savegame2.cpp, server/savegame/savegame3.cpp, server/score.cpp, server/srv_main.cpp, server/stdinhand.cpp, server/techtools.cpp, server/unittools.cpp
It always returns a constant, 
Inspired from https://github.com/freeciv/freeciv/commit/62fb8c8f66baf67bbd7eebcb03982ffc5c024702, why call it once when you dont have to call it at all.
=> Remove function  player_slot_count()

client/CMakeLists.txt, client/helpdlg.cpp, client/hudwidget.cpp, client/layer.cpp, client/layer.h, client/layer_background.cpp, client/layer_background.h, client/layer_base_flags.cpp, client/layer_base_flags.h, client/layer_darkness.cpp, client/layer_darkness.h, client/layer_special.cpp, client/layer_special.h, client/layer_terrain.cpp, client/layer_terrain.h, client/layer_units.cpp, client/layer_units.h, client/mapview_common.cpp, client/mapview_common.h, client/tileset_debugger.cpp, client/tilespec.cpp, client/tilespec.h, common/tile.cpp
This PR refactors the code that draws units on the map and some code around it. I wanted to implement #429 but figured that some refactoring was needed first. This PR introduces no behavior change.
**Things to check**
* Are units still drawn where they should?
* Do options like drawing only the focused unit still work as intended?
* Does it crash?
=> Refactor unit map layers

client/CMakeLists.txt, client/colorizer.cpp, client/colorizer.h, client/tilespec.cpp, client/tilespec.h, data/alio.tilespec, data/amplio.tilespec, data/amplio2.tilespec, data/cimpletoon.tilespec, data/hex2t.tilespec, data/hexemplio.tilespec, data/isophex.tilespec, data/isotrident.tilespec, data/toonhex.tilespec, data/trident.tilespec
Implements #429 for units. No tileset supports it yet (I have WIP changes for amplio2 but it will take more time and a different kind of review).
Will rebase once we get #1083 
**Testing it**
* Open `units.png` for your favorite tileset and draw in magenta over the units (`#ff00ff` or any color with the same HSL hue)
* Set `replaced_hue = 300` in the `tilespec`
* Load a game with many units and many nations and check how units are colored with the player color!
* Look around other places where units are displayed to check for weird displays (I don't think any of them uses the player color)
=> Add tilespec support for more colorful units

client/tilespec.cpp, data/alio.tilespec, data/amplio.tilespec, data/amplio2.tilespec, data/cimpletoon.tilespec, data/hex2t.tilespec, data/hexemplio.tilespec, data/isophex.tilespec, data/isotrident.tilespec, data/toonhex.tilespec, data/trident.tilespec
Equivalent of #1095 for cities.
Partially modified amplio2 sprites for testing: [cities.zip](https://github.com/longturn/freeciv21/files/9077601/cities.zip) (`replaced_hue = 300`, magenta).
=> More colorful cities

client/menu.cpp
Tested on Linux (KWin/X11) only.
Closes #1094.
=> Remember the previous window state when leaving fullscreen

client/reqtree.cpp
Lines are drawn with a 2px width, and we must take this into account in the
position of their starting point.
Closes #1091.
=> Fix line alignment in the tech tree

client/sciencedlg.cpp
QTooltip only ever shows a single tooltip so there's no chance this creates
multiple tooltips.
Closes #1092.
=> Tech tree: show the new tooltip even if another is active

client/icons.cpp, client/menu.cpp, client/minimap.cpp, client/minimap_panel.cpp, client/minimap_panel.h, client/minimap_panel.ui, client/page_game.cpp, client/page_game.h
Closes #1096.
I chose not to remove the option (for now), instead implementing a more or less sensible behavior.
=> Fix minimap show/hide

.github/workflows/build.yaml
Looks like the issue was fixed upstream.
This reverts commit aeb24ebf786fe1e503efc1ba8b1d20747364b14b.
Closes #1043
=> Revert "Temporarily disable builds on Ubuntu 22.04"

.github/workflows/build.yaml, patches/karchive.diff
The CI started to fail because of an outdated cache after the latest release of
emsdk. Update the cache key to pull a fresh cache.
=> Fix running the wasm CI

utility/shared.cpp
After it is installed, Freeciv21 is supposed to find its default set of
scenarios independent from where it's started from. Use default_data_path() to
build a list of paths to search in.
Closes #1133.
Here is the list of paths on my Linux machine for `freeciv21` installed in `/usr/local/`: `"./scenarios", "data/scenarios", "/home/louis/.local/share/freeciv21/3.0/scenarios", "/usr/local/share/freeciv21/scenarios", "/home/louis/.local/share/freeciv21/scenarios", "/usr/share/plasma/freeciv21/scenarios", "/home/louis/.local/share/flatpak/exports/share/freeciv21/scenarios", "/var/lib/flatpak/exports/share/freeciv21/scenarios", "/usr/local/share/freeciv21/scenarios", "/usr/share/freeciv21/scenarios", "/var/lib/snapd/desktop/freeciv21/scenarios"`
=> Fix loading scenarios once installed

client/chatline.cpp, client/messagewin.cpp, client/widgetdecorations.cpp, client/widgetdecorations.h
Now we can support several types of "resizable" at the same time
Example:
```cpp
setResizable(resizable_flag::top | resizable_flag::topLeft
| resizable_flag::topRight | resizable_flag::bottom
| resizable_flag::bottomLeft | resizable_flag::bottomRight
| resizable_flag::left | resizable_flag::right);
```
=> Widget Resizable now support multiple types of resize

server/savegame/savecompat.cpp
It caused a use-after-free bug
=> Fix typo in savecompat.cpp

utility/fcintl.h
We need to include fc_config.h in fcintl.h to control enabling NLS. Else we're
defining "textdomain" as nothing, which doesn't play nice with libintl.h.
=> Fix build with NLS enabled

client/CMakeLists.txt, client/mapview.cpp, client/mapview.h, client/page_game.cpp, client/renderer.cpp, client/renderer.h
It is meant to incorporate the functionality of mapview_common needed to draw
the map. Right now it delegates most (all) of its work to mapview_common.
Developed on top of many patches from #1169 but auto rebase worked fine so I'm making a PR to `master`.
=> Introduce a map renderer class

client/dialogs.cpp, client/include/repodlgs_g.h, client/menu.cpp, client/page_game.cpp, client/page_game.h, client/top_bar.cpp, client/unitreport.cpp, client/unitreport.h
`units_reports` is the units list widget. This replaces static functions to pop it open and close it with Qt signals and slots.
Widgets are better managed by their parents: this way the parent knows exactly
when and why its children change (well, signals and slots might break this in
principle, but the parent knows how it connects them).
=> Remove static calls to units_reports

dependencies/sol2/CMakeLists.txt
tolua was implicitly converting floats to ints, but sol2 chokes on this. For
backward compatibility and to fix our own rulesets, disable this check in sol.
Closes #1161.
=> Allow implicit float to int conversions in sol2

client/page_load.cpp, client/page_scenario.cpp, server/stdinhand.cpp, utility/shared.cpp, utility/shared.h
Use QFileInfo and QFileInfoList instead. While we're at it, simplify the API a
little.
=> Get rid of fileinfo and fileinfo_list

client/citydlg.cpp, client/citydlg.h, client/mapctrl.cpp, common/mapimg.cpp, common/nation.cpp, common/nation.h, server/auth.cpp, server/ruleset.cpp, tools/civmanual.cpp, tools/ruleutil/rulesave.cpp
A handful of Coverity warnings popped up in the last month. This should clear them all.
Special thanks to Synopsis for 55336e7b7bc37cb046c78a259fa6a99dbb985266: *The client was crashing when Ctrl+Alt+clicking outside of the map (this shortcut is bound to the "create link" action).*
=> Fix new Coverity warnings

client/client_main.cpp, client/connectdlg_common.cpp, client/options.cpp, client/options.h, client/tilespec.cpp, client/tilespec.h, data/alio.tilespec, data/amplio.tilespec, data/amplio2.tilespec, data/cimpletoon.tilespec, data/hex2t.tilespec, data/hexemplio.tilespec, data/isophex.tilespec, data/isotrident.tilespec, data/toonhex.tilespec, data/trident.tilespec
The last used tileset was saved in the options file, but that value wasn't shown anywhere in the interface. It was then used *instead* of the tileset configured in the settings when the topology matched. This was a source of confusion. Get rid of this behavior by removing the hidden option.
---
The tileset in pregame isn't well defined because the topology isn't known yet. Always start servers with the default ruleset, and load a tileset based on that.
If the user want to spawn a client with a given ruleset, they can use the `-r` option.
=> Don't try to set the ruleset based on the tileset

client/page_load.cpp, client/page_load.ui
This PR changes the layout of the "load game" screen to jump around less. There are still huge improvements to be made but I think it's a good start.
The new layout looks like this:
After #1165.
Related to #115.
=> Improve the layout of the "load game" page

client/messagewin.cpp
Scrolling per item results in jumpy behavior, especially with messages of
varying height. This in turn results in scrolling being hard on imprecise
devices that generate many scroll events, like touchpads.
This was found to be the underlying issue in a request to add arrows to scroll
bars, #1162.
Closes #1162.
=> Scroll the messages window per pixel

client/citydlg.cpp, client/client_main.cpp, client/climisc.cpp, client/climisc.h, client/control.cpp, client/control.h, client/dialogs.cpp, client/dialogs.h, client/goto.cpp, client/goto.h, client/gotodlg.cpp, client/hudwidget.cpp, client/include/dialogs_g.h, client/include/mapview_g.h, client/mapctrl_common.cpp, client/mapview.cpp, client/menu.cpp, client/packhand.cpp, client/text.cpp, client/text.h, client/tilespec.cpp, common/unitlist.cpp, common/unitlist.h
I would like to have some decent container to use in #805 (if several units are
selected, I want the right click menu to apply to all of them, which will
require a container).
Change focus_units (=get_units_in_focus()) to be a std::vector<unit *>. This
has implications in a lot of places, which are also modified to use
std::vector.
**Test:**
Do everything you an with your units.
=> Use std::vector for the list of focused units

common/nation.cpp
It wasnt explicitly set as default, and Asan complains
Fixes #1189
=> Set server.rgb to nullptr in the nationtype constructor

.github/workflows/clang-tidy.yaml
Otherwise it can't find headers. Also reduce the number of steps using features
of clang-tidy-review.
Hopefully this works...
=> Use compile_commands.json with clang-tidy

client/mapview_common.cpp
The cached mapview texture always gets resized in tile_width/height increments.
One needs to redraw only when the cache got resized, not every time. The code
doing that had been broken since https://github.com/longturn/freeciv21/commit/9bd5b4a91b87fe4e859bd8439dc2408382380078; fix it.
This should slightly improve performance when resizing the main window.
On top of #1169
=> Resize the canvas a bit less often in map_canvas_resized

client/control.cpp
Eagerly waiting for std::erase in C++20.
Closes #1191.
=> Proper erase-remove in control_unit_killed

client/citydlg.cpp, client/citydlg.h, client/citydlg.ui, client/mapview_common.cpp, client/mapview_common.h, common/city.cpp, common/city.h
Closes #805
Closes #1200
**Test plan**
* Try to repro the above issues
=> Improve the city dialog unit lists

client/citydlg.cpp, client/citydlg.h, client/citydlg_common.cpp, client/citydlg_common.h
Closes #438.
The citizen types (happiness and entertainers) is shown in the tooltip.
The patch itself is rather small, but there's a lot of refactoring to make it less error-prone in the end.
=> Add the city size and citizen happiness next to other city stats

client/text.cpp, client/text.h, common/city.cpp, common/city.h
Improve the city dialog tooltip text that explains how many citizens are
unhappy because of the number of cities. Write two paragraphs: the first
describing the rules for the current player, and the second the status of the
city at hand. The total number of citizens that can be made content without
improvements is also shown; see #269.
All cities start with 4 content citizens. Once you have more than 12 cities, a citizen becomes unhappy.
You have 36 cities, resulting in a maximum of 3 content citizens. In this city of size 14, **3 citizens are content.**
All cities start with 4 content citizens. Once you have more than 12 cities, a citizen becomes unhappy.
You have 36 cities, resulting in a maximum of 3 content citizens. In this city of size 2, **all citizens are content.**
All cities …
=> Expand the text for empire size unhappiness

client/text.cpp, client/text.h
Same as (and on top of) #1206 for luxury. The rules are much simpler and so the code also is.
Improve the city dialog tooltip text that explains how many citizens are
made happier by luxury. This provides a lot more information than the previous
"Luxury: %d total", which will hopefully help towards https://github.com/longturn/freeciv21/issues/269.
For each 2 luxury produced in a city, a citizen becomes happier. This city generates no luxury.
For each 2 luxury produced in a city, a citizen becomes happier. This city generates a total of 1 luxury, not enough to have an effect.
For each 2 luxury produced in a city, a citizen becomes happier. This city generates a total of 5 luxury.
2 citizens are made happier using 4 luxury. 1 luxury is not used.
For each 2 luxury produced in a city, a …
=> Expand the city dialog text for luxury spendings

client/menu.cpp
tileset_custom_load() was still using some old tileset option names from
Freeciv 2.6. Use only Freeciv21 names.
Closes #525.
=> Don't use nonexistent tileset option names

client/hudwidget.cpp
Otherwise it was showing garbage.
Closes #1185.
=> Initialize defender pixmap contents in hud_unit_combat

client/text.cpp, client/text.h
Follow-up of #1206, #1208, and #1209 for citizen nationality.
Explain the rules and give the result of the calculation. The rule sentence is
not fully correct but it's easier to understand than the actual mechanism.
Hopefully helps with #269.
All examples are with nationality enabled.
The presence of enemy citizens can create additional unhappiness. However, it is not the case in this city.
For every 2 citizens of an enemy nation, one citizen becomes unhappy.
There is **no enemy citizen** in this city.
For every 2 citizens of an enemy nation, one citizen becomes unhappy.
There are 5 enemy citizens in this city, resulting in **2 additional unhappy.**
=> Expand the city dialog text for nationality

client/menu.cpp, client/menu.h
The code was needlessly convoluted, using a custom list class that wasn't
updated properly. This was the most likely cause of a crash reported in #1125.
Untested on my end, but the code was clearly completely wrong.
Closes #1125.
=> Remove useless clutter around delayed orders

client/hudwidget.cpp, client/hudwidget.h, client/mapview.cpp, client/menu.cpp, client/page_game.cpp
When, after starting a game, the user does /observe to his own player,
client.conn.playing is null for a brief period of time. While it's null, one
can't evaluate whether actions are valid or not because we don't know who we
are playing. This was triggering an assertion in update_actions(); just skip it
when we're not playing anyone (same as when we don't have a focused unit).
Closes #457.
=> Prevent an assertion when observing 

client/text.cpp, client/text.h
Improve the description of martial law by listing the number of units applying
it and the total number of citizens made happier as a result.
Greatly expand the description of military unhappiness by explaining the three
effects that come into play and providing numbers similiar to the above.
Should help with #269.
Up to 2 military units in the city may impose martial law. Each of them makes 2 unhappy citizens content.
1 military unit in this city imposes the martial law. <b>1 citizen</b> is made happier as a result.
Military units in the field may cause unhappiness. The unhappiness caused by military units is reduced by 3 with respect to its normal value.
This city supports 3 agressive military units, resulting in <b>1 additional unhappy citizen.</b>
=> Expand the city dialog text for military happiness

server/unithand.cpp
Ported: https://github.com/freeciv/freeciv/commit/c75e91ebd42fe29271e9b336e12f7ee52a4baedb
Along with a few refactoring commits,
=> do_attack(): Shrink city only after complete removal of the defender 

scripts/eval-pr
=> eval-pr: provide more instructions for autogame and multiple runs

client/chatline.cpp, client/citydlg.cpp, client/cityrep.cpp, client/client_main.cpp, client/climisc.cpp, client/control.cpp, client/dialogs.cpp, client/gotodlg.cpp, client/hudwidget.cpp, client/mapctrl_common.cpp, client/mapview.cpp, client/mapview.h, client/mapview_common.cpp, client/mapview_common.h, client/messagewin_common.cpp, client/minimap.cpp, client/packhand.cpp, client/page_game.cpp, client/renderer.cpp, client/renderer.h, client/tilespec.cpp, client/unitreport.cpp
There are two main changes in this PR:
* When centering the map on a new tile, a "busy" loop was started within the mapview code. Rewrite this loop with `QPropertyAnimation`, but keep the old code around because not all calls have been ported yet.
* Move the handling of map updates to the renderer class. This way, when there is an update the renderer gets notified directly and decides on its own when to update the cached maps.
=> Implement map centering with Qt animations and move map updates to the renderer

client/attribute.cpp, common/networking/packets.cpp, common/player.cpp, common/player.h, server/savegame/savegame2.cpp, server/savegame/savegame3.cpp
I had no idea where the double free came from, so I just refactored to avoid
explicit delete[] altogether.
Closes #1224.
**Testing**
The attributes block is used to store governor information. Check that governors can still be operated correctly; that they are saved and reloaded; that both old and new saves can still be loaded.
=> Fix a double free of the attributes block

client/text.cpp
Improve the description by explaining which effects are active and, for two of
them, what contributes to their value (the third one is a simple binary effect,
and that's harder to display properly). Helps #269.
Factor out a function to build such effect descriptions so we don't need to
repeat the same code over and over again.
Granted, I wasn't very inspired when writing the default text.
With this PR, I'm happy to close #269, so:
Closes #269.
=> Expand the city dialog text for wonders

.gitignore, client/renderer.cpp, doc/freeciv.doxygen
This PR:
* Turns Doxygen to use C++ mode as we're writing more and more C++ code as opposed to C.
* Adds the files produced by Doxygen to `.gitignore`
* Improves the documentation of the newly introduced `renderer` class
To run Doxygen, use `doxygen doc/freeciv.doxygen`.
=> Optimize Doxygen docs some

docs/Contributing/msys2.rst
=> Docs: Update MSYS2

client/editor.cpp, client/mapview_common.cpp, client/mapview_geometry.cpp, client/mapview_geometry.h
In the initial implementation of gui_rect_iterator, it was assumed that each
iteration point corresponds to a single type of object in the geometry. This
was without counting on the laziness of Freeciv's hex implementation, which
simply collapsed one of the vertical edges into a corner. In hex mode, some
iteration points need to be corners and edges at the same time.
This PR also adds more documentation to the code.
Closes https://github.com/longturn/freeciv21/issues/1253.
=> Fix horizontal edges not showing in iso-hex grids

client/menu.cpp
This improves item grouping and thus usability.
See #1237.
=> Add two separators to the multiplayer menu

client/page_game.cpp
They don't do anything.
Closes #1225.
=> Hide the science and economy buttons for global observers

client/citydlg.cpp, client/citydlg.h
I encountered a class of crashes where city_dialog::pcity was garbage. Make
sure that it's always nullptr while the city screen is hidden.
Zoom in and out many times while also constantly switching player. `master` crashes occasionally, this patch prevents the crash.
=> Initialize city_dialog::pcity

client/page_game.cpp, client/top_bar.cpp, client/top_bar.h
The tooltip of the "Cities" button in the top bar was showing the number of
cities by querying the help text for the player's capital. Now that we have
better help texts, this string is more specific about the capital and breaks in
the context of the top bar.
Change back the tooltip to what it was before, i.e. a simple city counter.
=> Don't use the capital for the tooltip of the city top bar button

common/city.cpp, common/city.h, common/fc_types.h, common/game.cpp, common/game.h, common/unit.h, server/cityhand.cpp, server/citytools.cpp, server/citytools.h, server/cityturn.cpp, server/diplomats.cpp, server/sernet.cpp, server/sernet.h, server/server.cpp, server/settings.cpp, server/srv_main.cpp, server/srv_main.h, server/unittools.cpp, server/unittools.h
This ports two of the LT patches mentioned in #1150:
* Add the option for unitwaittime to apply to unit activities
* Expand unitwaittime to affect newly-built units and captured/bribed units
I don't think we should port the other two.
The port itself is untested, but the original patches have been used in production.
Closes #1150.
=> Port unit wait time patches

server/commands.cpp, server/commands.h, server/stdinhand.cpp
Add three new timeout-related server commands:
- timeoutshow displays the current timeout
- timeoutadd adds time to the current turn
- timeoutset sets the remaining time for the current turn
They are named timeoutsomething for three reasons:
- timeoutincrease already exists
- it's easier to find them if they're together in /help commands
- sub-commands like "timeout show" are not feasible with the current
implementation
This is heavily inspired from an earlier patch used by LT with 2.6,
41cc12b401fe4a9db8d22b78039561710fff59e3. The syntax is however more flexible,
allowing for hours or minutes to be passed directly without doing any
calculation.
Closes #1151.
=> Add commands to control the timeout

client/citydlg.cpp
When opening a city without any units, the "Present units" list is hidden to
save space. It was never restored afterwards.
=> Fix the city screen "Present units" list disappearing

client/chatline.cpp, client/chatline.h, client/fc_client.cpp, client/fc_client.h, client/messagewin.cpp, client/page_game.cpp, client/widgetdecorations.cpp, client/widgetdecorations.h
Had some "fun" reviewing the chat widget code and fixing most open issues. See commit messages for details.
Closes #1056.
Closes #1074.
Closes #1145.
Closes #1144.
Closes #1143.
Closes #1159.
Closes #1158.
Closes #739.
=> Fix the chat widget

docs/Contributing/dev-env.rst, docs/Contributing/msys2.rst, docs/Contributing/visual-studio.rst, docs/General/Manuals/client-manual.rst, docs/General/install.rst
Merged all language around installation to a single place. Add support for MacOS X. Cleaned up other files referencing.
Closes #1239
=> Docs: Installation consolidation

.github/workflows/build.yaml, README.md, docs/Contributing/dev-env.rst, docs/General/faq.rst, docs/General/install.rst
=> Change Mac OS X to macOS

client/options.cpp
This could happen in pre-game, or for global observer.
See osdn #45310
Ported from: https://github.com/freeciv/freeciv/commit/a8570f3b61cbead146a87820fdeb57862b22dca1
=> Fix crash when non-player changes ai_manual_turn_done

client/fonts.cpp
We have enabled Qt's transparent handling of HiDpi, and thus the manual scaling
that was done in configure_fonts() was useless. Worse, on HiDpi diplays, it
would choose larger fonts to make the UI bigger, which Qt also does internally.
This resulted in huge fonts on such systems.
Simply delete the scaling code. Use the opportunity to tidy up a bit.
See #1273.
=> Don't default to huge fonts of HiDpi systems

client/themes.cpp, data/themes/gui-qt/Classic/theme.conf, data/themes/gui-qt/Necrophos/theme.conf, data/themes/gui-qt/NightStalker/theme.conf, data/themes/gui-qt/System/resource.qss, data/themes/gui-qt/TheLastLaserMaster/theme.conf
In order to achieve consistency in what is displayed regardless of the system
theme, the system color scheme needs to be overriden. Previously only 3 colors
were changed (and for a single theme), which was causing readbility issues when
the system color scheme didn't match the theme.
Always fill the system QPalette with dark colors for dark themes and light
colors for light themes. Use the Breeze Light and Breeze Dark palettes as
references.
There are still some issues when changing the theme on the fly, much like #762.
It looks fine after restarting the game.
=> Set a baseline palette for all themes except System

client/top_bar.cpp
=> Bump top bar icons to 22px

lua/database.lua
The database.lua script does not work out of the box.
To make it work I had to
* install lua-sql and md5 with `dnf install lua-sql-sqlite lua-md5`
* use require to load the modules in the script
=> Update database script to load external lua modules

client/goto.cpp, client/goto.h, common/path_finder.cpp, common/path_finder.h
=> Fix cancelling goto with ESC

client/CMakeLists.txt, client/clinet.cpp, client/connectdlg.cpp, client/fc_client.cpp, client/fc_client.h, client/include/pages_g.h, client/packhand.cpp, client/page_load.cpp, client/page_scenario.cpp, client/qtg_cxxside.h
This fixes two cases in which the game would become unusable:
* Connect to network game, but don't enter your password; go back to the main page and try again (this is likely #785)
* Start new game, go back to the main page and try again (#1009)
Doing it in a single PR because the two issues ended up sharing a common root cause.
Closes #785.
Closes #1009.
=> Fix deadlocks in the main menu

ai/default/daieffects.cpp, client/plrdlg.cpp, common/effects.cpp, common/effects.h, common/game.cpp, docs/Modding/Rulesets/effects.rst, server/plrhand.cpp, server/rscompat.cpp, server/ruleset.h
The client has always known which small wonders any player had built (#318). This adds code to show this in the client. For backward compatibility, the patch also hides small wonders by default, keeping only great wonders. This can be controlled using a new effect `Wonder_Visible`. All shipped rulesets use the old way.
Closes #318.
=> List small wonders in the client, but hide them by default

docs/General/index.rst, docs/General/on-the-server.rst
The intent of this page is to help people set up their own server. It should be an introduction with pointers to the relevant parts of the upcoming server manual.
=> Add a new documentation page about Freeciv21 on servers

client/control.cpp, client/goto.cpp, common/path_finder.cpp, common/path_finder.h
Add a flag to the path finder class to control whether it should include
unknown tiles in the search. Bind it to the corresponding gui option when
creating the finders.
This restores the ability to produce paths going through unknown parts of the
map, which is useful in some circumstances.
Closes #890.
=> Restore goto into the unknown

common/networking/packets.cpp, common/networking/packets.h
Improper use of QString::count() to obtain the length of the utf-8 encoded
string resulted in help texts being truncated when they contained multibyte
characters. In addition, a possible buffer overflow was possible with help
texts longer than MAX_LEN_PACKET (4096 bytes). Fix all of this by using
qstrncpy properly.
In addition, simplify packet_strvec_compute to use QStringList::join().
Closes #1034.
=> Fix sending help texts with multibyte characters

client/chatline.h, client/page_game.cpp
The reported bug was that the widget will acquire a wrong size if the map view
is resized while it's closed.
Hoping that nobody will find the not-reported bugs.
Closes #1290.
=> Fix reported chat bug, don't fix not reported ones

common/movement.cpp
Using can_step_taken_wrt_to_zoc in the path finding code (through
unit_can_move_to_tile) makes it possible that unseen tiles are passed to it. We
should therefore not assume that the terrain of the tile is known.
Given our inability to reproduce #1315, this may not be a complete fix. It does protect the code path shown in the stack trace there. I looked around a bit and couldn't find any other unchecked use of `tile->terrain` in the path finding code.
Closes #1315.
=> Protect can_step_taken_wrt_to_zoc against null terrain

client/options.cpp
"Overview" sounded like the tab was about something like an overview of
available settings. The word "minimap" is preferred as per our style
guidelines.
Closes #1241.
=> Change the "Overview" options tab to "Minimap"

client/citydlg.cpp
It's never visible, so the menu would do nothing. The implementation is also
buggy when triggered while the widget is hidden.
Closes #1126.
=> Forbid toggling the minimap from the city view

client/minimap.cpp
Tiny differences between the results of floating-point calculations that would
yield the exact same results in infinite precision culminated into off-by-one
errors in the calculation of the viewport coordinates on the minimap. Round the
floating-point results when converting them back to integers. This change might
lose some formal accuracy but the difference is invisible in practice.
Closes #1128.
=> Fix slanted lines in the minimap view rectangle

docs/Contributing/capitalized-terms.rst, docs/Contributing/style-guide.rst
As we discussed on Discord, capitalizing generic terms such as `tile` and `city` looks terrible in some cases:
> For the display of national Borders (similar to those used in Sid Meier’s Alpha Centauri) each Map Tile also has an owner field, to identify which nation lays claim to it. If game.borders is non-zero, each City claims a circle of Tiles game.borders in Vision Radius. In the case of neighbouring enemy Cities, Tiles are divided equally, with the older City winning any ties. Cities claim all immediately adjacent Tiles, plus any other Tiles within the Border radius on the same continent. Land Cities also claim Ocean Tiles if they are surrounded by 5 land Tiles on the same continent. This is a crude detection of inland seas or Lakes, which should be improved upon.
I propose to ditch …
=> Recommend capitalization in fewer cases

server/server.cpp
At least on Linux, one needs to force QFile to read from stdin for it to notice
that it can read a line or that EOF was reached.
This is a redo of c8427ec2dc6cfcd2383af85f0648630fe894dcbd after it was undone in 38eac2f98d4a8e5975a4060c654d3003398214b5.
Closes #1342.
=> Handle non-interactive stdin better

client/menu.cpp
Hiding units gives a better view of the terrain beneath them. Requested by
Corbeau.
Closes #1351.
=> Add a menu entry to toggle unit visibility

.github/workflows/build.yaml, docs/Contributing/msys2.rst
Explicitly adds some environment variables that we set in `release.yaml` to `build.yaml` to ensure that MSYS2 knows some extra path information as well as that we do not want to use `vcpkg`.
=> Fix MSYS2 CI

.github/workflows/clang-tidy.yaml
Codacy has built-in support for clang-tidy, which is leveraged to produce
reports. This is achieved by running a two-steps Github Action on pull
requests. The first step, that runs without particular permissions, compiles
and runs clang-tidy. The second has more permissions and can use a secret API
key to upload the results to Codacy.
Building the code is needed to obtain a useful report, because clang-tidy spits
an error and terminates when the generated files (speclist, lua stuff, ui files, etc.) 
are absent.
Tested at https://github.com/lmoureaux/freeciv21/pull/3/ / https://github.com/lmoureaux/freeciv21/actions/runs/2985944779
=> Use Codacy to generate reports from clang-tidy output

cmake/FreecivInstall.cmake
=> Fix an issue on Linux when nothing is set for CMAKE_INSTALL_PREFIX 

common/path_finder.cpp
Fix three rather stupid bugs due to rapid development of the path finding algo, including #1360.
~~**Bug:** unloading foot soldiers from a boat gives incorrect results now :(~~
Closes #1360.
I tested unloading bombers and fighters from a carrier and dropping paratroops.
=> Fix a few path finding bugs

server/unittools.cpp
When Leonardo's Workshop upgrades units, it starts by collecting a list of upgradeable units and then pick upgrades at random. This doesn't work if upgrading one unit prevents another from being upgraded, which can happen with unique units. Consider for instance the following upgrade chain of unique units:
A -> B -> C
If a player has one A and one B, and discovers the technology for C, both the A and the B units will be candidates for Leo upgrade. Once one of them is upgraded, the second can't be upgraded anymore because it would create two C units. This patch fixes the handling of this corner case in the server.
This is a straightforward port of a LT commit.
Closes #1153.
=> Fix a crash when auto-upgrading unique units

client/fonts.cpp, client/fonts.h, client/gui_main.cpp, client/options.cpp
Right now it assumes there is no `rc` file and then loads the font if not found in the font database from the filesystem and sets the defaults. I think there might need to be another check, but not sure where from.
Closes #1273
=> Load Linux Libertine Font

data/multiplayer/README.multiplayer, docs/Getting/Manuals/client-manual.rst, docs/Getting/compile.rst, docs/Playing/faq.rst
Quick sed really. On top of #1376 
Closes #1364
=> Consistent use of "Longturn" instead of "LongTurn"

client/control.cpp, client/goto.cpp, common/path_finder.cpp, common/path_finder.h, server/maphand.cpp, server/unittools.cpp, server/unittools.h
This has grown quite big...
The original commit https://github.com/longturn/freeciv/commit/1945cd8f3c solved two issues:
* UWT could be bypassed by forced moves on the server side (e.g. terraforming).
* Bounced units when breaking an alliance allowed disembarking without losing MP (related to a now-removed `slow_invasions` server setting)
I think the first issue is better fixed elsewhere, so I have a very simple commit for that.
The second issue looks totally different in Fc21 because unit moves are now controlled by action enablers. After a few failed attempts, I chose to run the fully-fledged path finding algorithm to legal paths for the unit and pick one at random.
Here are a few cases where unit "bouncing" happens:
* Upon breaking alliance, units in transports and cities get bounced …
=> Port 1945cd8f3ccea261dc8c6ff769e42543aca32a31

server/cityturn.cpp
When a city has negative shields and doesn't manage to disband enough offending
units, it starts killing citizens instead, one per free unit upkeep. Except
this wasn't working: the units were always counted as if disbanding them had
succeeded. Then, when killing citizens the shields weren't given back to the
city and the negative shields were causing an assertion in the coinage
code.
Closes #1332.
=> Fix killing citizens when can't disband units

.github/workflows/release.yaml
No related issue. Added since we are doing the same for the macOS `.dmg`, figured it good to offer for all of our assets at release.
=> Add sha256 hash files to the source archives

.github/workflows/build.yaml, dist/Info.plist
This PR does two things:
1. It adds support for fc21:// links on macOS
2. It adds support of uploading a `.dmg` to a build's artifact list to aid testing outside of a release
Closes #916
=> Add support for fc21:// on macOS

docs/Contributing/style-guide.rst, docs/Manuals/client-manual.rst, docs/Playing/how-to-play.rst
Branch name would suggest game manual, but Discord conversation derailed it. While here, found out how to use `:ref:` role properly. Fixed cross link in how to play and document the usage in style guide. No referenced issue.
=> Documentation links fixes

docs/Getting/compile.rst
Docs: Add missing libsqlite3-dev package to Debian steps. I wiped my laptop to start from scratch and found an error in the set of packages. No related issue.
=> Docs: Add missing libsqlite3-dev package to Debian steps

data/amplio2/units.spec, docs/Modding/Rulesets/nations.rst, docs/Modding/Tilesets/ts-breaking-changes.rst, docs/Modding/index.rst
Add a compatibility file for tilesets relying on Amplio2 `units.spec`. Also documents breaking changes.
Closes #1429
=> Amplio2 Units compatibility fix

.github/workflows/release.yaml
While it's being added to the documentation, our actions will be more understandable if described in the PRs themselves. And it's also a useful reminder to avoid checking the docs in the first place.
See #1427 and #1435.
=> Add a message reminding to close-open the AutoRevision PR

server/unittools.cpp
Someone had written stupid code and disregarded a coverity warning.
Closes #1442.
=> Fix unit bouncing crash

client/chatline.cpp
Otherwise it keeps growing, which ends up taking O(n^2) time because of a copy taking place somewhere in the code.
-> very significant speedup observed when the server sends many messages
=> Clear the chat line completion list before filling it

ai/default/daieffects.cpp, common/effects.cpp, common/effects.h, docs/Modding/Rulesets/effects.rst, server/unittools.cpp
Add an effect Nuke_Infrastructure_Pct that allows the destruction of extras located within the blast area of nuclear weapons. Destroying infrastructure makes large-scale nuclear warfare more difficult because roads and rails need be rebuilt before tanks can ride them again to reach the next city.
This is a rewrite of 8691fa8e38c56c6fa066c77aadf1eab1df5e620b in the 2.6 LT repo. Extras of category "Infra" can potentially be destroyed in nuclear blasts, with an effect-configurable chance. Contrary to the original commit, hidden extras can be blasted away just like they can be (target-)pillaged; this can be prevented with suitable rmreqs.
See #1155.
**Test Plan**
Add the following to your fav ruleset and drop a nuke:
```ini
[effect_nuke_infrastructure_pct]
type    = "Nuke_Infrastructure_Pct" …
```
=> Make nukes destroy infrastructure

client/unitreport.cpp, client/unitreport.h
=> Right-clicking within Units widget closes it and doesn't change appearance of "Units" button in top bar

common/path_finder.cpp
This preserves the paradropping ability for the player to use later on. The optimal algorithm depends on the requirements for "Paradrop Unit". MinMoveFrags is common so try to preserve MP (and health), but this is a heuristic.
Closes #1474.
=> Goto: Avoid paradropping if it's not faster

client/fc_client.cpp, client/fc_client.h, client/gui_main.cpp, client/gui_main.h, client/page_main.cpp, client/themes.cpp
The only thing it was doing was calling QApplication::quit(). Make that explicit instead.
=> Remove fc_client::quit()

client/widgetdecorations.cpp
It was possible to grab a corner of the Messages widget and move it in a direction in which moves supposedly were disallowed (for the top left corner, up or down; for the bottom right corner, left or right), effectively moving the widget out of the corner. Fix the logic used to determine which edges can be moved in a drag-and-drop.
=> Fix a bug where the Messages widget could be moved

client/listener.h, client/menu.cpp
It's big because rendering is no longer synchronous, so I had to switch to an async callback.
Closes #1486.
=> Fix saving map images

docs/Getting/compile.rst, server/plrhand.cpp, utility/fcintl.h
This fixes the build failures recently reported on Arch and Gentoo when NLS is disabled. The documentation is also modified to stop recommending less tested non-default settings and build tools (including the modpack installer).
=> Fix build with NLS disabled and GCC 11

client/mapview.cpp, client/mapview.h
Support the following gestures:
* Mouse wheel/touchpad scroll gesture: scroll the map
* Shift+wheel/touchpad: scroll the map with x and y inverted
* Ctrl+wheel/touchpad: zoom
This is consistent with the gestures widely used in browsers and other software.
=> Add support for scroll events on the map

client/hudwidget.cpp, client/icons.cpp, data/themes/gui-qt/Classic/resource.qss, data/themes/gui-qt/NightStalker/resource.qss
Make sure to paint unit action icons in white, since the background is black.
Reported by Mu [on Discord](https://discord.com/channels/378908274113904641/912500712833974322/1043590889827745832):
=> Fix black-on-black unit actions for Classic

.github/workflows/build.yaml
4.4.0 started failing today for clang-format-11. Since 4.5.0, the action supports use even older versions so 11 should be fine.
Closes #1503.
=> Bump jidicula/clang-format-action to 4.9.0

client/messagewin_common.cpp, client/update_queue.cpp, client/update_queue.h
Reverts commits touching `update_queue.{h,cpp}` as needed to undo the culprit for #1485.
Closes #1485.
=> Fix opening load saved game or start scenario game on start menu

client/citydlg.cpp, client/citydlg_common.cpp
Sort and categorize the table showing the detailed output of cities. The four main categories are Food, Production, and Trade, in the order they are shown on the map. Further details are shown under each category:
- Under Food: everything related to growth
- Under Production: only waste (the difference between waste and corruption is hard to learn, maybe this will help...)
- Under Trade: corruption and the three outputs taxed from it, in the order they are shown in the national budget.
This is only a first pass: in the future we'll want to add icons, make this more colorful, and get rid of the monospace font.
Closes #1491.
=> Sort rows in the city dialog detailed output

client/options.cpp
The options dialog used not to be refreshed because of a logic error in handle_server_setting_bitwise(), which caused the old values to remain displayed and other fancy behavior. Make sure to always call option_gui_update(), even if it would maybe be redundant -- better waste a few CPU cycles than display wrong information.
Closes #1122.
=> Always update enum and bitwise options when the server sends them

client/mapctrl.cpp, client/mapview.cpp, client/mapview.h
...and not only when releasing the middle mouse button.
Closes #1120.
=> Close the tile info popup when another button is pressed

client/client_main.cpp, client/fonts.cpp, client/fonts.h, client/gui_main.cpp, client/optiondlg.cpp, client/optiondlg.h, client/options.cpp, client/options.h, client/qtg_cxxside.h
Support both the Linux Libertine and Libertinus font families. Give priority to the latter because the Libertine project is dead.
Closes #1428.
=> Support Libertinus as a Libertine alternative

data/themes/gui-qt/Classic/theme.conf, data/themes/gui-qt/NightStalker/theme.conf
Contrast was too low for some of the colors used by the server. Use the color replacement feature to make them stand out on the black background.
Closes #1510.
=> Improve contrast in the chat

server/sernet.cpp
The closing reason would otherwise persist from the previous client disconnecting and would appear when listing connected clients via the `/list connections` command.
Part of #1517
=> Clear closing reason for connection object when a client connects

client/citydlg.cpp
super small change, noticed it while testing other things today.
=> Add a colon to present units to match formatting

.github/workflows/build.yaml, .github/workflows/clang-tidy.yaml
I think the action from the fork cancels the one from the main repo (if actions are enabled in the fork, as is the case with mine).
=> Try to fix Github Actions not running in repo

client/fonts.cpp
"Libertinus Display" was used instead of the correct font name.
Closes #1548.
=> Fix Libertinus Serif Display font name

data/themes/gui-qt/Classic/resource.qss
Text on disabled buttons (such as Turn Done during turn processing) had the same color as text on active buttons (black). Gray it out when the button is disabled.
Part of #1517.
A couple enabled and disabled buttons:
=> Classic: Improve contrast between active and disabled buttons

client/page_game.cpp
The shortcuts for top bar buttons use the F1-F6 keys. Visually order the widget to make the shortcuts more consistent with the on-screen layout.
=> Order top bar buttons consistently with F-keys

client/citydlg.cpp, client/citydlg.h
An animation only makes sense if the bar is dynamic and progress is expected without user interaction. There is no reason whatsoever to animate progress bars that will only update during TC.
=> Remove the animation from prod and research progress bars

server/generator/mapgen_utils.cpp
A bug was introduced when porting away from realloc(): the vectors holding the sizes were reset instead of merely resized. This had the direct effect of generating large lakes (#1537) and affected player placement in a strange way (#1535).
Closes #1535.
Closes #1537.
=> Fix computing continent sizes in map generator

client/shortcuts.cpp
The last shortcut, SC_PILLAGE, was never added back to the map of shortcuts after clearing it for a reset, causing a crash when selecting any pillage-capable unit.
=> Fix a client crash after reseting options

client/chatline.cpp
=> Update tool tip on allies/private button on chat

server/connecthand.cpp, server/plrhand.cpp
* Disallow Turn Done at the server side in fixedlength mode.
* Don't spam the console with "waiting for X to finish turn" nonsense if fixedlength
* Ensure "moving"/"blocking" information in the player list is accurate after a player has disconnected
=> Improvements for fixedlength games

client/citydlg.cpp, client/citydlg_common.cpp, client/citydlg_common.h
Merge into the "Citizens" line since this happiness is eventually related to them.
Closes #1581.
=> Add the city status (content/happy/...) to the city dialog

client/sciencedlg.cpp, client/text.cpp, client/text.h
Requested by horror-vacui on Discord.
See #1517.
=> Add detailed info about tech progress to top bar

client/turn_done_button.cpp
It's more consistent this way, always changing between absolute and relative times exactly at TC-1 and not randomly at midnight.
Requested by Mu on Discord.
=> Timeout display: always use absolute time until TC-1h

client/page_load.cpp, client/page_load.ui, data/themes/gui-qt/Classic/resource.qss
Ensure that "Browse..." always has a different role than Ok, otherwise Qt does fancy things.
Closes #1582.
=> Fix random button ordering in PAGE_LOAD

client/control.cpp, client/control.h, client/mapctrl.cpp, client/mapview.cpp, client/mapview.h
The "auto center on unit" option was being changed without user interaction because of badly engineered code that was temporarily changing its value and failing to restore it. Make the code safer by introducing a new, purely internal, flag to pause the auto centering so we don't need to touch the user-visible setting.
Closes #1316.
=> Prevent the autocenter option from autochanging

.github/workflows/build.yaml
Remove python3 from macOS CI since its included in the image and is causing a conflict.
=> Remove python3 from macOS CI

client/citydlg.ui
The layout of the city dialog was getting bad on 1366x768 screens because there was not enough vertical space. Add scroll bars as a minimal change for 3.0.
Closes #1584.
Need to compile twice since this changes the .ui
=> Add scroll bars to the city screen when info doesn't fit

client/cityrep.cpp, client/diplodlg.cpp, client/economyreport.cpp, client/hudwidget.cpp, client/menu.cpp, client/plrdlg.cpp, client/top_bar.cpp
Otherwise we may get the minimap and messages overlapping with the city screen widgets. Closing the city screen is maybe not the best solution, but it does work around the inconsistency.
Closes #1606.
=> Close the city screen when closing reports

client/diplodlg.cpp, client/page_game.cpp, client/plrdlg.cpp, client/plrdlg.h
Similar to how the Research view button will blink on the top bar when no research target is set. We enable the same visual feature to remind a player that there are open meetings to attend to.
Closes #1421
=> Diplomacy Visibility

utility/inputfile.cpp
It's more reliable than manual new line parsing, especially with Windows-style CRLF come into play.
Closes #1087.
**Test:**
* Convert `helpdata.txt` to DOS format
* Start the client
* Open Help > About Freeciv21
* Reproduce 1087 without the patch and not with the patch
=> Use QTextStream to read input files

client/client_main.cpp, client/options.cpp
The list of available options wasn't initialized properly before loading.
**Test plan:**
Set Classic theme, check that it's picked up after restart. Check other options that use a combo box.
=> Fix loading audio plugin and theme options

client/cityrep.cpp, client/cityrepdata.cpp, client/cityrepdata.h
In the city dialog, we had `Celebrating/Happy/Peace/Disorder`. The city list was missing `Happy`. Add it.
This is big because I mass-changed `const char *` to `QString` to allow code sharing between the city dialog and city list (which makes more sense than two separate functions). It's also safer.
The first commit contains the boilerplate, the second commit has the functional changes.
Closes #1616.
=> Fix inconsistent display of city happiness

common/government.cpp
The server was crashing when a ruleset was failing to load before governments were initialized. This prevents the crash.
**Test plan:**
Read the code. Trust me initializing a field in the constructor prevents a crash (it's good practice anyway).
=> Fix crash when failing to load a ruleset

server/rssanity.cpp
When emitting warnings about action enablers, include the action name in the message (unfortunately, we currently don't store the enabler section name). This gives some context to messages that would previously look like:
This action enabler is never used by any unit.
**Test plan:**
Load the latest LTX (from [LTT-LTX](https://github.com/longturn/LTT-LTX)) with and without this change.
=> Specify which action a sanity warning is emitted for

client/cityrep.cpp
Modifying a city can (somehow) change the selection, upon which selected_cities is modified. Modifying a QList invalidates iterators, thus we were triggering undefined behavior when doing this in loops. Copy the list before doing anything with it, which avoids any invalidation (since we work on the copy).
Also remove a duplicated `nullptr` check (items in the list shouldn't be `nullptr` anyway).
**Test plan:**
* Select all cities
* Switch to a governor that works for some cities but not all
* Observe crash without patch (YMMV), no crash with patch
=> Fix a class of crashes in the city list

common/research.cpp, common/research.h, server/sanitycheck.cpp, server/savegame/savegame2.cpp, server/savegame/savegame3.cpp, server/srv_main.cpp, server/techtools.cpp
The number of valid research objects is the number of teams when team_pooled_research is enabled, and the number of players when it is disabled. The code was always assuming the first case, which created bugs in team games without pooled research.
Fixes 22c0c4b47ed3ed239358933af15818c7b4873c49.
Observed in the LT76Team test game.
**Test plan:**
* Check that research is working normally in single player
* Check that research is working normally in a team game with shared research (`/set team_pooled_r en`)
* Check that research is working normally in LT76Team (which will have this patch in a few minutes)
=> Take team_pooled_research into account when looping over research

.github/workflows/build.yaml
We require build CI to complete as it is our repo protection mechanism. We had paths-ignore to not run full CI on documentation only updates (docs/**), however that doesn't really work. You have to go through a collection of hoops to actually get it to satisfy the check. Removing as that is easier and keeps our protection mechanism in place.
=> Remove paths-ignore

client/options.cpp
Users were confused that they weren't shown.
Closes #1627.
=> Enable combat messages by default

client/fc_client.cpp, client/fc_client.h, client/page_game.cpp
It's nicer not to reopen them by hand every time we connect.
There may be rough edges when disconnecting and reconnecting.
Closes #1488.
=> Remember whether the chat and messages are visible

client/packhand.cpp
=> Don't advance unit focus when the city dialog is shown

client/citydlg.cpp
* "Set homecity" was hidden when right clicking without a selection and never shown again afterwards
* Initially, clicking anywhere on the widget (except on units) would show the full menu with all options enabled (but none working)
This patch fixes the above and changes the menu so items are enabled or disabled depending on available options, instead of hiding unavailable ones. This enables better visual memory of the items location.
Closes #1615.
=> Fix bugs with the units actions menu in the city dialog

client/minimap_panel.cpp, client/minimap_panel.h, client/minimap_panel.ui, data/themes/gui-qt/icons/settings-minimap.svg, data/themes/gui-qt/icons/settings-minimap.svg.license
Make the minimap options more visible and easier to change by adding them in a dropdown menu next to the minimap.
=> Add a menu with minimap options next to the minimap

CMakeLists.txt, client/client_main.cpp, client/clinet.cpp, client/options.cpp, client/packhand.cpp, client/page_main.cpp, client/page_scenario.cpp, client/servers.cpp, common/CMakeLists.txt, common/capstr.cpp, server/civserver.cpp, server/connecthand.cpp, server/meta.cpp, server/report.cpp, server/savegame/savegame3.cpp, server/sernet.cpp, server/stdinhand.cpp, tools/civmanual.cpp, tools/fcmp/mpcli.cpp, tools/fcmp/mpgui_qt.cpp, tools/ruledit/ruledit.cpp, tools/ruledit/ruledit_qt.cpp, tools/ruleup.cpp, translations/core/POTFILES.in, utility/CMakeLists.txt, utility/cmake_fc_config.h.in, utility/netfile.cpp, utility/version.cpp, utility/version.h
For devs who do not clean their cache directory often, we do a check for the generated `fc_version.h` and if the patch version is different then we delete the cache file. Closes #1564
=> Check cache fc_version.h at configure time

client/cityrepdata.cpp
There are seven clusters: City, Workers, Units, Resources, Economy, Culture, and Production
Also took the chance to bring some stray columns together with their relatives (e.g. plague, trade routes)
=> Reorganize city tab columns into clusters

ai/default/daieffects.cpp, common/effects.cpp, common/effects.h, docs/Contributing/style-guide.rst, docs/Modding/Rulesets/effects.rst, server/cityturn.cpp, server/plrhand.cpp
Tested by adding the following to `classic/effects.ruleset`:
```ini
[effect_foo]
type    = "Growth_Surplus_Pct"
value   = 100
```
Closes #510.
=> Add an effect to keep food surplus when a city grows

client/helpdlg.cpp
Fixes #1644.
If I understand correctly, `static_cast<whatever>` is preferred over `(whatever)`, please do correct me if I'm wrong about that.
=> Show unit vision in help dialog for units

client/hudwidget.cpp, client/menu.cpp, client/menu.h, client/shortcuts.cpp, client/shortcuts.h
Well, they could always be exploded with Do..., but it's easier now. Two commits:
1. Fix the duplicate shortcuts message with Go to and... shortcuts (Shift+B, Shift+J, Shift+N). Backporting candidate.
2. Fix the Shift+N button. This one is more risky, not sure if we should backport.
Closes #1650
=> Fix exploding nukes

client/CMakeLists.txt, client/citydlg.cpp, client/citydlg.h, client/citydlg.ui, client/tilespec.cpp, client/tilespec.h, client/utils/improvement_seller.cpp, client/utils/improvement_seller.h, client/utils/unit_quick_menu.cpp, client/utils/unit_quick_menu.h, client/widgets/city/upkeep_widget.cpp, client/widgets/city/upkeep_widget.h, common/improvement.cpp, common/improvement.h
This PR introduces a unified widget to show everything supported by a city: improvements and units. It adopts a purely vertical layout that should be easy to scroll. All items respond to double click and right click. Eventually this widget would be added to a side of the city screen with as much height as possible. I want to add the widget to master early to gather feedback, so this PR adds it to the left of the 3.0 city screen layout.
Some infrastructure work for better tileset changing support is also done in this PR. I also started using a more structured folder layout with #1097 in mind.
=> Start breaking the city dialog

client/CMakeLists.txt, client/citydlg.cpp, client/citydlg.ui, client/layer.cpp, client/layer.h, client/tileset/drawn_sprite.cpp, client/tileset/drawn_sprite.h, client/tilespec.cpp, client/tilespec.h, client/widgets/city/city_icon_widget.cpp, client/widgets/city/city_icon_widget.h
No interaction, this is purely decoration. The PR is a bit big (for the functionality) because I had to extract the sprites from the tileset code (getting the walls correct would be surprisingly hard otherwise). I also modified the city dialog layout.
In the same spirit as #1695, the layout is preliminary so we can test the widget IRL.
See #1591.
=> Add a city icon to the city dialog

client/minimap_panel.h
Coverity warned about it not being initialized, it's in fact never used.
Closes #1701.
=> Remove unused variable

client/page_network.cpp, server/connecthand.h
The server stores a password in memory. If set, this password is sent to the server automatically when requested. This is true for *any* server, so setting the password, connecting to the correct server, disconnecting and going to another server would send the same password.
Prevent this by wiping the password when the user attempts to connect.
Looking at this code in the context of #785, but this is unlikely to fix it.
=> Reset the internal password when the user connects

client/text.cpp, common/actions.cpp, common/actions.h
This uses the target_reqs for action "Bribe Unit", so unit stacks are always listed as unbribeable.
Closes #1677.
=> Mention when units are unbribeable

server/techtools.cpp
Closes #1682.
Backporting candidate.
=> Fix sending current research to team mates

client/fc_client.cpp
Setting the connection state resets, among others, the password field. The metaserver scan runs synchronously with its own nested event loop.
If a user was fast enough to start connecting before the scan was finished, the password field would be reset when the scan finished.
Closes #785.
This is the patch proposed by @daavko.
=> Set the connection state before starting the metaserver scan

client/layer_terrain.cpp, client/tilespec.cpp, docs/Modding/Tilesets/terrain.rst
Three small changes in one PR:
* More logging when loading broken tilesets
* Crash fix with `hex_corner` (stupid control flow). AFAIK `hex_corner` is only used in `project-vectron`
* Doc fix for `hex_corner`
Would like to backport.
=> Small hex tileset improvements

docs/Modding/Tilesets/terrain.rst
The hex_corner sprite type doesn't work with `MATCH_SAME` or `MATCH_PAIR` (that is, with a single group in `layerN_match_with`). Don't imply that it works in the documentation.
=> Don't document not working hex_corner w/ single matching

client/layer_terrain.cpp, docs/Modding/Tilesets/terrain.rst
I need this for a hexagonal tileset project I'm doing on the side. Vectron might also benefit from this feature.
The patch touches the drawing of most terrain, all bundled tilesets seemed to work but always good to check.
=> Implement hex_corner with MATCH_SAME

client/mapview_common.cpp
#1669 turned out to be caused by a bug in the rendering code. The first commit fixes it, the second commit is a small refactor.
First commit might be backported.
Closes #1669.
=> Don't let middle click erase tile labels

client/menu.cpp
The calculated image size was never exactly matched by a renderer update, resulting in the image never being saved. The stall temporary renderer was then blocking map updates. Only require the renderer update to be larger than the calculated size, which will always happen since we trigger a full update.
In addition, remove wrong size heuristics for iso-hex tilesets: they behave just like normal isometric tilesets.
Closes #1642.
Backport candidate since this ended up being a relatively easy fix.
=> Fix saving hexagonal maps to image

cmake/FreecivInstall.cmake, vcpkg.json
This change will fix the CI. We need upstream MSYS2 team to fix `QSslSocket` so the modpack installer will work.
I will want to push some more commits for vcpkg here too as its related.
=> Use SSL v3 libraries for MSYS2

data/themes/gui-qt/Classic/resource.qss, data/themes/gui-qt/NightStalker/resource.qss
Affected widgets:
* Demographics
* UWT table (under F2)
* Middle click popup
* Unit combat report
* Unit actions HUD
`info_tab` doesn't exist so I removed it from the styles.
Closes #1739.
=> Remove transparency from a few widgets

client/include/ratesdlg_g.h, client/menu.cpp, client/page_game.cpp, client/page_game.h, client/ratesdlg.cpp, client/ratesdlg.h, client/top_bar.cpp, client/top_bar.h
Implementing this was somewhat complicated by existing code (throwing one-shot dialogs without a refresh ability). I did some refactoring to get rid of that.
Main behaviour changes:
* The dialog is now shown right under the taxes display instead of under the mouse.
* Some checks done to avoid the dialog going off screen should work better on multi-screen systems.
* The dialog is unique.
Closes #1602.
Will not be backported due to the patch complexity.
=> Make the national budget dialog unique

client/citydlg_common.cpp
Closes #1720.
Backport highly recommended (previous implementation was undefined behavior).
=> Fix displaying the total output in city dialog tooltips

client/client_main.cpp
When invoking the client by clicking on a fc21 link, the expected behaviour is that it tries and joins the linked-to game. This is only possible if passing a URL implies -a.
Suggest backporting this to `stable`.
Closes #1743.
=> Make passing a fc21:// URL to the client trigger autoconnect

client/chatline.cpp, client/chatline.h
This caused performance issues when connecting. Instead, update the list whenever the chat input gets focus (so never if it's never used).
Used the opportunity to add relevant strings for translation and use `QStringLiteral()` on the others. Also removed O(N^2) duplicate-checking code when adding players to the list.
This fixes the "crocodiles" issue when connecting to long-running games. Backport recommended.
=> Don't update the chat completion list with every new message

server/server.cpp
It was doing the exact opposite of the intended behavior, allowing an infinite number of connections from the same host but disallowing any new connection once N players were connected.
Closes #1754.
Also upgrade the rejection message to a warning so it appears in the server logs.
=> Fix maxconnectionsperhost

common/helpdata.cpp, data/helpdata.txt
The table was showing wrong information since Cultivate was split from Irrigate and Plant was split from Mine. Fix it by displaying only terrain change actions, and simplify the implementation. Irrigate and Mine are no longer included in the summary (adding more columns would take too much space and the overall organization should be improved if another table was to be added).
Closes #1686.
=> Fix the terrain alterations table

docs/Contributing/visual-studio.rst, docs/Modding/Tilesets/terrain.rst
No related issue, just cleaning up some headings to make them unique and stop issuing warnings at generation time.
=> Docs: Fix some cross-reference warnings

client/goto.cpp, common/path_finder.cpp
Closes #1783.
Backporting highly recommended.
=> Fix goto for units without MP

client/packhand.cpp, client/text.cpp
Closes #1782.
Backport recommended since otherwise the unit name feature is kind of moot.
=> Display foreign unit names

server/savegame/savegame3.cpp
Fixes the weird issue with resources [seen in LT76Team](https://discord.com/channels/378908274113904641/912500712833974322/1069019470573613147).
Testing: load a saved game and check that fogged resources are shown correctly in the middle click popup.
=> Set resources on player map (FoW map) when loading saved game

client/citydlg.cpp
The refresh had been introduced to highlight the correct tiles when switching city from the city dialog. Detect such changes and refresh the relevant working areas only.
This improves performance of city management dramatically when using small tilesets or large windows.
Reported by Corbeau [on Discord](https://discord.com/channels/378908274113904641/912500712833974322/1068120449822765076).
Testing:
* Use a small tileset like Trident (more tiles to refresh)
* Make sure most of the map is explored and visible
* Try to manage citizens in a city
* Notice the reduced latency with the patch
Suggest to backport.
=> Don't refresh the whole map with every change to a city

client/citydlg.cpp
Use the generic setup_ui function instead of duplicating its code in get_city.
See #1788.
=> Fix highlighting the new city when switching with prev/next

.github/workflows/build.yaml
The 5.15.2 branch was removed recently.
Let's see what happens to the CI.
=> Update WASM Qt to 5.15.8

client/dialogs.cpp, client/hudwidget.cpp, client/views/view_economics.cpp
Turned out that calling show() twice moves the widget around. Don't call it from set_text_title() and always call it externally instead.
Closes #1422.
Backporting not envisioned because if I missed a `show()`, that dialog wouldn't show up at all.
=> Fix hud_message_box sometimes showing at the top left of the screen

.github/workflows/build.yaml
It has shown long-lasting breakage and takes forever. Save on computing resources and reduce spurious failures.
Closes #1437.
=> CI: Run Windows clang only once a week

client/citydlg.cpp, client/hudwidget.cpp, client/views/view_map_common.cpp, client/views/view_map_common.h
The fog effect from the city screen is gone, will do it properly if we want to add it back.
Closes #1106.
=> Remove ColorDodge in the city screen and other places

client/optiondlg.cpp
This way it doesn't block input, but should also always stay on top of the main window.
Closes #1035.
Will need a Mac tester to confirm that it's actually working as intended.
=> Change the options dialog to be a tool window

client/CMakeLists.txt, client/page_game.cpp, client/repodlgs_common.cpp, client/repodlgs_common.h, client/top_bar.cpp, client/top_bar.h, client/views/view_units.cpp, client/views/view_units.h, client/views/view_units.ui
Implement a new page view for units. See #1498
ToDo:
To get to the view as it stands in this draft, you right-click on the top bar. Left click opens the old widget.
Sample:
=> New Units View

client/views/view_units.cpp, client/views/view_units.h, client/views/view_units.ui
=> Units View #2

.gitattributes
Suggest to include in `stable`.
=> Don't include CI files in release tarballs

.github/workflows/release.yaml, docs/Contributing/release.rst, docs/Contributing/stable-branch.rst
We released 3.0-rc.3 with code from master. This should not happen.
Also update the CI so it can push new version numbers to `stable` when we make RC releases and document when `stable` gets created (as a first draft to be revisited when we reach 3.1 and make a new `stable` branch).
The branch part was tested in https://github.com/lmoureaux/freeciv21/pull/4.
Backporting recommended.
=> Don't hard code master for autorevision and source tarballs

common/scriptcore/tolua_game.pkg
No related issue. Access through `tile.continent`.
=> Add the continent number to lua

client/tileset/tilespec.cpp
Closes #319
I havent added the sprite in any of the default tilesets, but it can be tested with. https://github.com/lmoureaux/RoundSquare/pull/2
=> Show celebration spires for cities

client/CMakeLists.txt, client/attribute.h, client/citydlg.cpp, client/citydlg.h, client/citydlg.ui, client/governor.cpp, client/governor.h, client/options.cpp, client/widgets/city/governor_widget.cpp, client/widgets/city/governor_widget.h, client/widgets/city/governor_widget.ui, common/aicore/cm.cpp
As part of the general city dialog rework in https://github.com/longturn/freeciv21/issues/1591, move the widget used to set
governor parameters to its own file. Implement the layout in a .ui file for
easier edits and rework it:
* Add labels with slider values.
* Set slider pageSteps to 1 for more precise edits.
* Expose max_growth, allow_specialists, and allow_disorder.
* Add accelerator shortcuts.
* Improve typography, in particular removing usage of the notify_label font.
The widget is designed to be used horizontally in the future and thus doesn't
fit very well in the current column-based layout.
=> Move governor settings widget to its own class with a .ui

docs/Contributing/style-guide.rst
Keep the topic short because math should be used sparingly. In particular, a full Latex reference is out of scope here; Latex is widespread enough that there are countless resources on the topic. The syntax is also way to complex to explain in a single page.
Closes #1719.
=> Add guidelines for math usage in the documenation

.github/workflows/release.yaml
=> Remove spurious `git diff` in the release scripts

utility/cmake_fc_config.h.in
We don't intend to break file formats as often as Freeciv used to, and when we do we'll indicate this with a new major version.
Closes #1853.
=> Don't include the minor version in the data path

docs/Coding/ai.rst, docs/Coding/architecture.rst, docs/Coding/attributes.rst, docs/Coding/fcdb.rst, docs/Coding/hacking.rst, docs/Coding/internationalization.rst, docs/Coding/logging.rst, docs/Coding/network-protocol.rst, docs/Coding/scorelog.rst
Part of #1250
Updating to match style guide
* Standard SPDX attribution header
* Proper capitalization rules
* Image `:numref:` usage
* Cross document `:ref:` usage
* Consonant usage
* Glossary usage
=> Docs/Coding Style Guide Update

docs/Contributing/bugs.rst, docs/Contributing/capitalized-terms.rst, docs/Contributing/dev-env.rst, docs/Contributing/eval-pull-request.rst, docs/Contributing/msys2.rst, docs/Contributing/pull-request.rst, docs/Contributing/release.rst, docs/Contributing/style-guide.rst, docs/Contributing/visual-studio.rst
Closes #809
Part of #1250 
Updating to match style guide
* Standard SPDX attribution header
* Proper capitalization rules
* Image `:numref:` usage
* Cross document `:ref:` usage
* Consonant usage
* Glossary usage
=> Docs/contrib update to Style Guide

server/unithand.cpp
The old transporter needs to be updated when a transported unit switches to another transport, otherwise its "loaded" status may be wrong on the client side.
Closes #1883.
=> Fix updating the old transport when switching ships

client/menu.cpp
=> Fix pillaging shortcuts (Shift+P, unit control bar)

server/civserver.cpp
freeciv-server help text has a typo for -s, --save flag, "Sage games to directory DIR". Pull request changes "Sage" to "Save"
=> Minor typo fix

.gitignore
Update `.gitignore` to be ready for flatpak support down the road.
=> add .flatpak-builder to .gitignore

client/hudwidget.cpp, client/unitselect.cpp, common/unit.cpp, common/unittype.cpp
It is tracked as turns internally and helps shows it as turns, it is highly misleading and confusing to show it as movement points instead.
=> Always display fuel in turns.

cmake/FreecivInstall.cmake, dist/flatpak.yaml
Add support for Flatpak to master branch. Note that it doesn't work right now as the platform file needs to have cmake 3.21 (has 3.20 now).
=> Flatpak master

docs/Coding/fcdb.rst, lua/database.lua
Leaves original `.cpp` finding code alone for backwards compat w/ LT.net server. Documents use of the `lua/database.lua` file, but does not attempt to ship the file in a package.
Closes #1908
=> Document the use of database.lua

client/tileset/tilespec.cpp
Makes it easier to spot where they're coming from.
See #1931.
=> Add the tileset name to the "duplicate sprites" message

.github/workflows/build.yaml, docs/Getting/compile.rst
fter the debacle of 3.0 (https://github.com/longturn/freeciv21/issues/1895), I feel like it's a good idea to systematically check more environments. This introduces a check for the stable version of Fedora.
=> Add a Fedora CI and review the dependency list

client/tileset/tilespec.cpp
We were looking for "upkeep.unhappy1", which is actually "upkeep.unhappy" for
historical reasons. So start by looking for "upkeep.unhappy2". Do the same for
other upkeep sprites.
Closes #1859.
=> Fix loading unhappy sprites when there is more than one

client/chatline.cpp, common/featured_text.cpp, common/featured_text.h
The previous code was doing some dark magic to obtain an ok-looking result, but the generated HTML closing tags weren't in the correct order. In addition, it was neglecting any leftover out of any tags. This was working fine because most message content is enclosed within a color tag, but hid the timestamps that are not located inside a tag.
Simplify the implementation by merging the HTML tags together (in the correct order!) as they are generated. This way applying them becomes a simple string insertion task.
Also use the opportunity to refactor some related code slightly. We should eventually write a simple direct featured-text-to-HTML converter instead of using the intermediate "tags" step (whose architecture is a copy of Gtk's rich text functions and doesn't play well with Qt's). …
=> Fix displaying message turn and timestamp

client/client_main.cpp
Loading options resets them to their defaults, so we can only override them after they are loaded. This has the side-effect of using a default username if the user sets it to something invalid (which is good because Freeciv21 is unusable without a username).
Closes #1898.
=> Guess the default username only after loading options

client/gui_main.cpp
Options are configured in client_main, no need to repeat this in ui_main. load_fonts is also called as needed from configure_fonts, so no need to call it from ui_main either.
Found while investigating #1899.
=> Don't configure options twice

data/themes/gui-qt/NightStalker/resource.qss
When the turn and time are displayed next to messages, they use the default color. The saturated green we had earlier was clashing with message colors, in particular the ones in red. Switch to a slightly softened white to avoid this.
See commit f6d7d609b9a8c2a2445eac09b9f93e842da0644b.
=> NightStalker: make default chat color more neutral

client/client_main.cpp
The client wouldn't start because the "--debug" option had been renamed to "--debug." in one place but not everywhere. Revert the change.
=> Fix starting the client

client/clinet.cpp
This is one of the failure modes of bad connections. Fail to connect after 30s (Qt default). Related to #450.
To test, try to connect to an unused game port on LT.net.
=> Don't wait forever when trying to connect

client/helpdlg.cpp
* When restoring, cap the size to the screen's available area
* When showing for the first time, use the current screen instead of the first one
To backport or not to backport?
=> Ensure that the help dialog doesn't get bigger than the screen it is on

server/diplomats.cpp
This makes inciting way too powerful, allowing "tech trading" in games where it ought to be disabled.
Closes #1944.
=> Don't give a free tech when inciting a city

client/packhand.cpp, common/city.cpp, common/city.h, common/networking/packets.def, server/cityhand.cpp, server/citytools.cpp, server/cityturn.cpp, server/savegame/savegame3.cpp, utility/fc_version.h.in
When a player buys a unit that cannot be built then switches to building something else, penalize half of the shields that were bought. This changes the previous overjealous behaviour where half the total amount of shields would be lost.
Closes #1915.
* Playing normally works as expected.
* Added the `Unique` flag to warriors in `classic` and started a game. Bought a couple Warriors before I had any, then changed production to Settlers. Half of the shields I had bought disappeared as expected.
=> Fix penalizing buy-then-change-production

dist/net.longturn.freeciv21.client.metainfo.xml
No related issue. Will make future flatpak updates easier.
=> Add <releases> tag to client metainfo.xml file

client/fc_client.h
timeout  value changed from 2000 to 8000
=> timeout value changed

client/text.cpp, client/text.h, client/views/view_research.cpp
Improve the following texts in the research view header following [a comment by Blauwal on Discord](https://discord.com/channels/378908274113904641/1106327029223272518/1132109288521867346):
* The bulb production details (top left): add a missing newline when tech upkeep is enabled
* The current status (top right in the progress bar): make it work better when tech leak and tech upkeep are used together
* The number of bulbs/turns required to reach the current goal (bottom right): make it less confusing by taking the real cost of the current tech into account
Some small code improvements here and there as well.
I think the risks of backporting this outweigh the benefits.
=> Improve texts in the research view

cmake/FreecivInstall.cmake
Found a regression from #2004. Fixing here. No related issue.
=> Ensure icon png available for win32

data/themes/gui-qt/Classic/resource.qss, data/themes/gui-qt/Classic/theme.conf
Use a yellowish color instead of gray. This works better with other widgets.
Closes #1981.
No backport needed, I don't think the issue is present in 3.0.
=> Change the default background color for Classic

client/dialogs.cpp, client/dialogs.h
Picking a gender was not working because the radio buttons weren't synchronized with the internal variable holding the information. Discard the internal variable and use the buttons as the source of truth. Always make sure that one of the buttons is selected. Pick one randomly on startup, as choosing one would be offensive towards half of humankind.
Reported by Hawk on Discord.
=> Fix picking a gender and init randomly

client/control.cpp
Suggested on Discord. This will draw units stationed in cities when drawing cities is disabled in the settings.
=> Make units on cities visible when city drawing is disabled

docs/requirements.txt
This is a short-term solution for #2023. In the long run, upstream issues should be fixed:
* https://github.com/sphinx-doc/sphinx/issues/11643
* https://github.com/mgeier/sphinx-last-updated-by-git/pull/57
Closes #2023.
=> Docs: pin sphinx to <7.2

common/map.cpp, common/path.h, common/path_finder.cpp, server/unithand.cpp, server/unittools.cpp
Say we have two transports A and B next to the coast C, with a land
unit in A. Consider the following orders for the land unit:
1. Unload from A to B->tile
2. Move from B->tile to C
This sequence should not succeed because the unit should still be loaded
after the first step. However, in practice the unit was not loaded after
step 1, resulting in an invalid state that confused ORDER_MOVED. Do the
same when bumping units after a transport is killed.
The fix to that is obviously to load the unit after step 1. There is a
catch though: this is (and has always been) done without considering
action enablers. It might be possible to exploit this to bypass loading
rules.
Path finding support is also included in this PR.
=> Fix disembarking without losing MP through adjacent transport

client/options.cpp, client/options.h, client/tileset/tilespec.cpp
And actually never overwrite tileset options when loading a tileset. Updating the tileset options should only be done when the user explicitly changes them.
=> Don't overwrite the "square" tileset option on startup

data/helpdata.txt
Fixes a typo in the help for the controls
=> Fix typo: vity => city

server/unittools.cpp
When a unit affected by unit wait time was bounced, the generated move order was rejected by the move handling code. As a consequence, the unit ended up being disbanded.
This affected units doing terraforming work (e.g. turning land to ocean). This forced players to issue the terraforming orders at least UWT seconds before TC, which forced them to connect at specific times of the day. Since one of the goals of UWT is exactly to avoid this constraint around TC, adding a similar constraint around TC - UWT is the opposite of good.
=> Stop disbanding units under UWT when bouncing them

client/tileset/tilespec.cpp
Create a dummy "error" pixmap when the sprites are missing.
Testing: comment out the file with wonder sprites in your favorite tileset. Repeat with the file with tech sprites.
Backport candidate
Related to #1750
=> Fix crashes on missing building or tech sprites

client/control.cpp, client/packhand.cpp, common/city.h
The client was already remembering information about investigated cities, but there was no way of seeing it once out of the city screen. Allow reopening the city screen by clicking on the city.
Closes #2059.
Could be backported even though it's technically a new feature, it was so simple...
=> Allow reopening investigated cities

common/vision.cpp, common/vision.h, server/citytools.cpp, server/diplomats.cpp, server/maphand.cpp, server/maphand.h, server/savegame/savegame2.cpp, server/savegame/savegame3.cpp, server/srv_main.cpp, server/unittools.cpp
Sharing maps between players was fundamentally broken. The server records the last turn in which a player saw a tile. This information is only updated when the player stops seeing a tile, and not when it just keeps seeing it because the tile is within its vision range.
The following map sharing bugs existed:
* Tiles seen by the giving player were not sent if the receiving player had last viewed them after the giving player;
* Cities were only updated when destroyed. Renamed or growing cities were not updated.
This commit fixes both bugs. The core logic in `really_give_tile_info_from_player_to_player` was completely overhauled to make it easier to follow and more correct. In addition, `player_tile.site` was turned to a `unique_ptr` to facilitate bookkeeping.
Closes #2045
Testing: Before …
=> Fix map sharing

client/CMakeLists.txt, client/ratesdlg.cpp, client/ratesdlg.h, client/widgets/multi_slider.cpp, client/widgets/multi_slider.h
I would like to have a generic version of fc_double_edge (the widget to choose tax rates) available. The general idea is that there is a fixed number of items and the user can distribute them across multiple categories. This could be useful for specialists in big cities. In order to level up the field a bit, I intend to make the new widget usable with the keyboard only.
This PR implements the generic widget and uses it in the tax rates dialog. Both keyboard and mouse navigation should work properly. The widget was developed with NightStalker and I quickly checked that it's not doing anything crazy under Classic.
If/when this gets merged, documentation screenshots will need an update.
=> Introduce a multi slider widget and use it to choose tax rates

server/stdinhand.cpp
There was a warning that a variable may have been used initialized. This was likely not the case, but since the implementation was convoluted I used the opportunity to simplify it.
Closes #2064.
=> Simplify the implementation of /kick

client/tileset/layer_terrain.cpp
Silences a warning.
Closes #2063.
=> Always initialize indices in fill_terrain_sprite_array

client/views/view_nations.cpp
The diplomatic status between two nations the current player has no contact with is usually not known by the client. The server sends "war" in this case (it should arguably not send anything at all). It also sets the NI_DIPLOMACY bit in client.visible to false to tell the client that this information is not available. However, the client ignores this and just displays "war".
Make the client ignore diplomatic relations between two players when the NI_DIPLOMACY bit is false for both players -- that is, when no information is available. This prevents the client from displaying invalid data.
Discovered during LeagueB2.
Backport candidate (I confirmed that `stable` already has the `NationalIntelligence` feature that this patch requires)
=> Don't display unknown diplomatic relations as war

.github/workflows/build.yaml, client/CMakeLists.txt, cmake/FindSphinx.cmake, cmake/FreecivDependencies.cmake, common/CMakeLists.txt, server/CMakeLists.txt, utility/CMakeLists.txt
FindPythonInterp is deprectaed. FindPython3 is a drop-in replacement.
=> Update CMake files to use FindPython3

common/unittype.cpp
Closes #769.
Will want @Corbeau-1 to test the `.exe` once the Windows build is ready.
=> Allow using the unit type for Shield2Gold_Factor

docs/Contributing/release.rst
to include managing updates to vcpkgGitCommitId in CI.
Also fix a small typo to the new Workarounds page.
=> Update release process 

client/ratesdlg.cpp
Closes #2072.
Coverity CID 1528901.
This affects the national budget dialog when there is no player (global observer). I haven't been able to fire it up in this case, but better safe than sorry.
=> Fix dereference after null check in ratesdlg.cpp

common/aicore/cm.cpp
This PR fixes the governor option to "optimize" food for growth, trying to find as much food as possible without having excess food when growing. The implementation of this feature isn't optimal but I found it easier to fix the current code than to implement something better.
I also implemented the governor option to disallow using specialists. The field for this was implemented in 2003 and maybe it was working back then, but I don't remember it working in any of the versions I played.
Closes #2058.
=> Implement two broken governor options

common/actions.cpp
The win probability could become negative or larger than one when Spy_Resistant effects were involved. Clip the probability between 0 and 1.
I think this is the only way #2035 can possibly have occurred so I would close it after this PR is merged.
Closes #2035.
=> Prevent negative action chance in diplomat battles

common/networking/dataio_raw.cpp, common/requirements.cpp
This makes the server fail to load the ruleset when an invalid enum-based requirement is specified. The LT79 and LeagueB2 rulesets have one and will stop loading. Since this is the server doing more error checking instead of ignoring invalid values, this is acceptable. We should remove the offending reqs from the games repo.
A client counterpart of the server-side checks is also implemented (duplicating a lot of code in the process...), so the client can now detect when the server sends invalid requirements. It prints a warning and sets the requirement to an invalid value that it won't attempt to interpret later on. This allows forward compatibility with future server versions.
Tested by trying to load the LT79 ruleset, loading the `classic` ruleset successfully, and connecting to broken …
=> Fix the server loading and the client receiving invalid requirements

client/tileset/layer_terrain.cpp
Check that there is a group before trying to dereference it. The user may not have provided one.
Closes #2017.
=> Fix crash in layer_terrain

common/city.cpp
The client's accounting of the shield stock didn't always take the bought shields into account.
Closes #1848.
=> Fix wrong numbers of turns displayed after buying

common/traderoutes.cpp
The Manhattan distance is `|deltaX| + |deltaY|`, which only makes sense when you can't move in diagonal. Since caravans can use the diagonal, the "Euclidian" (shortest path) distance is better suited for trade routes.
This introduces an incompatibility by changing (lowering) trade revenue for rulesets currently using CLASSIC. Since trade routes are usually OP, I don't think this is a big deal.
Closes #882.
=> Remove Manhattan distances from trade routes

server/techtools.cpp
When the technology for the current government is lost, the game used to pick some government at random. Be more punitive and always switch to Anarchy. This is more consistent with other government changes.
Closes #2047.
=> Switch to Anarchy when the current government is lost

.github/workflows/build.yaml
Since I don't know the full name, I'm just assuming it starts with build.
This fixes running tests in the CI on macOS.
=> Use the correct build directory for tests on mac

.github/workflows/build.yaml, server/civserver.cpp, utility/shared.cpp
This PR fixes build errors on FreeBSD and adds a weekly CI run to ensure it doesn't break in the future. While debugging FreeBSD, I understood the cause of the test errors on Fedora and also included a fix/workaround for that (FreeBSD got a different solution).
I did a full CI run [in my local](https://github.com/lmoureaux/freeciv21/actions/runs/7361897765) (before squashing debug commits into a nice history, but the code was identical)
=> Add a weekly FreeBSD CI run

cmake/FreecivDependencies.cmake, server/rscompat.cpp, server/stdinhand.cpp, utility/cmake_fc_config.h.in, utility/fcintl.h, utility/log.h
I went through the process of evaluating all [feature macros](https://github.com/longturn/freeciv21/wiki/Feature-macros) once again. The large number removed macros shows how much refactoring work has been happening since the last time we looked at this in 2020.
Closes #2103.
=> Remove unused feature macros

ai/default/ailog.h, ai/default/aiplayer.h, ai/default/daieffects.h, common/clientutils.h
As spotted by `clazy` and `clang-tidy`. This covers `ai` and `common/c*`.
No associated issue.
=> Add a few missing includes in headers

.github/workflows/build.yaml
Change the Windows Clang CI/CD action to use the same `lukka/run-vcpkg@v10` as we use for macOS. Both platforms rely on vcpkg, so it seems like we should use the same tool to install it. Caching works well and we might get better stability with the Windows Clang weekly builds this way, especially with the new release process that keeps the git hash up to date.
It runs fine in my fork - https://github.com/jwrober/freeciv21/actions/runs/7380419411/job/20077801399
=> CI/CD Windows Clang same as macOS

common/mapimg.cpp, server/savegame/savemain.cpp, utility/shared.cpp, utility/shared.h
* Remove a function provided by Qt
* Switch a `const char *` to a `QString` (and update docs)
* Fix a bug spotted by `clangd`
=> Small refactors in utility/shared.h/cpp

server/stdinhand.cpp, utility/registry_ini.cpp, utility/shared.cpp, utility/shared.h, utility/tests/test_paths.cpp
On top of #2121.
This PR unifies two functions, simplifying their interface to be more Qt-friendly.
=> QString-based interface for interpret_tilde

dist/snapcraft.yaml
No related issue. Bring `snapcraft.yaml` up to date with 3.1-alpha.4. Pushed to latest/edge channel
=> snapcraft.yaml - bring up to speed for 3.1-alpha.4

client/audio/audio.cpp, client/client_main.cpp, client/listener.h, server/advisors/advdata.cpp, server/advisors/advdata.h, tools/fcmp/mpdb.cpp
All bugs could have been spotted by running with ASan more often:
1. The wrong type of cast was used in the `listener` destructor. ASan warned about it.
2. `NULL` had been changed to `nullptr` in SQL code. #2128 
3. A use-after-free condition was present when shutting down audio. #2132 
4. Advisor data wasn't resized properly when switching tileset.
All commits are backport candidates.
=> Fix bugs affecting blabber of *BSD

.github/workflows/clang-tidy.yaml
Also upgrade codacy-clang-tidy to 1.3.8.
I was growing a bit worried not to see anything from Codacy. Turns out it's been broken ever since we moved to Ubuntu 22.04 because Codacy can't parse the colored output produced by clang 14 (which is the default). Use `ansifilter` to remove it.
I expect this PR to generate dozens of new warnings.
=> Fix passing the clang-tidy output to Codacy

client/menu.cpp
Saving a map to image fails, if the storage location described by QStandardPaths::PicturesLocation does not exist. Use the fallbacks already defined in the code, if the image would be saved in a nonexistent location.
Alternative solutions:
1. Make the location configurable in "Interface Options -> Map Image"
2. Open a "Save as..." dialog every time a map is saved
3. Create the location, if it does not exist (I'd prefer if no directories are created without my knowledge)  
In my experience the home directory is a sane fallback, especially as the full path to the image is displayed after saving. But this might be considered a workaround until a better solution ist implemented. Failing to save the image without showing the user a reason is definitely annoying and unexpected.
=> Fix image saving for nonexistent pictures location

server/sernet.cpp
This ensures consistent permissions across platforms that support them (so everyone but macOS).
=> Local socket: restrict permissions to the current user

client/citydlg.cpp, client/citydlg.h, client/citydlg.ui
Several things in this PR:
- Citizens are now drawn in multiple rows, where amount per row is controlled via `CITIZENS_PER_ROW`
- Fixed specialist rotating code so the correct specialist is picked even for large cities
- Add size hinting to `city_label` and several other places to prevent them being squished by the unit list when a city has too many units in it
Given that I don't really know C++, this is on a best-effort basis, but hopefully it's at least a bit helpful.
Fixes #2041 
Could partially work for #1904 as well, since that's caused by too many citizens in the second tab
=> Rewrite drawing of citizen sprites to use multiple rows

client/chatline.cpp, client/chatline.h, client/listener.h, client/map_updates_handler.cpp
Commit d1f50af71316b3ab817f0438aecd0a639a93af63 broke the listener<> template in a subtle way: the destructor wouldn't remove listeners from the set because dynamic_cast to a derived type returns nullptr in a destructor. This caused a segfault upon saving map images.
In order to solve both the warning that lead to the commit and the new bug, change the set of instances to hold listener<A>* instead of A*, and use dynamic_cast in invoke since the A objects are still valid there.
While I was there, I changed invoke() to be a variadic template. It wasn't one because the code originally had to support C++03.
=> Fix and modernize listener<>

utility/shared.cpp
There was an encoding issue in fileinfoname() that prevented finding files with special characters in the path when the system encoding wasn't UTF-8 (fc_stat would fail as if the file didn't exist because it always received the path in UTF-8). Rewrite the function using only charset-independent Qt APIs.
(I'll want to test the installer in Wine for a final cross-check once actions finish running)
Closes #565.
=> Fix fileinfoname for non-ASCII characters

.github/workflows/release.yaml
We got a spurious AutoRevision PR this morning because of missing event names in `release.yaml`. No related issue.
=> Fix release.yaml to properly run when needed

client/fc_client.cpp, client/fc_client.h, client/page_main.cpp, client/page_main.ui, tools/fcmp/mpgui_qt.cpp
=> Add an Add Ons button to start screen that loads mp installer

AUTHORS, tools/civmanual.cpp
Look mom, low hanging fruits!
This pull request removes images completely from the generated HTML as proposed by @jwrober in https://github.com/longturn/freeciv21/issues/1974#issuecomment-1641101883_
Closes #1974.
=> freeciv21-manual: Remove broken image links

client/views/view_units.cpp
The checks whether the find, disband and upgrade buttons should be enabled reference the wrong columns in the table.
This commit fixes the column references.
Reported by Corbeau on Discord.
***Screenshots demonstrating the fix***
| Before  | After |
| ------ | ----- |
| ![find broken](https://github.com/longturn/freeciv21/assets/1199257/440c32e0-d9bf-402a-8d0a-a4758870ba94) | ![find fixed](https://github.com/longturn/freeciv21/assets/1199257/bfc6716a-5883-455b-99b7-01b5c3e44cbc) |
| ![none broken](https://github.com/longturn/freeciv21/assets/1199257/5d843339-c624-4283-a129-29e3d392dec0) | ![none fixed](https://github.com/longturn/freeciv21/assets/1199257/5ad3a4f8-3d83-4480-aace-1228358c589b) |
| ![upgrade broken](https://github.com/longturn/freeciv21/assets/1199257/4665196a-e7a8-40b1-9682- …
=> view_units: Fix find, disband and upgrade buttons

README.md
Freeciv21 has been added to the FreeBSD ports tree as `games/freeciv21`. Add installation instructions.
=> README.md: Add FreeBSD

client/text.cpp
=> Add missing .arg() when there are no more content citizens

cmake/FreecivInstall.cmake, dist/freeciv21-server.cmd, dist/windows/freeciv21-server.cmd, dist/windows/qt.conf
Rendering of the Libertinus fonts was terrible with the (default) DirectWrite backend on Windows. Install a `qt.conf` file forcing Qt to use FreeType.
While reviewing Qt options I also found a way to make the window title bars dark if the user chose a dark theme. I enabled this as well.
Finally I moved files used for the Windows installer to dist/windows in an effort to organize that folder.
=> Force Qt to use FreeType on Windows

docs/conf.py
It was noted in #2155 that when packaging Freeciv21, sphinx_rtd_theme and sphinx_last_updated_by_git were needed at build time to create the man pages. The rtd theme is obviously only needed for HTML output and last_updated_by_git doesn't seem to be used with the man pages. Make them both optional by checking if they can be imported when evaluating the config.
This will allow package maintainers to ship man pages even if one of the two packages are missing from their distribution.
=> Docs: make external packages optional

docs/CMakeLists.txt
Fxes the handling of the `FREECIV_ENABLE_MANPAGES` option, leveraging the fact, that an `option` call is a no-op if the value is already set.
We also allow users on non-Unix systems to build manpages (for whatever reason one may want to do that).
Closes #2155
This needs a thorough review as I am non-fluent in cmake and don't have non-Unix systems available to test.
=> cmake: Fix the option to disable man pages

client/fc_client.cpp
The main window title had been `freeciv21-client` for a while. Now it's `Freeciv21`:
Suggesting to backport.
=> Give the main window a title

.readthedocs.yaml
Cherry-pick changes to `.readthedocs.yml` present in `master` but not in `stable`. This should fix the build error in #2166.
=> Bring stable rtd config to master level

.github/workflows/release.yaml
Fix the CI on stable and allow running it on demand.
This doesn't add Fedora nor FreeBSD.
=> Cherry-pick GitHub workflow commits for stable

cmake/NSIS.template.in, dist/net.longturn.freeciv21.metainfo.xml.in
There is no need to use such a technical term in user-facing text. This also removes any need for translation.
=> Remove "client" from the app name on Windows and in AppStream metadata

client/repodlgs_common.cpp, client/repodlgs_common.h, client/views/view_economics.cpp
Part of #1238. List the names of cities where the redundant improvement resides. Does not offer a quick link at this time, but at least gives you the some more information. Units are never redundant, they are upgradeable, which is shown on the units view.
=> Add redundant city names

.github/workflows/build.yaml
Part of release process to update and keep us current.
=> Update vcpkgGitCommitId before Alpha.5 release

server/unithand.cpp
The patch cf7e1bd2bc0d457bd17b7c10438fd73387112614 had been applied improperly. Follow upstream code.
Closes #2183.
=> Fix use-after-free in do_attack

docs/Manuals/Advanced/index.rst, docs/Manuals/Advanced/map-generator.rst
=> Add a map gen manual page

common/scriptcore/tolua_game.pkg, data/civ1/units.ruleset, data/civ2/units.ruleset, data/civ2civ3/units.ruleset, data/classic/units.ruleset, data/default/default.lua, data/experimental/units.ruleset, data/granularity/units.ruleset, data/multiplayer/units.ruleset, data/royale/units.ruleset, data/sandbox/units.ruleset, data/stub/units.ruleset, docs/Modding/Rulesets/effects.rst, server/scripting/api_server_edit.cpp, server/scripting/api_server_edit.h, server/scripting/tolua_server.pkg, server/unittools.cpp
This PR adds flexibility to partisans and changes the default behavior when they cost population:
* Multiple partisan unit types are now supported. The game will pick one the player can build, or the first one if the player can't build any
* When partisan units cost population, the population is taken away from the conquered city (rationale: it's an exodus)
In the ruleset you're playing:
* Lower or remove requirements for the `Inspire_Partisans` effect
* Add the `Partisan` flag to some normal unit, e.g. Musketeers
* Change your favorite Partisan unit's `pop_cost`
Then conquer a city. You should see partisans of an appropriate unit type appear and the city size be reduced accordingly if they cost population. The city should never be wiped out.
=> More flexible partisans

.github/workflows/build.yaml, .github/workflows/release.yaml
No related issue. Noticed the warning when looking at action results.
=> Update to node.js v20 actions based on deprecation warning

docs/CMakeLists.txt
If `FREECIV_ENABLE_MANPAGES` was set to `OFF` and Sphinx was available, this setting was ignored during the build on Unix-like systems.
This commit fixes this issue.
=> Support build without manpages on Unix-like OS

tools/fcmp/download.cpp, tools/fcmp/mpcli.cpp, tools/fcmp/mpdb.cpp, tools/fcmp/mpgui_qt.cpp
When the modpack installer updates an already installed modpack, it emits a bogus critical message that a query failed with error code 100.
Error code 100 is `SQLITE_ROW` and is not really an error, but signals that a data row has been successfully read. `SQLITE_ROW` is also an expected return value in `mpdb_update_modpack`.
Change the check for failed queries to ignore `SQLITE_ROW`.
=> fcmp: Fix bogus "query failed" message

server/ruleset.cpp
Otherwise the requirements could reference unknown (not yet sent) objects. This was seen with nation groups.
Closes #2197.
=> Send action enablers at the end of the ruleset

tools/fcmp/mpdb.cpp
The string allocated for filename manipulation was never deleted. Replace the related code using Qt, eliminating the need for a direct allocation.
Closes #2216.
=> Fix a memory leak in the modpack installer

client/clinet.cpp, client/gui_main.cpp, client/qtg_cxxside.h
Since it's used everywhere in the client code to determine the current player, keeping it set to a dangling value triggers various assertions.
Closes #2195.
Backport candidate
=> Unset client.conn.playing on disconnect

client/tileset/tilespec.cpp
Border sprites were not colored properly for tilesets with very large sprites, like Vectron. Take the tileset sprite size into account.
Vectron after:
Backport recommended
=> Fix borders for large tilesets

client/tileset/layer_darkness.cpp
Used e.g. in hexemplio (tile edges fading to the unknown).
=> Fix drawing darkness sprites

server/ruleset.cpp
The FerryBoat flag is only meaningful for units that can transport. Warn when the flag is set for non-transport units, and unset it. This prevents an assertion failure later on.
Closes #2238.
=> Warn about non-transport FerryBoat units

docs/Contributing/dev-env.rst, docs/Contributing/eval-pull-request.rst, docs/Contributing/pull-request.rst, scripts/eval-pr
No related issue. Based on commentary helping another coder get setup.
=> Update the eval-pr scripts and docs to match

data/hex2t.tilespec, data/trident.tilespec
No related issue. Getting rid of some noise on the console.
=> Remove duplicate sprite error in trident and hex2t tilesets

.github/workflows/build.yaml
The macOS CI stopped working, seemingly because multiple Python versions are installed simultaneously. We forced the Python version in response to #2069. There is now a proper fix for #2069 in upstream vcpkg. Update the vcpkg version so we can use it.
=> Fix the macOS CI build

client/citydlg.cpp
=> Colorize (red) negative values on city dialog

.github/workflows/release.yaml
=> Use native compression tools instead of git archive for releases

server/plrhand.cpp
This reverts commit ecd275d7a487c8859446fe53d0b94745930a95db.
The current implementation has issues, that need to be resolved first:
* AI will fail to declare war, if entangled in a web of alliances
* Cease-fires running out, will end in an "undefined" state if war can't be entered because of alliances
Related to: #2214
=> Revert "Prevent user from declaring war if it would break alliances"

docs/Contributing/visual-studio.rst
=> Update Visual Studio installation steps to current

client/tileset/tilespec.cpp, client/tileset/tilespec.h, client/views/view_map.cpp, client/views/view_map.h, data/amplio2.tilespec, data/hex2t.tilespec, data/hexemplio.tilespec, data/isophex.tilespec, data/isotrident.tilespec, data/trident.tilespec, docs/Modding/Tilesets/graphics.rst
This is used to render the tileset by default and when the user resets the zoom. Useful to emulate HiDpi.
Vectron will use this.
=> Allow tilesets to specify a default zoom level

client/views/view_map.cpp
Using pixelDelta() resulted in seemingly meaningless values on KWin/Wayland. Qt code uses angleDelta() exclusively, so I see no reason not to do the same.
Closes #2236.
Suggest to backport (if we do another stable)
=> Always use angleDelta() for scrolling

client/citydlg.cpp
Force white-space:pre in all cases to preserve the alignment.
Closes #2276.
=> City dialog: Fix label alignment for negative values

client/options.cpp
This PR removes map image options from the configuration dialog, as a temporary solution for #2237.
As a side-effect, any settings previously set by the user will be discarded when saving the config file. I don't consider this an issue since the options were basically useless; anyone changing them would have left them in a random state.
=> Temporarily remove map image options

docs/Getting/compile.rst
No related issue. Found while working on Open Build Service packages.
=> Docs: Update supported OSs for compilation

client/unitselect.cpp, client/unitselect.h
The unit selection popup for stacks in the open (and in allied cities) didn't behave very well with many units: its width remained fixed to 4 and it was showing at most 12 units -- quite a small stack for a serious attack. In addition, the last row was in some cases inaccessible due to a scrolling bug (maybe Wayland-specific; #2285).
Increase the base width of the menu to 5 units (a loaded Galleon), and further to 6 when there are more than 25 units. Show up to 36 units (four fully loaded Transports) at once before resorting to scrolling.
Fix the scrolling bug, which was related to scroll events with deltaY=0 being interpreted as scrolling upwards.
Closes #2285.
---
This was likely already a bug in 3.0, so we should consider backporting the fix if there is another dot release.
=> Improve sizing and scrolling of the unit choice popup

client/CMakeLists.txt, client/citydlg.cpp, client/text.cpp, client/text.h, client/unitselect.cpp, client/unitselect.h, client/utils/unit_utils.cpp, client/utils/unit_utils.h
On top of #2287 - check the second commit.
This patch makes the user interface look more consistent by sorting
units in two contexts:
* In the city dialog
* In the unit picker
The sorting logic is an improved version of code formerly used to sort
units in the city dialog (but that had been lost for some reasion). It
tries to produce a sort order that looks natural and is stable in time.
To do so:
* Loaded units are always sorted right after their transport, so one can
tell in which transport they are loaded;
* The best defensive units go to the beginning of the list. These tend
to stay in cities and not move around too much;
* Tie breaker by unit type and nationality ensure similar units are
grouped together;
* Finally, the unit id is used as a last resort.
I tested this logic in a few …
=> Sort unit lists shown to the user

server/diplhand.h, server/plrhand.cpp, server/plrhand.h, server/srv_main.cpp
This is a follow-up PR for #2214 and #2239.
Closes #2177.
In games with complex alliance systems, declaring war can have unintended consequences. To protect the user from cancelling alliances by accident:
* When declaring war would result in an alliance being cancelled, require the user to cancel the alliance first.
* When declaring war would force one of your team mates to cancel an existing alliance, require this alliance to be cancelled first.
* When a cease-fire running out would result in an alliance being cancelled, automatically lengthen the cease-fire until the alliance gets cancelled.
=> Add some protection measures for a players alliances

client/views/view_units.cpp, client/views/view_units.h
A timer triggers a periodic update of the UWT table in the unit view. Each update clears the current contents of the table and rebuilds it from scratch. As a result, the list loses its scrolling state and scrolls back up.
This PR changes the behavior to update existing entries and only selectively delete and add entries as needed.
To match units to their entries in the table, a hidden id column has been added to the UWT table.
Closes #2296
=> Do not rebuild contents when UWT table is updated

.github/workflows/build.yaml
No related issue. Windows Clang build is failing. Hoping this fixes it.
=> Bring vcpkg ID up to date

client/attribute.cpp, client/governor.cpp, client/widgets/city/governor_widget.cpp, client/widgets/city/governor_widget.h
This is an attempt at fixing some governor issues mentioned by TriClad.
Maybe will eventually address #1834
=> Governor fixes

client/shortcuts.cpp
This reduces the risk of hitting it by accident.
Closes #2303.
=> Change the default autoexplore shortcut to Shift+X

client/citydlg.cpp
This allows giving orders to one's own units in the city and scrolling through the unit list.
Closes #2302.
Closes #2286.
=> Don't disable the present units list when investigating

client/views/view_cities.cpp
When buying production with multiple cities selected in the cities view, always buy from the cheapest cities. This ensures that we buy from as many cities as possible.
Closes #2311.
=> Always buy the cheapest options in the cities view

client/tileset/tilespec.cpp
The user should be able to set tilesets and widget styles independently. Having one influence the other cannot be made to work in a way that's not confusing.
The code was not used anyway.
=> Remove unused code for tileset preferred themes

common/path_finder.cpp
It's common to select sentried or fortified units and initiate a goto. Currently this requires a click on the units to unset any activity they may have. Do this automatically in the path finder.
Closes #2272.
=> Automatically cancel the current activity in goto

server/citytools.cpp
In my last game someone used names like `         aa`, which caused all
sorts of UI issues. Disallow names that start or end with a space, or
have multiple spaces in the middle.
=> Forbid too many spaces in city names

client/repodlgs_common.cpp, client/views/view_economics.cpp, client/views/view_economics.ui
Fix wrapping redundant cities in the economics view
We were resizing columns to avoid wrapping with resizeColumnsToContents,
then resizing rows. This produced horizontal scrolling and strange
behaviour when the redundant list got long.
Fix this by:
1) Setting the last column (redundant cities) to use all remaining
space, and
2) Adjusting the width of all columns except the last.
Closes #2289.
Tested locally by inverting the logic of `get_economy_report_data` to show all non-redundant cities (which is usually many).
=> Fix wrapping redundant cities in the economics view

docs/Manuals/Game/menu.rst, docs/Playing/faq.rst, docs/glossary.rst
We have multiple mentions of MP2 in the docs, including one in the manual suggesting that we support the ruleset (how did this come to be?). Adjust the wording slightly.
=> Reduce mentions of MP2

client/views/view_units.cpp, client/views/view_units.ui
Put units-table and units-waiting-table into a splitter to facilitate adjusting the ui for many units.
If no units are waiting, the units-waiting-table is hidden and the units-table uses the full available screen estate.
Closes #2313.
=> Fix units view for many units

server/generator/fracture_map.cpp
The fracture generator was always generating seas at the edges of the map, which is a strange thing to do when the map is wrapping along x or y or both. Stop doing this in wrapping topologies.
To test, generate a few maps with revealmap=start and generator=fracture. Then play with wrapx and wrapy
=> Fracture: take map wrapping into account

common/city.cpp
Governors that forbid specialists do not bother computing how much specialists would produce and end up with an empty specialist output cache. When applying solutions to evaluate them, however, we were trying to use the cached values. Only do it when there specialists are actually present in the solution.
See #2332.
=> Fix a crash for governors without specialists

common/city.cpp
While debugging an issue reported in LT85, I found that in certain circumstances an empty specialist output cache (introduced in 5c44029) is accessed, what crashed the client.
An obvious fix, contained in this PR, is limiting access to non-empty caches. There may be better ways to handle this though.
While here, I applied the same safety measure to the waste level cache, introduced in ecabf5d.
=> Don't access items in empty cache

.github/workflows/clang-tidy.yaml
This is needed for compatibility with the latest download-artifact.
=> Bump actions/upload-artifact to 4.1.7

client/views/view_nations.cpp
They were always sorted from Z to A, which felt wrong.
Test plan:
* Load a game with many players
* Open the nations dialog
* Check that it's sorted A-Z and not Z-A
=> Sort players alphabetically in the nations view

.github/workflows/clang-tidy.yaml
This will pick the latest available v4 for both actions without us needing to care about exact version numbers. Should fix the clang-tidy action.
The changes will only take effect once merged in `master`.
=> Use @v4 for actions/{upload,download}-artifact

client/top_bar.cpp
The `science_report` loses the scroll position when the view is closed. This is because the object is destroyed and therefore loses its state.
This commit adds code to track the scroll position in static fields and restore the state when the `science_report` is reinstantiated.
Closes #2329.
An alternative solution would be to prevent the destruction of `science_report` when the view is closed; this is the behavior in stable.
=> Keep scroll position when reinstantiating science_report

client/packhand.cpp, client/views/view_map_common.cpp, client/views/view_map_common.h, common/generate_packets.py, common/networking/packets.def, server/unithand.cpp, server/unittools.cpp, server/unittools.h, utility/fc_version.h.in
Bombarding cities was very powerful because it was showing every unit inside the city, something only diplomats and spies can normally do. Stop sending this around.
=> Only send bombardment combat when targets are visible

docs/Contributing/release.rst
No issue, found while doing steps for 3.1-beta.2
=> Docs: Fix snap release steps

cmake/FreecivDependencies.cmake
The server now depends on Gui for map image support. Gui was already required in complete builds because all other components use it through Widgets. Make sure it is also required in server-only builds.
Found while building the server for Sim06
=> Always require QtGui

client/governor.cpp, client/governor.h
The governor code was using pointers to keep track of cities to be removed or updated. These pointers would sometimes become invalid when the city was lost or otherwise conquered, causing use-after-free errors.
This fixes the first version of #2351.
=> Remove dangling city pointers from the governor code

client/views/view_research.cpp, server/techtools.cpp
Closes #1753
Marking as draft for now. Need an event to test it.
=> Fix research refresh button

.github/workflows/release.yaml
Using tips from the action's author to remove the problem file.
Closes #2370
=> Update AutoRev release steps

ai/default/aiunit.cpp
No related issue.
CID 1435482, 1435595
=> Cleanup two divide-by-zero issues from Coverity

client/tileset/layer_roads.cpp
Some roads were missing in hexemplio because of confusion between two kinds of indices, directions valid for the tileset and all possible directions.
Reported by jockel, Corbeau, and others on Discord.
=> Fix drawing AllSeparate roads in hex mode

docs/Contributing/dev-env.rst, docs/Contributing/game-admin.rst, docs/Contributing/index.rst
=> Docs: New Game Admin page

client/page_game.cpp
Remove a useless condition for showing it. Spotted by Corbeau on Discord.
=> Fix showing the city count when there is no capital

client/citydlg.cpp
There were already a Cancel button and right click to close, but ESC is more natural.
Closes #2383.
=> Support ESC to close the production menu

client/views/view_research.cpp, server/techtools.cpp
Upon getting a free tech, the server was sending the updated research before it was done updating the struct. The client received contradicting information (in #2405, that the tech was both fully researched and still the current tech goal).
Closes #2405.
I tested the following cases:
* Tech from hut with no target set
* Tech from hut with a goal set (the next tech towards the target gets selected and researched immediately if there are enough bulbs)
* Researching techs with and without a target
* Getting a tech from allies
=> Send updated research after it is fully updated

client/minimap.cpp, client/minimap.h
The widget needs to compute horizontal and vertical scaling factors to map between the displayed minimap (in pixel units) and the computed one (essentially in tile units). It was computing them on resize events and storing them, which was causing issues when switching maps. Compute them when they are needed instead, it's just two float divisions.
Also remove a bunch of unused variables from the class.
Closes #1657.
=> Save less state in minimap_view

client/views/view_units.cpp, client/views/view_units.h
The units view was crashing when more than 250 units were on UWT. This was reported by @Corbeau-1 on Discord (Sim06).
The second commit isn't strictly necessary but keeps things consistent.
=> Fix a crash in the units view

server/savegame/savegame3.cpp
Use snprintf instead of sprintf.
Closes #2415.
=> Fix buffer overflow in quote_block

client/dialogs.cpp, client/views/view_map.cpp, client/views/view_map.h, client/widgets/report_widget.cpp
When connecting to a game and receiving an historian report, they would often be shown out-of-screen. This is ultimately caused by the resizing of the client window happening only after the game state is fully loaded. The placement algorithm has to provide sensible results when the widget doesn't fit inside the (small) base window size.
The complicated placement algorithm relied on an initial guess for the position and could result in the widget being shown off-screen when the window was too small. Replace it with a linear scan going left-to-right and top-to-bottom across the entire screen. Also avoid recursion, permitting more attempts by lifting the limitation due to the stack size.
This doesn't entirely solve the issue of widgets being shown in an unexpected location when connecting to …
=> Fix reports being shown out of screen

common/path_finder.cpp, server/savegame/savegame3.cpp
The sub_target should be set to NO_ORDER by default, otherwise we get a warning when reading back from saves.
Closes #2394.
.I tested using the save from #2394:
* Set long goto for a few paratroopers
* Save
* Load again
* Warnings are gone
=> Initialize order.sub_target in path_finder

common/actions.cpp, data/civ1/game.ruleset, data/civ2/game.ruleset, data/civ2civ3/game.ruleset, data/classic/game.ruleset, data/experimental/game.ruleset, data/multiplayer/game.ruleset, data/royale/game.ruleset, data/sandbox/game.ruleset
"You're Fired" was difficult to understand and was on a totally different tone than other action names.
Closes #2392.
=> Action names: You're Fired -> Disband Unit

client/citydlg.cpp, client/citydlg.h, client/citydlg.ui
=> City Dialog: ExpCol present units list

common/effects.cpp, common/helpdata.cpp
* Sort effects alphabetically
* Show correct values for `Output_Waste_by_Distance`
=> Fix issues with effects in help dialog

client/options.cpp
The default tilesets were not set when starting the game for the first time. This resulted in hexemplio being used regardless of the game topology.
Closes #2441.
=> Fix setting default tilesets

server/unithand.cpp
In some places, "A" and "D" were switched. Also in a case the defence value was not displayed at all; which was not consistent with the rest.
=> Minor fixes to battle messages

docs/Manuals/Server/index.rst, docs/Manuals/Server/maths.rst
Requested by Corbeau on Discord.
See #1573.
=> Document unit bribe cost

docs/Modding/Rulesets/actions.rst, docs/Modding/Rulesets/effects.rst
Document what is considered a nuclear weapon. Add links in both directions between the effect controlling their availability and nuclear actions.
Requested by Hawk on Discord.
=> Improve the documentation of Enable_Nuke

client/views/view_units.cpp
Views are no longer destroyed, if the view is switched. That's the reason why the `popdown_units_view`, that is called after clicking "find nearest unit", is no longer guaranteed to show the map.
Closes #2451
=> Units view: Show map after clicking "find nearest unit"

common/map.h, docs/Manuals/Server/options.rst
Some generators can generate maps without water. Allow game admins to request this.
Closes #2444.
=> Allow setting landmass to 100

server/maphand.cpp, server/srv_main.cpp, server/unittools.cpp, server/unittools.h
See osdn #44155
Closes #1064.
@XHawk87
=> Climate change: Check unit activities on tiles surrounding changed one

docs/Modding/Rulesets/effects.rst
* Warn that Stealth and Subsurface must be smaller than Main
* Fix the ruleset option name Vision_Layer
See #2459.
=> Improve vision effects docs

ai/default/daicity.cpp, ai/default/daieffects.cpp, client/citydlg_common.cpp, common/city.cpp, common/city.h, common/effects.cpp, common/effects.h, docs/Modding/Rulesets/effects.rst
This adds a Pollu_Trade_Pct effect that can be used to generate pollution from trade. This may be more realistic for trade-based governments like Democracy.
Requested by Hawk.
Closes #2446.
Add the following effect to your favorite ruleset:
```ini
[effect_pollution]
type = "Pollu_Trade_Pct"
value = 100
```
Now try to tame down GW...
=> Add the ability to turn trade into pollution

client/utils/unit_utils.cpp
When selecting a stack, we were trying to sort the units by nationality. This information isn't available for allied players (unit->nationality is null). Use unit->player instead.
This solves player.cpp:758 - Assertion nullptr != pplayer failed
=> Fix assertion error when selecting allied stack

client/control.cpp, client/control.h, client/hudwidget.cpp, client/hudwidget.h, client/views/view_units.cpp, docs/Manuals/Game/unit-controls.rst
Since the new Units Report was introduced in 3.1, there was no longer a way to cycle all units of a given unit type on the map.
With this commit scrolling the mouse wheel on the selected unit icon in the "Unit Controls" widget, cycles through idle or sentried units of the same unit type.
=> Implement units cycling

client/repodlgs_common.cpp, client/repodlgs_common.h, client/views/view_cities.cpp, client/views/view_cities.h
=> Fix selling improvements for multiple cities at once

server/citytools.cpp, server/diplomats.cpp, server/maphand.cpp, server/savegame/savegame2.cpp, server/savegame/savegame3.cpp, server/unithand.cpp, server/unittools.cpp, server/unittools.h
=> Refactored bounce_unit to allow reporting using function callbacks

client/spaceshipdlg.cpp, client/top_bar.cpp, client/views/view_research.cpp
=> Fix inconsistent behavior when using view shortcuts

common/scriptcore/api_game_methods.cpp, common/scriptcore/api_game_methods.h, common/scriptcore/tolua_game.pkg
=> Added support for using featured text links in Lua

client/dialogs.cpp
This addresses the missing parts from issue #1612. While I already made F6 (research view) and F12 (spaceship view) work as a toggle, making F7 (wonders of the world), F8 (top 5 cities) and F11 (demographics) work like that is a bit special.
These reports are generic notification popups, which the server triggers to be displayed. The flow is
1. the user presses F7
2. the client asks the server for the research report
3. the server sends the research report
4. the client displays the report in a notification popup by calling `popup_notify_dialog`
This PR changes the behavior of subsequent calls to `popup_notify_dialog`. The former behavior was to refresh an existing notification, the new behavior is to close the existing notification. The notification to be manipulated is, in both cases, …
=> Toggle report notifications

server/cityturn.cpp
Conquest removes all shields from the city production. This means the penalty on bought shields is no longer needed.
Not resetting to zero resulted in negative shields with the following sequence of events:
1. Player A buys something
2. Player B conquers the city (the shield stock becomes 0)
3. Player B changes production
4. The bought shields penalty is deduced from the empty shield stock
5. Negative shields!
This is needed in a few more cases such as sabotage. Implement the change in nullify_prechange_production that is already used when changing production.
Noticed by TriClad in Sim06.
=> Remove the bought shields penalty after conquest

client/chatline.cpp, client/chatline.h, client/mapctrl.cpp, client/shortcuts.cpp, client/shortcuts.h, docs/Manuals/Game/shortcut-options.rst
Splits the functionality to create unit links for the chatline from the functionality to create tile/city links. This allows the user to create a tile link for a tile, even if it is occupied by a unit.
| Shortcut           | Old behavior                   | New behavior                   |
| ------------------ | ------------------------------ | ------------------------------ |
| Ctrl-Alt-RMB       | Link to (unit -> city -> tile) | Link to (city ->tile)          |
| Ctrl-Alt-Shift-RMB | ./.                            | Link to (unit -> city -> tile) |
It is possible to restore the old behavior by rebinding the shortcuts.
No documentation changes are required, as this matches the existing chatline documentation in `data/helpdata.txt`.
Closes #2524
=> chatline: Split creation of unit links from tile/city links

client/helpdlg.cpp, client/helpdlg.h
The bars representing the stats of a unit are no longer drawn relative to the maximum value of the unit class, but to the maximum value of all available units.
Closes #1708
=> Draw bars for unit stats relative to all units

common/terrain.h, server/ruleset.cpp
The savegame compatibility code was assuming that extras appeared in the same order as resources in the ruleset. This is obviously not always a valid assumption.
Fixes loading the SG4 scenario (I'll fix the ruleset so it works without this patch).
Backport suggested.
=> Fix loading resources from 2.6 saves in some rulesets

client/citydlg.cpp, client/citydlg.ui, client/widgets/city/governor_widget.ui
This is done by removing needless frames and moving the Optimize: button to its own line. The gain is about 100px on my system.
Qt Designer tried to update enumerator names in the UI file and made many mistakes. I tried to fix them but there might still be some.
We may want to backport to 3.1 but this is also a bit risky given the mess created by Designer.
=> Reduce the width of the governor tab

.clang-tidy, CMakePresets.json
Part of #2464. 
The idea is to enable clang as the compiler and include checks into the build system. We can add more checks as we clean up code as refactoring continues.
=> Add clang CMake Preset

client/helpdlg.cpp, client/helpdlg.h, client/hudwidget.cpp, client/mapctrl.cpp, client/text.cpp, client/text.h, client/views/view_map.cpp, client/views/view_map.h, docs/Manuals/Game/top-bar.rst, utility/astring.cpp, utility/astring.h
This PR adds the infrastructure needed to support links, pointing to help pages, in the info tile popup and adds a first help link for the selected unit.
This is based on #2540 and more PRs will follow to add all the links demonstrated in the Proof of Concept, but I will need some time to clean things. But it's probably better to split up the PRs anyway to keep the reviews manageable.
=> Add unit help link to info tile popup

client/client_main.cpp, client/connectdlg_common.cpp, client/connectdlg_common.h, client/gui_main.cpp, client/options.cpp, client/tileset/tilespec.cpp, server/scripting/script_server.cpp, server/srv_main.cpp, tools/civmanual.cpp, tools/fcmp/modinst.cpp, tools/ruledit/ruledit.cpp, tools/ruleup.cpp, utility/fciconv.cpp, utility/fciconv.h, utility/shared.cpp, utility/shared.h, utility/support.cpp, utility/support.h
This PR tries to sanitize the handling of character encodings:
* Remove support for non-utf-8 internal and data encodings.
* Remove all calls to the C file API and replace them with native Qt APIs. This should prevent path encoding issues like #565.
I checked the following under `wine` for files with accents in the name:
* Reading serv files (from the server prompt, with the `-r` option, and from the client)
* Finding tilespec file
* Handling UTF-8 ruleset files (Royale's Ħal Saflieni Hypogeum)
I couldn't check the following because the file names don't have accents in my setup:
* Removing the test file used for cmdlevel hack
* Finding and using the client settings file and modpack DB
=> Refactor encodings

client/attribute.cpp
Disabling the governor in the last city that had one was broken because the attribute block was not sent to the server when empty. Now it is and removing the last governor is working again.
Closes #2472.
Backport requested -- this is a 3.1 blocker.
=> Fix disabling the last governor

server/CMakeLists.txt, server/demographic.cpp, server/demographic.h, server/report.cpp
This adds a new class, demographic, whose task is to compute a single line in the demographic report for a single player. It also knows how to format the text and how to sort values.
This is a first step towards unifying demographics, the end game report, historian reports, and the scorelog.
See #2020, #2110, #2114.
=> Factor out demographic calculation so we can generalize

common/player.h, server/report.cpp, server/report.h, server/savegame/savegame3.cpp, server/score.cpp
This fixes #2114 by calculating (all) demographics at turn change and saving the values in `player->score.demographics`. They are also stored in saves so a save/load cycle doesn't lead to a recalculation.
=> Store demographics values at TC and use them for the demographics report

flake.nix
On top of #2222. This updates the dependencies in the NixOS config, everything seems to work (builds fine and the client runs).
=> Fix the NixOS flake for Qt 6

vcpkg.json
On top of #2222. This is currently incomplete because vcpkg doesn't have KF6 packages.
=> Bump the vcpkg config to use Qt 6

client/packhand.cpp
Apply the fix from a458a80 to the foreign units.
=> Fix garbage unit names for foreign units

.github/workflows/clang-tidy.yaml
Ensure curl and wget are availble for the clang-tidy workflow: install wget in the Ubuntu 24.10 container when running clang-tidy and use the base GitHub image to upload the results (it already has curl and we don't need anything else).
=> Fix running cland-tidy on the Qt 6 CI

.clang-tidy, docs/Coding/guidelines.rst
See #2599. I also removed an item in `.clang-tidy` that isn't supported by 17
=> Docs: Add more tips for IWYU and clang-tidy

utility/shared.cpp, utility/shared.h
We were getting warnings with clang on Windows when assigning string literals to a char* variable. The reason for this was long gone. Renovate the code around it to manipulate the environment with encoding-aware Qt instead of bare getenv/putenv.
=> Don't assing string literals to a non-const char*

.github/workflows/build.yaml
Disabled macOS and Windows Clang while vcpkg catches up. Also remove the wasm action as we are not supporting it.
Part of #2612
=> Disable broken build actions

.github/workflows/build.yaml, CMakeLists.txt, cmake/CPackConfig.cmake, cmake/FreecivBackward.cmake, cmake/FreecivDependencies.cmake, cmake/FreecivInstall.cmake
Closes #2609 
I also took the opportunity to remove some 32-bit checks. Since we don't support 32-bits any longer we don't need it now.
With the move to `clang` as part of going to Qt6 we don't also need to check for `MINGW` for most of the checks, so I removed those as well.
=> Fix Windows MSYS2 install and package

client/views/view_map.cpp
On Qt 6.8.3, it was not possible to open the tile info popup. Adding a `QWidgetAction`, containing the layout that was directly added to the `QMenu` before, fixes the behavior.
While here: Scale tile_height according to the current map setting
Closes #2603
=> Fix tile info popup behavior

client/unitselect.cpp, client/unitselect.h
On Qt 6.8.3 the popup was always placed at the origin of the map view. This is caused by missing `QAction`s in the `QMenu`. Adding a `QWidgetAction` fixes this issue.
Minor additional fixes:
- Remove superfluous call to show() on units_select
- Reduce minor code duplication.
Closes #2604
=> Fix unit selection placement behavior

server/savegame/savegame3.cpp
Closes #2632
Recommend a back port to stable as it's broken there too for nix builds.
=> Fixed buffer overflow on saving player attribute data

.github/workflows/coverity.yaml
No related issue. Change to Ubuntu 24.10 seems to not include `wget`
=> Update coverity.yaml to include wget

server/ruleset.cpp
Compiling stable in debug mode was failing with another -Wmaybe-uninitialized false positive. Ensure the compiler knows the value is initialized.
Backport requested.
=> Fix one more -Wmaybe-uninitialized

.github/workflows/build.yaml
This fixes the build but now we get an ARM-only dmg. I haven't been able to change it to x86 or to create a universal binary. It seems vcpkg doesn't support the latter.
Binaries for x86 Mac is a release blocker. Older macs cannot execute ARM code, while newer macs can execute x86.
=> [stable] Update vcpkg to 2025.04.09 to fix macOS builds

client/audio/audio_qt.cpp
Commit #2648 added a check that emits a configure warning if the backend of the Qt audio plugin does not support Ogg Vorbis. This commit adds an identical check to the Qt audio plugin itself and emits a warning when the plugin is loaded at runtime.
=> Emit warning if the Qt audio plugin does not support Ogg Vorbis

data/nation/barbarian.ruleset, data/nation/pirate.ruleset
Some leaders of the Barbarian and Pirate nations had misspelled names (noticed this after looking up François l'Olonais). Fix them using the preferred spellings from English Wikipedia. I didn't touch Ching Shih because it didn't seem so clear.
=> Fix spelling mistakes in barbarian leader names

client/governor.cpp
We got reports that governors did not behave as expected in many cases, showing strange results and inconsistent with server-side data. This was in reliably observed when doing /take or /observe (#1834).
Governors run whenever information about a city changes, including when it is seen for the first time. There is a catch, however: the city may be sent before all game data is known. In this case its processing must be delayed. This is achieved using freeze/thaw packets sent by the server.
The governor code was incorrectly disregarding the freeze/thaw mechanism, resulting on governors being run on incomplete data. Fixing this solved the observed issues with /take and /observe. It also speeds up the initial connection by running governors less often (somehow city information gets sent …
=> Stop running governors on incomplete game data

client/editor/map_editor.cpp, docs/Manuals/Server/options.rst, server/settings.cpp, server/stdinhand.cpp
There was no way for server administrators to set the connection username before a player connected for the first time. This forced players to /take themselves when connecting to a Longturn server for the first time (#1599).
A slightly unrelated issue was that the `allowtake` setting was applied even to local games (#2552). This allowed users to shoot themselves in the foot. Those players could always modify `allowtake`, but it wasn't immediately obvious.
This patch solves the first issue by allowing the console or HACK connections to issue `/take <username> <player>` even if there is no existing connection called `<username>`.
Since the fcdb API exposes the connection object and not merely the username, it could not be called without an active connection. Instead of changing the API, I …
=> Allow overriding connection names from the console

docs/conf.py
sphinx_lua_ls isn't packaged for my system and I want to do the main build outside a virtualenv if possible.
Make sphinx_lua_ls optional. We get warnings when it's not there, which is fine.
=> Support compiling without sphinx_lua_ls

common/helpdata.cpp, common/movement.cpp, common/movement.h, common/reqtext.cpp, common/requirements.cpp, common/unittype.cpp, server/unithand.cpp, tools/civmanual.cpp
The function was allocating memory using qstrdup, but none of its callers was freeing it. Force them to pay attention by returning a QString instead of const char *.
Found by ASan.
=> Fix memory leak in move_points_text_full

client/views/view_map_common.cpp
The game was crashing on Windows when attacking units on a local server. This was caused by network input being processed in the middle of the animation and units being deleted. This was caused by anim_delay() processing events. Strangely enough, this doesn't happen with TCP sockets.
This patch reintroduces a blocking sleep in anim_delay() on Windows. It blocks the window and might lead to it being unresponsive, but this is better than an almost guaranteed crash.
A proper fix would include a better framework for animations, which cannot be done in time for 3.1.
**Note that this patch is for the `stable` branch only.** I do not consider it an appropriate fix for master.
=> Prevent a crash on Windows

cmake/NSIS.template.in
The Windows installer was running the uninstaller in parallel with the installer, which sometimes resulted in incomplete installs (#2722).
Fix this issue by running the uninstaller synchronously. In addition, run it only after the user commits to installing the new version: simply opening the installer shouldn’t uninstall the current Freeciv21.
Closes #2722.
=> Fix incomplete installs on Windows

docs/Manuals/Advanced/map-generator.rst, server/generator/height_map.cpp, server/generator/startpos.cpp
* Possibility to create maps with a medium number of islands (5-10) with FRACTAL and startpos=VARIABLE
* Enhanced starting positions with startpos=VARIABLE
See commit messages for individual details.
Tested with:
```
set nationset all
set aifill 60
set mapsize PLAYER
set tilesperplayer 80
set topology WRAPX|WRAPY|ISO
set generator FRACTAL
set startpos VARIABLE
set landmass 29
set revealmap start
set fogofwar disabled
set mapseed 2134
start
```
Notice the small islands also getting populated (but there are many players). Starting there would be its own challenge.
This may require updating the high-level mapgen docs...
=> Map generator tweaks

server/savegame/savemain.cpp, server/savegame/savemain.h, server/stdinhand.cpp
Savegame loading is modified in a way better suitable for loading from vastly different formats.
This lays down groundwork for #2748.
=> Refactor savegame loading

common/scriptcore/api_game_methods.cpp, common/scriptcore/api_game_methods.h, common/scriptcore/tolua_game.pkg, server/scripting/api_server_edit.cpp, server/scripting/api_server_edit.h, server/scripting/tolua_server.pkg
Closes #2752
Can be tested by typing lua commands into the console: 
```
/lua cmd log.debug("%s", find.tile(0, 0):primary_resource_name())
/lua cmd find.tile(0, 0):set_primary_resource("Buffalo")
/lua cmd find.tile(0, 0):set_primary_resource(nil)
```
=> Allow getting and setting primary tile resource in Lua

client/unitselect.cpp, client/unitselect.h
The game was crashing when switching players after opening the unit choice menu at least once.
Fix it by removing the destructor of units_select. Rely on Qt parent-child mechanics to delete the widget (this was already in place).
=> Fix a crash when switching players

docs/Manuals/Advanced/civ2.rst, docs/Manuals/Advanced/index.rst, docs/Manuals/Game/start-screen.rst, docs/Manuals/Server/commands.rst, server/savegame/CMakeLists.txt, server/savegame/civ2.cpp, server/savegame/civ2.h, server/savegame/savemain.cpp, server/stdinhand.cpp
The goal of this PR is to support minimal loading of civ2 saves and scenario files (`.sav`/`.scn`). The format of map files (`.mp`) is also known, but is different enough that a separate code path would be needed. Saves are loaded with the usual `/load` command.
Current status:
* Most game structures are defined and can be read from civ2's binary save format
* Only MGE saves are supported (other civ2 versions have minor layout variations)
* Terrains, tile improvements, and cities are converted to fc21 data structures
* Vision and diplomatic states should be imported properly
* The game doesn't crash immediately
This is what a loaded game might look like with minimal tileset conversion:
civ2 modders frequently reassigned terrains so things will look strange with default tilesets.
What's …
=> Add support for loading civ2 saves

.github/workflows/build.yaml, .github/workflows/clang-tidy.yaml, .github/workflows/coverity.yaml
We were using 24.10, which has reached EOL and has been removed from the Azure mirror.
=> Bump CI to Ubuntu 25.10 (questing)
