.travis.yml
cmake/FreecivDependencies.cmake
common/fc_interface.cpp
utility/CMakeLists.txt
utility/support.cpp
utility/support.h

Well, Qt uses ICU internally, but using it through Qt APIs is easier and safer.

Use QString instead of ICU

---

CMakeLists.txt
cmake/FreecivDependencies.cmake
utility/netintf.cpp
utility/shared.cpp

Not sure if moving DIRENT_H out of if(UNIX) wont break msys build ?

Windows compilation with MinGW32

---

common/city.cpp

Fix city.cpp::566]: assertion 'NULL == city_map_index' failed

---

client/servers.cpp
client/servers.h

Removed main loop in scan to signal/slot so thread could be removed there.

Udp scan in client

---

client/citydlg_common.cpp
client/helpdata.cpp
client/servers.cpp
client/tilespec.cpp
client/tilespeenum.cpp
common/aicore/cm.cpp
common/aicore/path_finding.cpp
common/city.cpp
common/clientutils.cpp
common/featured_text.cpp
common/map.cpp
common/mapimg.cpp
common/networking/dataio_raw.cpp
common/scriptcore/luascript.cpp
common/unittype.cpp
server/advisors/autosettlers.cpp
server/gamehand.cpp
server/generator/mapgen_utils.cpp
server/generator/startpos.cpp
server/notify.cpp
server/savegame/savecompat.cpp
server/savegame/savegame2.cpp
server/savegame/savegame3.cpp
server/score.cpp
server/stdinhand.cpp
server/unithand.cpp
tools/ruleutil/rulesave.cpp
utility/fcintl.cpp
utility/registry_ini.cpp
utility/shared.cpp

If there will be some bugs new coverity should show them. Some char* mismatch left.

Fixing free/delete/malloc mismatch

---

common/generate_packets.py
common/networking/packets.h

msvc++ doesnt like typeof in c++

replace typeof with decltype

---

client/clinet.cpp
client/gui-qt/menu.cpp
client/gui-qt/menu.h
common/networking/connection.cpp

Simply remove the error condition and process buffered packets.

Fix "can't grow buffer"

---

server/civserver.cpp
server/srv_main.cpp
server/srv_main.h

New server function to time track some server activities

---

client/CMakeLists.txt
client/client_main.cpp
client/gui-qt/gui_main.cpp
client/gui-qt/qtg_cxxside.h
client/gui_interface.cpp
client/gui_interface.h
client/include/gui_main_g.h
server/civserver.cpp
server/console.cpp
server/console.h
server/meta.cpp
server/meta.h
server/savegame/savegame2.cpp
server/savegame/savegame3.cpp
server/savegame/savemain.cpp
server/score.cpp
server/sernet.cpp
server/server.cpp
server/srv_main.cpp
server/srv_main.h
server/stdinhand.cpp
server/stdinhand.h
utility/log.cpp
utility/log.h
utility/shared.cpp

Also move initialization of the QApplication to client_main so we can do the same in the client.

QCommandLineParser for server options

---

common/networking/connection.cpp

Hello, awesome project.
I found a fix for endturn not being enabled asap.

Fixed end turn client button

---

common/networking/connection.h

It was making a lot of clang warnings

Fixed struct timer in one of headers  ->class timer

---

client/gui-qt/page_network.cpp
client/servers.cpp
client/servers.h

Removed threads from client network scans

Dont use threads in network scan

---

ai/default/daimilitary.cpp
ai/default/daimilitary.h
ai/difficulty.cpp
ai/handicaps.h
common/game.h
common/map.h
common/networking/packets.def
common/networking/packets.h
server/citytools.cpp
server/citytools.h
server/diplomats.cpp
server/plrhand.cpp
server/ruleset.cpp
server/ruleset.h
server/settings.cpp
server/unithand.cpp
utility/cmake_fc_config.h.in

Drop freeciv web support

---

cmake/GettextTranslate.cmake

fix of #65 
I tried using BYPRODUCTS property but it didn't worked and its ninja only anyway.

Generate translations only once per build

---

client/gui-qt/helpdlg.cpp
client/gui-qt/page_game.cpp
client/tilespec.cpp

It should be close #48 not 49 in b45f0bc

Fixed some qt Issues

---

client/gui-qt/messagewin.cpp
client/gui-qt/sidebar.cpp
data/themes/gui-qt/Classic/resource.qss
data/themes/gui-qt/Necrophos/resource.qss
data/themes/gui-qt/NightStalker/resource.qss

Now it will look like it should !!!

Fixed some widgets borders visible in dark themes as white

---

client/gui-qt/canvas.cpp
client/gui-qt/citydlg.cpp
client/gui-qt/citydlg.h
client/gui-qt/qtg_cxxside.cpp
client/gui-qt/qtg_cxxside.h
client/gui_cbsetter.cpp
client/gui_interface.cpp
client/gui_interface.h
client/include/canvas_g.h
client/include/citydlg_g.h
client/mapview_common.cpp
client/mapview_common.h

Still far from perfect but better

One step closer to make city dialog great

---

client/options.cpp

Here 987a319f125455423c56fc5fd74a2aaf277d619f, was using continue to iterate wihtout increasing iterator

Fix regression in QHash settable options

---

client/tilespec.cpp
data/alien/terrain.ruleset
data/civ1/terrain.ruleset
data/civ2/terrain.ruleset
data/civ2civ3/terrain.ruleset
data/classic/terrain.ruleset
data/experimental/terrain.ruleset
data/multiplayer/terrain.ruleset
data/sandbox/terrain.ruleset
data/webperimental/terrain.ruleset

Fixes:
* Two errors on server startup (`critical` level)
* The client spamming boxes with `debug` (?) level messages from the tileset loading code

Quick fixes after logging merge

---

client/gui-qt/fonts.cpp
client/gui-qt/fonts.h
client/gui-qt/gui_main.cpp
client/gui-qt/gui_main.h
client/include/gui_main_g.h
client/options.cpp
client/options.h

Option is in fonts category.
It has all changes from "useless" PR bc it changes similar files.

New option to increase/decrease all fonts at once

---

cmake/FreecivDependencies.cmake
server/CMakeLists.txt
server/console.cpp
server/stdinhand.cpp
server/stdinhand.h
utility/cmake_fc_config.h.in

There are implementations for Windows and it was already mandatory in practice.

Make readline mandatory

---

server/civserver.cpp

Fix --ruleset server option

---

server/civserver.cpp
server/sernet.cpp
server/srv_main.cpp
server/srv_main.h

Try harder to find a usable port

---

client/packhand.cpp

research.cpp:555) - Assertion state == TECH_UNKNOWN failed

Fix assertion fail for global observer

---

client/gui-qt/sidebar.cpp
client/include/ratesdlg_g.h
client/options.cpp
client/options.h

Resizeable width - not height - via options

Added option to resize sidebar(in options - interface)

---

utility/support.cpp

Ctrl+c + ctrl +v is sooooooooo good ... but sometimes fail :D

Fix of #140

---

client/gui-qt/fc_client.cpp
client/gui-qt/sidebar.cpp
client/gui-qt/sidebar.h

Added resizeEvent to sidebar and removed processEvents added few patches back

Fixed Nofocus in newgame

---

client/mapview_common.cpp

Create a logging category for FPS messages

---

server/stdinhand.cpp

Fix empty strings when splitting

---

data/themes/gui-qt/TheLastLaserMaster/resource.qss

Changes to theme only, it fixed that grey box on sell improvements box

Last Laser Master theme changes [skip travis]

---

client/gui-qt/shortcuts.cpp
client/gui-qt/shortcuts.h

Quick reminder: After changing number of shortcuts all shortcuts are reseted to origin

add missing shortcuts

---

client/gui-qt/notifyreport.cpp

Now its a bit too tall but looks ok.

Fix size of notify report

---

client/gui-qt/citydlg.cpp
client/gui-qt/citydlg.h
client/gui-qt/citydlg.ui
client/gui-qt/mapctrl.cpp
client/gui-qt/mapview.cpp
client/gui-qt/mapview.h
client/gui-qt/page_game.cpp
client/gui-qt/page_game.h
data/themes/gui-qt/NightStalker/resource.qss

Move it to the main screen, refactor a bit, clean up NightStalker tabs.
@mir3x could you review this one?

City dialog

---

data/themes/gui-qt/Classic/resource.qss
data/themes/gui-qt/Necrophos/resource.qss
data/themes/gui-qt/NightStalker/resource.qss
data/themes/gui-qt/TheLastLaserMaster/resource.qss

[skip travis][skip travis][skip travis][skip travis][skip travis][skip travis][skip travis][skip travis][skip travis][skip travis][skip travis]

Added city unit list icons style for themes

---

common/generate_packets.py

We deserve A in CodeFactor  :1st_place_medal:

Python codeFactored and autopeped8 with deafult values

---

client/clinet.cpp

It didnt break anything, 
I have no idea what I disconnected with client.conn.sock->disconnect(); but it's crucial to fix.

Fix reconnecting to local server

---

common/map.cpp
server/srv_main.cpp

Fixed Hashes/Sets when starting scenarios game

Fix scenarios starting

---

client/gui-qt/citydlg.cpp

Someone broke citizens label and didnt fixed

Fix citizens label

---

client/gui-qt/citydlg.cpp
client/gui-qt/citydlg.h
client/gui-qt/cityrep.cpp
client/gui-qt/dialogs.cpp
client/gui-qt/helpdlg.cpp
client/gui-qt/helpdlg.h

only 80 lines shaved ... not worth

Removed some duplication in gui-qt

---

common/aicore/cm.cpp
common/aicore/path_finding.cpp
common/city.cpp
common/map.cpp
common/mapimg.cpp
common/networking/dataio_raw.cpp
common/networking/packets.cpp
common/requirements.cpp
common/road.cpp
common/spaceship.cpp
common/terrain.cpp
common/unit.cpp
tools/civmanual.cpp
tools/fcmp/mpdb.cpp
tools/ruledit/ruledit_qt.cpp
tools/ruledit/ruledit_qt.h
tools/ruledit/tab_enablers.cpp
tools/ruleutil/comments.cpp
tools/ruleutil/rulesave.cpp
utility/fcthread.h
utility/genhash.cpp
utility/registry_ini.cpp
utility/shared.cpp
utility/shared.h

Fixed some Coverity issues

---

data/CMakeLists.txt
data/scenarios/CMakeLists.txt
data/scenarios/compress.cmake

Always compress with gzip for now

Install scenarios

---

client/connectdlg_common.cpp

Using the current directory isn't nice because CMake encourages out-of-source builds. First look in the same directory as the client is in (QCoreApplication::applicationDirPath()), then in PATH. And thanks to Qt a special case for Windows is not needed.

Improve the logic to find the server

---

client/audio.cpp
client/audio.h
client/options.cpp

It was resulting in QString(nullptr) being evaluated… bad!

Fix the default sound plugin

---

common/networking/packets.cpp

or maybe not, coverity will tell :dancers:

Chunk maybe fix

---

client/gui-qt/citydlg.cpp
client/mapview_common.cpp
client/mapview_common.h

added fast redrawing map function and used in city dialog

---

ai/default/aiunit.cpp
ai/default/daicity.cpp
ai/default/daieffects.cpp
ai/default/daimilitary.cpp
client/attribute.cpp
client/goto.cpp
client/governor.cpp
client/gui-qt/citydlg.cpp
client/gui-qt/diplodlg.cpp
client/gui-qt/helpdlg.cpp
client/gui-qt/shortcuts.cpp
client/servers.cpp
client/tilespec.cpp
common/featured_text.cpp
common/generate_packets.py
common/map.cpp
common/requirements.cpp
server/cityturn.cpp
server/generator/fracture_map.cpp
server/ruleset.cpp
server/sernet.cpp
server/unithand.cpp
tools/civmanual.cpp

Coverity again

---

client/gui-qt/canvas.cpp

Its for tilesets that dont have fog of war like hexemplio, previous fog had some artifacts.

Better for of war

---

client/gui-qt/fc_client.cpp
client/gui-qt/shortcuts.cpp
data/themes/gui-qt/Classic/resource.qss
data/themes/gui-qt/Necrophos/resource.qss
data/themes/gui-qt/NightStalker/resource.qss
data/themes/gui-qt/TheLastLaserMaster/resource.qss

Taat fixes invisible shortcut description in nightstalker theme

Add custom theme property for shortcut dialog

---

ai/default/aidata.cpp
ai/default/aidata.h
ai/default/aidiplomat.cpp
ai/difficulty.cpp
ai/handicaps.cpp
ai/handicaps.h
client/helpdata.cpp
common/mapimg.cpp
common/player.h
utility/bitvector.cpp
utility/bitvector.h
utility/inputfile.cpp
utility/registry_ini.cpp

THose 2 astrings are very easy to remove but I dont have time for them :D

Removed some bitvectors, 2 small astrings left

---

client/gui-qt/dialogs.cpp
common/actions.cpp
utility/astring.cpp
utility/astring.h

The probability that function will success is 0-100% or somewhere in between. (This is the most precise interval I can calculate given the information our nation has access to.

Add function to break lines and use it in action tooltips

---

common/networking/packets.h
server/diplomats.cpp
server/plrhand.cpp
server/ruleset.cpp

Fix investigate city info

---

client/update_queue.cpp

list_iterate replaced with for auto

Wait queues replaced lists

---

client/text.cpp

If timeout > 3600 show time (hours + mins) change
If day differs then show also day

Add extra time information to timeout sidebar

---

client/client_main.cpp

Fixed ScenarioPage/LoadPage showing PageStart (as connected to server).

Update queue fix -> fix switching to load scenarios/load saves

---

ai/default/aihand.cpp
ai/default/daicity.cpp
ai/default/daimilitary.cpp
client/gui-qt/page_game.cpp
client/gui-qt/page_load.cpp
client/gui-qt/page_scenario.cpp
client/mapview_common.cpp
client/packhand.cpp
common/aicore/cm.cpp
common/networking/packets.cpp
server/generator/mapgen.cpp
server/ruleset.cpp
server/savegame/savegame3.cpp
server/unithand.cpp
server/voting.cpp
tools/fcmp/download.cpp

Road to 50 cows

---

CMakeLists.txt

The files have been removed.
Closes #274

Drop ChangeLog and NEWS from the installed docs

---

dependencies/backward-cpp-1.5/backward.hpp

Simply update backward.hpp to the latest version.
Fixes #272

Fix backward compilation on MSYS

---

server/server.cpp

The event fires with just key released events left in the queue. Make sure that there is at least one key down in the queue before attempting to read (since it blocks).
Fixes #278

Windows: don't block on empty console input queue

---

utility/log.cpp

Windows-only patch.
Fixes #288

Enable VT-100 mode in cmd.exe

---

utility/inputfile.cpp
utility/registry_ini.cpp

Fixes #236
In addition, includes a small improvement to memory safety.

QIODevice error checking and safety

---

AUTHORS

Update AUTHORS for Freeciv21

---

CMakeLists.txt
INSTALL

INSTALL Fixes

---

data/scenarios/CMakeLists.txt
server/server.cpp

file Unrecognized argument: "COMPRESSION_LEVEL"
cmake version 3.18.20081302-MSVC_2
Cmake 3.19 Release Notes:
The file(ARCHIVE_CREATE) command gained a COMPRESSION_LEVEL

fix Fle Unrecognized argument: COMPRESSION_LEVEL

---

client/gui-qt/page_load.cpp
common/featured_text.cpp
common/requirements.cpp
server/ruleset.cpp
server/techtools.cpp
tools/fcmp/download.cpp
tools/ruledit/effect_edit.h

This (hopefully) fixes issues listed in [this Coverity report](https://scan6.coverity.com/reports.htm#v10572/p11368/fileInstanceId=113587100&defectInstanceId=32379512&mergedDefectId=1438955). There were a few genuine bugs but it was mostly noise.

Fix new Coverity findings

---

doc/README.modpack_installer
tools/fcmp/download.cpp
tools/fcmp/download.h
tools/fcmp/mpcli.cpp
tools/fcmp/mpcmdline.cpp
tools/fcmp/mpgui_qt.cpp
tools/fcmp/mpgui_qt.h
tools/fcmp/mpgui_qt_worker.cpp
utility/netfile.cpp
utility/netfile.h

This changes the format of modpack definition files in a backward incompatible way. The versioning of the format itself is decoupled from releases because it will likely be rather stable.
The documentation has also been updated.
Closes #308

JSON modpack definitions

---

client/gui-qt/page_load.cpp

Fixed fix about fixing mem leak in page load

---

tools/fcmp/mpcmdline.cpp

Fix starting the modpack installers

---

common/map.h
data/civ2civ3/game.ruleset
data/scenarios/british-isles.sav
data/scenarios/europe.sav
data/scenarios/france.sav
data/scenarios/hagworld.sav
data/scenarios/iberian-peninsula.sav
data/scenarios/italy.sav
data/scenarios/japan.sav
data/scenarios/north_america.sav
data/scenarios/tutorial.sav

Hex is nice but art is harder to find than for isometric and square.
Closes #357.

Revert the default topology to square

---

server/savegame/savegame3.cpp

Load did_buy_production from saves correctly

---

server/savegame/savemain.cpp

check for creating empty dir with mkpath to avoid warning

---

server/savegame/savemain.cpp

Fix copy-paste error in fad94fdf9035b0be81e3665b7edb25d1cf8eed3c

Fix copy-paste error

---

client/audio_sdl.cpp

SDL plugin: don't try to free a NULL music pointer

---

.travis.yml
INSTALL

Build on Windows with MinGW and create the installer. Creating nightly releases is left for later.
See https://docs.travis-ci.com/user/reference/windows/#how-do-i-use-msys2
See #300

Build the Windows installer on Travis

---

utility/log.cpp

Don't log unknown source locations in non-debug builds

---

client/audio.cpp
client/audio.h
server/ruleset.cpp

Closes #375.
Two commits cancelling each other were not included and another related fix was also included.
@jwrober I'd be grateful if you could confirm that the issues are fixed.

Cherry pick freeciv.org music fixes

---

client/tilespec.cpp

Created with VS Code extension :P

Search for intro graphics trying png first

---

client/tilespec.cpp

Fixed goto turn numbers

---

client/tilespec.cpp

Some rulesets (eg LTT) go above the hard-coded maximum of 10. Let the artist
specify as many sprites as he wants.
Closes #345.

Allow an arbitrary number of tile output sprites

---

INSTALL

It doesn't work on Debian Buster.
Closes #431.

Don't recommend cmake --install

---

.travis.yml

Travis on OS X: Force updating Homebrew

---

CMakeLists.txt

Discover dependencies dynamically

---

.travis.yml

Restore NLS in the Windows CI

---

tools/fcmp/download.cpp
utility/netfile.cpp

Two independent issues; see #446 and commit messages for details.

Fix FCMP issues reported in #446

---

CMakeLists.txt
cmake/CPackConfig.cmake
cmake/NSIS.template.in

Collection of changes closing the following issues: #334, #336, #339, #443

Windows NSIS Installer Updates

---

CMakeLists.txt
client/CMakeLists.txt
cmake/FreecivDependencies.cmake
cmake/NSIS.template.in
tools/fcmp/CMakeLists.txt
tools/ruledit/CMakeLists.txt

- Automatically installs required Qt libraries - closes #453 
- Eliminates the .cmd files and the console window that comes up on launch - closes #338 
- Does a little cleanup

Msys2 Qt Updates

---

client/gui-qt/citydlg.cpp

Dont resize on show event in citydialog

---

client/goto.cpp

Seems out of place, might introduce some tranport bugs, didnt observed any so far

Fix popup when disembarking 

---

client/connectdlg_common.cpp

Fix Start game not spawning server on windows

---

cmake/FreecivDependencies.cmake

Add cvercmp whenever fcmp is built

---

.readthedocs.yaml

I don't know if it will work.
Closes #484.

Add a Read The Docs configuration file

---

common/city.h
common/improvement.cpp
common/player.cpp
common/player.h
server/cityturn.cpp

I have tried to keep the same commit pattern as ilkkachu inspite of certain commits being redundant since this has been extensively tested now.

A port of WYSIWYG Patch

---

server/stdinhand.cpp

Remove the remaining #ifdef HAVE_FCDB

---

data/nation/phoenician.ruleset

closes #479 
Just thought I'd add this to improve it slightly. Also cleans up your issues :). Trying to help another issue too.

Added Female Leaders for Phoenician nation

---

client/gui-qt/page_network.cpp

Change MAX_LEN_NAME to MAX_LEN_PASSWORD

---

cmake/FreecivDependencies.cmake

Msys2 Lua error fix

---

AUTHORS

Include @pranavtifr and @DobbyK

Modify AUTHORS

---

.travis.yml

Fix a syntax error in the Travis configuration file

---

cmake/NSIS.template.in

Add a run freeciv21 command on windows installer

---

client/text.cpp

Bugfix: Fix popup repeating text when a unit had name

---

INSTALL
docs/install/install.rst

Bring it up to date with docs version, plus a small typo in docs/install/install.rst

INSTALL Update

---

CMakeLists.txt
cmake/FindSphinx.cmake
docs/CMakeLists.txt
docs/install/install.rst

Two commits. First is to wire in sphinx-build into cmake as a custom target and the second is an update to install.rst showing new target w/ some cleanup to better support RTD theme.

Cmake sphinx

---

client/clinet.cpp
server/server.cpp

This closes #341. See the commit messages for details of what was going on.

Fix spawning a local server on Windows

---

data/helpdata.txt
translations/core/Makevars
translations/nations/Makevars
translations/ruledit/Makevars

Prevent xgettext warnings

---

.gitignore
README.md

Closes #603.
Also clean up `.gitignore`.

Update the README.md status badge

---

.github/workflows/build.yaml

This follows the documentation of `softprops/action-gh-release@v1` but wasn't otherwise tested.
Closes #604.

Try to publish Windows binaries automatically

---

utility/rand.cpp

Bugfix: Seed the RNG better

---

common/version.cpp
server/civserver.cpp
utility/cmake_fc_config.h.in

Bugfix: fc21server announces fc21 instead of legacy fc

---

docs/Modding/Rulesets/effects.rst
docs/Modding/index.rst
docs/Modding/modpack-installer.rst

Docs update - Modding manual

---

client/gui-qt/page_network.cpp

Fix a crash when the metaserver is down

---

client/client_main.cpp
client/gui-qt/fc_client.cpp
server/commands.cpp
server/connecthand.cpp
server/rssanity.cpp
server/stdinhand.cpp
server/unittools.cpp
tools/ruleutil/rulesave.cpp

Some hand-editing was performed to tweak strings.
Closes #642.

Run clang-format

---

server/server.cpp

They wouldn't go past turn 1.
Closes #648.

Fix autogames (timeout -1)

---

client/audio.cpp

Audio.cpp update for modpack installer message

---

client/gui-qt/helpdlg.cpp
client/helpdata.cpp
client/include/helpdlg_g.h
common/effects.cpp
common/effects.h
data/helpdata.txt

This adds an "Effects" section to the help dialog that contains a list of all effects present in the ruleset and their requirements.

Basic effects documentation

---

ai/default/daieffects.cpp
common/effects.cpp
common/effects.h
data/civ2civ3/effects.ruleset
data/classic/effects.ruleset
docs/Modding/Rulesets/effects.rst
server/unittools.cpp

longturn/freeciv@0c1b537 implemented as an effect instead of server setting.

Feature: Make nukes destroy city improvements

---

docs/Modding/musicsets.rst

Fix misspelling in musicsets.rst

---

client/citydlg_common.cpp

Use the scaled tileset when computing city screen dimensions

---

client/attribute.cpp
common/networking/packets.cpp

Fix sending the CMA to the server and recovering it

---

.coverity/modeling.cpp
client/governor.cpp
client/gui-qt/page_load.cpp
client/layer_darkness.cpp
server/aiiface.cpp
server/citytools.cpp
server/maphand.cpp
server/ruleset.cpp
server/techtools.cpp
utility/registry_ini.cpp

This should fix or silence the warnings listed in #388 (subject to confirmation after merging by running a new scan).
Ending up fixing more… will stop pushing if someone starts reviewing (just lmk).

Fix Coverity warnings listed in #388

---

client/gui-qt/page_game.cpp
client/gui-qt/sidebar.cpp
client/gui-qt/sidebar.h

Always keep aspect ratios. Seems to work well on my small monitor.
Closes #556
I'd like two reviews on this one.

Resize sidebar buttons more sensibly

---

docs/General/install.rst

Add what Linux Distros are supported

---

client/gui-qt/helpdlg.cpp

Fix help to better state cultivate and transform

---

client/gui-qt/citydlg.cpp
client/gui-qt/unitselect.cpp
client/gui-qt/unitselect.h

This closes the following issues:
* A crash I noticed during testing, quite frequent
* #599 
* #738 
Did a small amount of code cleanup along the way.
Test plan: play with stacked units.

Unit selector update

---

.github/workflows/build.yaml

Fix clang-format for CI

---

CMakeLists.txt

set GET_RUNTIME_DEPENDENCIES to use objdump

---

docs/Contributing/dev-env.rst

Add steps to setup KDevelop

---

client/gui-qt/chatline.cpp
client/gui-qt/citydlg.cpp
client/gui-qt/diplodlg.cpp
client/gui-qt/mapview.cpp
client/gui-qt/menu.cpp
client/gui-qt/messageoptions.cpp
client/gui-qt/sciencedlg.cpp
client/gui-qt/themes.cpp

qapp has some linker errors on MacOS.

Change qapp to qApp macro

---

data/scenarios/tutorial.sav

Updated fc21 Tutorial Scenario

---

.github/workflows/coverity.yaml

I was looking at the actions history and found this error.

Fix coverity.yaml syntax error

---

.gitlab-ci.yml

https://gitlab.com/zekoz/freeciv21/-/jobs/2020670181

Add gitlab page ci for woboq codebrowsing

---

.github/workflows/build.yaml

No linked issue. Noticed at last tagged release.

Update MacOS package at release

---

.github/workflows/build.yaml
cmake/AutoRevision.cmake

Collection of changes to help CI builds

Build ci update

---

server/scripting/script_fcdb.cpp

Was a bit too optimistic when writing this one :)
See Coverity CID 1468899.
This is the last of #388 worth fixing, so:
Closes #388.

Fix dead code in script_fcdb_do_string

---

client/layer_terrain.cpp
common/map.cpp

**Test plan**
* Open help dialog
* No assertions

Don't generate assertion failures when opening the help dialog

---

.github/workflows/build.yaml
common/effects.cpp

Current `master` fails to build in `Debug` mode.
Fix this, and introduce debug mode builds in Github Actions so the current situation doesn't repeat.

Fix build in debug mode

---

client/gui-qt/citydlg.cpp

Sort to make it look more consistent: best defenders to the left, engineers to
the right.  Also take care that units within transports are always sorted next
to their transport so one can know in which transport they are loaded.
Closes #707.
**Test plan**
"Present units" in the city dialog are sorted as follows:
* Units in transport are shown immediately after their transporter
* Defensive units are shown to the left
* Fortified is left of fortifying which is left of sentried which is left of everything else
* Everything else being equal, units of the same type are grouped together

Sort units in the city dialog

---

docs/conf.py
docs/index.rst

Mainly to improve the main page; see commits for details.

Small documentation tweaks

---

ai/default/daicity.cpp
client/gui-qt/citydlg.cpp
client/gui-qt/mapctrl.cpp
client/options.cpp
common/city.cpp
common/generate_packets.py
common/helpdata.cpp
common/path_finder.cpp
common/unit.cpp
server/cityhand.cpp
server/citytools.cpp
server/cityturn.cpp
server/edithand.cpp
server/stdinhand.cpp
tools/civmanual.cpp
tools/ruledit/ruledit_qt.cpp

Take care of GCC warnings in release mode

---

.github/workflows/build.yaml

Update paths-ignore in build.yaml

---

common/research.cpp

The previous implementation wasnt making full use of the capabilites of cpp.

Rewrite loop in research_get_reachable_rreqs

---

client/gui-qt/civstatus.cpp
client/gui-qt/qtg_cxxside.cpp
client/gui-qt/qtg_cxxside.h
client/gui-qt/themes.cpp
client/gui_interface.cpp
client/gui_interface.h
client/include/themes_g.h
client/themes_common.cpp
client/tilespec.cpp

Fix some memory leaks

---

AUTHORS

Add me to AUTHORS

---

CMakePresets.json

Cmake preset for ASan with ccache

---

README.md

Add Mac to Readme

---

scripts/eval-pr

Not related to an existing issue.

New script to help with automating major steps of evaluating a PR

---

CMakePresets.json
docs/Contributing/visual-studio.rst

CMakePresets.json update to support Visual Studio

---

server/maphand.cpp
server/ruleset.cpp

Fix bugs found when porting dino's ruleset

---

CMakeLists.txt
docs/Contributing/visual-studio.rst

Support target install in Visual Studio

---

CMakeLists.txt
vcpkg.json

Visual Studio override to SSL 1.1

---

client/mapview.cpp
client/mapview.h
client/menu.cpp
client/menu.h
client/minimap_panel.cpp
client/minimap_panel.h
client/minimap_panel.ui
client/page_game.cpp
data/themes/gui-qt/icons/zoom-in.svg
data/themes/gui-qt/icons/zoom-in.svg.license
data/themes/gui-qt/icons/zoom-original.svg
data/themes/gui-qt/icons/zoom-original.svg.license
data/themes/gui-qt/icons/zoom-out.svg
data/themes/gui-qt/icons/zoom-out.svg.license

Following the mockup in #1002.

Add zoom buttons next to the minimap

---

client/plrdlg_common.cpp
client/plrdlg_common.h

Add columns about
government, culture, gold, %tax, %science, %lux, and current research
Ported from https://github.com/freeciv/freeciv/commit/8510bf84a1a634d73b8ae531a1427daa83983a43

Add new columns to nations report

---

client/packhand.cpp
common/player.cpp

Closes #982.
**Test plan:** ASan server run

Fix a -Wclass-memaccess

---

.github/workflows/release.yaml
CMakeLists.txt
cmake/CPackConfig.cmake

Support Windows i686 at release

---

client/citydlg.cpp
client/citydlg.h
client/citydlg.ui
client/mapctrl_common.cpp
client/mapctrl_common.h
client/mapview.cpp
client/mapview.h
client/packhand.cpp
client/tilespec.cpp
common/city.h

Closes a bunch of issues related to the city screen. See commit messages for details.

Fix city screen issues

---

server/srv_main.cpp

Ported from: https://github.com/freeciv/freeciv/commit/d3d1a9665e5d917768cda936ddc715a8590c558f
Fixes #1075
Didnt test, but it should be ok :smile:

Correct endturn statistics

---

ai/default/aisettler.cpp
client/control.cpp
client/notifyreport.cpp
client/unitreport.cpp
client/widgetdecorations.h
common/clientutils.cpp
server/savegame/savecompat.cpp
server/savegame/savegame3.cpp

Tackled all issues with Coverity in the title. See commit messages for brief explanations.
Closes #1025 
Closes #1070 
Closes #1071 
Closes #1118

Close Coverity-related issues

---

client/dialogs.cpp
client/packhand.cpp
client/tilespec.cpp
common/actions.cpp
common/government.cpp
common/helpdata.cpp
common/map.cpp
common/nation.cpp
common/nation.h
common/requirements.cpp
server/citytools.cpp
server/edithand.cpp
server/plrhand.cpp
server/plrhand.h
server/rssanity.cpp
server/ruleset.cpp
server/sanitycheck.cpp
server/settings.cpp
server/srv_main.cpp
server/stdinhand.cpp
tools/ruledit/univ_value.cpp
tools/ruleutil/rulesave.cpp

Remove the nations iterator. 
Test:
There should be no behavioral change.

Remove nations iter

---

dependencies/sol2/sol/config.hpp
dependencies/sol2/sol/forward.hpp
dependencies/sol2/sol/sol.hpp

Version 3.3.0 was released on 25 Jun 2022. Update our version to match.
Closes #1163.

Update sol2 to version 3.3.0

---

.github/workflows/clang-tidy.yaml

Workflow for suggesstions using clang-tidy

clang-tidy-review

---

server/unittools.cpp

Send hp the message sent when sentry wakes up

---

common/government.cpp

Initialize ai.better to nullptr in government constructor

---

client/text.cpp

On top of (and after) #1206 and #1208.
Give the total number of citizens that can be made content and details about
active effects. This should help towards #269.
Infrastructure can have an effect on citizen happiness. In this city, it can make up to **5 citizens** content.
The following contributions are active:
* 3 citizens from Cathedral+not Michelangelo's Chapel
* 1 citizen from Theology+Cathedral+not Michelangelo's Chapel
* -1 citizens from Communism+Cathedral+not Michelangelo's Chapel
* 1 citizen from Temple
* 1 citizen from Mysticism+Temple
Infrastructure can have an effect on citizen happiness. In this city, it can make up to **2 citizens** content.
The following contributions are active:
* 1 citizen from Temple
* 1 citizen from Mysticism+Temple
Infrastructure can have an effect …

Expand the city dialog text for building happiness (Make_Content)

---

client/mapctrl.cpp

Fix a crash when Ctrl+clicking on the map in city view

---

docs/Contributing/style-guide.rst

Docs: Update the Style Guide

---

data/helpdata.txt

helpdata: fix unterminated string errors

---

docs/Contributing/bugs.rst
docs/Contributing/dev-env.rst
docs/Contributing/eval-pull-request.rst
docs/Contributing/msys2.rst
docs/Contributing/pull-request.rst
docs/Contributing/visual-studio.rst

Bring the `docs/Contributing` files up to style and also add SPDX License

Docs: Update Contributing Files

---

client/connectdlg.cpp

Switch to the network page when autoconnecting to an auth-enabled server

---

data/themes/gui-qt/Classic/resource.qss

Classic theme: make selected tabs more visible

---

.github/workflows/release.yaml

Set MSYSTEM to MSYS32 in release.yaml

---

docs/Coding/architecture.rst
docs/Coding/guidelines.rst
docs/Coding/hacking.rst
docs/Coding/index.rst
docs/conf.py

This started as #1321 and ended up being #743.
Sorry for the length, I can split if needed...

Docs: Coding Guidelines

---

cmake/NSIS.template.in

Support fc21:// links on Windows

---

client/hudwidget.cpp
client/hudwidget.h

Update detailed combat info widget

---

docs/Coding/guidelines.rst
docs/Coding/hacking.rst
docs/Coding/index.rst
docs/Coding/internationalization.rst
utility/fciconv.h

This replaces the old i18n section in the Hacking guide.

Document internationalization

---

data/helpdata.txt

Fixes missed capitalized rules now that we have standardized on what to capitalize.

Help: Fix capitalization to standard rules

---

data/helpdata.txt

Found this while working on another PR

helpdata: fix unterminated string literal

---

client/citydlg.cpp
client/cityrep.cpp
client/dialogs.cpp
client/economyreport.cpp
client/gui_main.cpp
client/menu.cpp
client/unitreport.cpp
tools/fcmp/mpgui_qt.cpp

Improve the buttons on various dialog boxes

---

docs/Contributing/dev-env.rst

Docs: Add Qt Creator to Linux dev env

---

docs/Contributing/msys2.rst
docs/Contributing/visual-studio.rst

Docs: Add Qt Tools to Visual Studio. Part of #1400

Docs: Add Qt Tools to Visual Studio

---

client/chatline.cpp

Add server commands to chat auto completion word list

---

client/cityrepdata.cpp

Also updated the function headers to match coding guidelines
Closes #1052

Break out production buy gold and turns as columns in city view

---

client/diplodlg.cpp

Don't change Nations button for a meeting

---

client/connectdlg_common.cpp
client/fc_client.cpp
client/fc_client.h
client/page_load.cpp
client/page_main.cpp
client/page_main.ui
client/page_scenario.cpp
server/civserver.cpp

Closes #1365 
Still needs some refactoring work. Did consolidate the loading of a server to a single function instead of duplicating the same code 3 times.

Add Tutorial as a menu option on main page

---

client/dialogs.cpp
client/notifyreport.h

Information widgets open multiple times

---

client/page_load.cpp
client/page_load.ui

Saved games are sorted by date&time with the latest at the bottom

---

client/page_load.cpp

Saved games are sorted in alphabetical order, not time

---

client/citydlg.cpp

Don't show plague risk in city view when plague is disabled in the current ruleset

---

client/messagewin_common.cpp
client/packhand.cpp
client/update_queue.cpp
client/update_queue.h

This is a refactoring step in the direction of #1438. There should be no change in game behavior.

Simplify update_queue

---

common/player.cpp

Allow underscores in usernames

---

ai/default/aihand.cpp
common/aicore/cm.cpp
common/city.cpp
common/helpdata.cpp
common/networking/packets.def
data/alien/cities.ruleset
data/civ1/cities.ruleset
data/civ2/cities.ruleset
data/civ2civ3/cities.ruleset
data/classic/cities.ruleset
data/experimental/cities.ruleset
data/granularity/cities.ruleset
data/multiplayer/cities.ruleset
data/royale/cities.ruleset
data/sandbox/cities.ruleset
data/stub/cities.ruleset
server/ruleset.cpp
server/ruleset.h
tools/ruleutil/rulesave.cpp

Rename changable_budget -> changeable_budget, add changable_tax compat

---

client/fc_client.cpp

Coverity CID 1499988
Closes #1440.

Check return value of client_start_server()

---

client/options.cpp

* **Fullscreen by default:** We've been talking about this for ages but I couldn't find a relevant issue.
* **Show terrain on the Minimap:** Why was this even disabled by default?

Small tweaks to default settings

---

client/goto.cpp

Disable goto after sending orders to the server

---

client/unitreport.cpp
server/console.cpp
utility/deprecations.cpp
utility/deprecations.h

Also fix a compiler warning I noticed when rebuilding. No functional change.

Remove a function doing nothing

---

data/CMakeLists.txt

Colors are incorrect (use the system palette) without this file.
Reported by Mu on Discord.

Install theme.conf

---

server/commands.cpp

Fix spelling mistakes in timeout command help texts

---

client/turn_done_button.cpp

It was commented by Longturn players that this is sometimes more relevant information than the time at which TC will happen, for instance:
* to communicate acros timezones
* when doing TC or TC+-UWT moves
Add it as a tooltip to the Turn Done button.

Add the time until TC to the Turn Done tooltip

---

.github/workflows/release.yaml

Add a top level directory to source archives

---

docs/Contributing/release.rst
docs/Getting/compile.rst

Docs: update compiling and release pages

---

client/fonts.cpp
cmake/FreecivBuildOptions.cmake
cmake/FreecivInstall.cmake

Switch to Libertinus font
Fix notify label to monospace
Closes #1484 
Part of #1517

Libertinus Font

---

client/minimap_panel.cpp
client/minimap_panel.h
client/minimap_panel.ui

Enable resizable minimap panel

---

server/unittools.cpp

* Unset any existing unit activity so the path finding code works
* Use real distance instead of Manhattan, so we can move to any adjacent tile with distance = 1
Closes #1515.
[Load and do Shift+Enter.](https://github.com/longturn/freeciv21/files/10147587/transform.sav.gz)

Fix unit bouncing

---

client/optiondlg.cpp
client/shortcuts.cpp

* Make the options dialog bigger
* Make the shortcut inputs in Game > Shortcuts bigger
* Fix saving and restoring key bindings across locales

Small UI fixes

---

.github/workflows/build.yaml

Fixes #1601
Test PRs in my fork seem to run the actions correctly after this change
https://github.com/daavko/freeciv21/pull/2 (docs changes)
https://github.com/daavko/freeciv21/pull/3 (code changes)

Ignore docs changes for Build action

---

client/page_game.cpp

Keep geometry of the minimap_panel

---

client/hudwidget.cpp

Add a way to cancel unit loading

---

common/research.cpp

Spotted when loading the tutorial or the Polish game

Fix infinite recursion in research_is_valid

---

.idea/.gitignore
client/plrdlg_common.cpp

new:
```c++
static QString col_idle(const struct player *plr)
{
int idle;
static char buf[100];
//nturns_idle >= 0
if (plr->nturns_idle == 0) {
idle = 0;
} else {
idle = plr->nturns_idle - 1;
}
fc_snprintf(buf, sizeof(buf), "%d", idle);
return buf;
}
```
old:
```c++
static QString col_idle(const struct player *plr)
{
int idle;
static char buf[100];
if (plr->nturns_idle > 3) {
idle = plr->nturns_idle - 1;
} else {
idle = 0;
}
fc_snprintf(buf, sizeof(buf), "%d", idle);
return buf;
}
```
Fixes #1643

The value of idle stays at 0 until it turns 3 #1643 FIX

---

client/cityrep.cpp
client/client_main.cpp

Fix bugs related to options

---

.gitattributes

update .gitattributes to aid line endings standardization

---

client/goto.cpp

Restore the ability to emit goto orders followed by an action, that had been lost when rewriting the path finding code.  The new implementation is a simplified version of the old one, following more or less the same logic.
Closes #1619.
Tested with Engineers transforming terrain and Cavalry attacking a city.

Restore "Go to and..."

---

client/page_game.cpp
client/sciencedlg.cpp
client/sciencedlg.h

Restore hidden buttons when switching players

---

.github/workflows/build.yaml

Reverts a change I accidentally did earlier.

Run build CI on push to master

---

cmake/NSIS.template.in

No related issue.
Highly recommend this to backports stable

Don't prompt to remove previous version on windows

---

cmake/AutoRevision.cmake
cmake/CPackConfig.cmake
cmake/NSIS.template.in

This is also a backport candidate

CPack: fix an issue with the package version

---

server/plrhand.cpp

Don't crash when global observing

---

client/chatline.cpp
client/chatline.h
data/themes/gui-qt/Classic/resource.qss
data/themes/gui-qt/NightStalker/resource.qss

Use a dropdown menu and improve styling.
Closes #1646.

Improve the Allies Only button

---

client/minimap_panel.cpp

Hide the minimap settings button when toggling the minimap

---

client/turn_done_button.cpp

Closes #1718.
Suggest to backport because the tooltip was doing the wrong thing.

Fix timeout in the Turn Done tooltip when > 1 hour

---

docs/Coding/ai.rst
docs/Coding/hacking.rst
docs/Contributing/capitalized-terms.rst
docs/Contributing/style-guide.rst
docs/Getting/about.rst
docs/Manuals/Game/message-options.rst
docs/Manuals/Game/shortcut-options.rst
docs/Manuals/Rulesets/Common/building_flags.rst
docs/Manuals/Rulesets/Common/tech_adv_flags.rst
docs/Manuals/Rulesets/Common/unit_class_flags.rst
docs/Manuals/Rulesets/Common/unit_type_flags.rst
docs/Manuals/Rulesets/Common/unit_type_roles.rst
docs/Manuals/client-manual.rst
docs/Playing/cma.rst
docs/Playing/faq.rst
docs/Playing/how-to-play.rst
docs/Playing/turn-change.rst
docs/_static/theme_overrides.css

No related issue. Not for backport.

Add a new "advance" interpretive text role to docs

---

docs/Manuals/client-manual.rst

(stable) update client manual for battle log widget

---

client/hudwidget.cpp
client/menu.cpp
client/menu.h
client/shortcuts.cpp
client/shortcuts.h

* Fix translations in the shortcut dialog
* Fix #1755
Closes #1755.

Fix two bugs related to shortcuts

---

docs/Contributing/index.rst
docs/Contributing/stable-branch.rst

Docs: Document the maintenance of stable branch

---

docs/Manuals/Game/shortcut-options.rst
docs/Manuals/client-manual.rst

Docs: Update client manual battle log, middle-click and unit controls

---

client/citydlg.cpp
client/cityrepdata.cpp

Update city dialog labels to show gross food/prod/trade

---

client/fc_client.cpp
client/page_main.ui

Resize the main start page at leave game

---

client/plrdlg_common.cpp

Add research progress to nations view research column

---

client/helpdlg.cpp

Also label the Plant result correctly.
Backport suggested.

Fix help when the cultivate/plant/mining time is 0

---

docs/Contributing/stable-branch.rst

Docs: Stable Branch uses a GH project

---

.github/workflows/build.yaml

Closes #1522.
Suggest to backport.

Use the new CI syntax to set job outputs

---

docs/Coding/guidelines.rst

Mostly based on commentary while working on new units view. No related issue.

Docs: Update coding guidelines

---

docs/Coding/ai.rst
docs/Coding/hacking.rst
docs/Contributing/msys2.rst
docs/Modding/Rulesets/effects.rst
docs/conf.py

Fix Latex build of docs

---

client/hudwidget.cpp

Closes #1835.
Also includes some refactoring.

Fix loading units into the first transport on tile

---

docs/Manuals/Advanced/index.rst
docs/Manuals/Advanced/on-the-server.rst
docs/Manuals/Advanced/players.rst
docs/Manuals/Game/start-screen.rst
docs/Modding/index.rst
docs/Playing/faq.rst
docs/glossary.rst
docs/index.rst

Docs Update

---

client/menu.cpp
docs/Manuals/Game/menu.rst

Update Game Menu Options

---

client/options.cpp

Disable keyboardless goto by default

---

client/hudwidget.cpp
data/themes/gui-qt/Classic/resource.qss
data/themes/gui-qt/NightStalker/resource.qss

Fix hover over actions on unit controls bar (unit_action)

---

client/text.cpp

There was probably a call to city_refresh_from_main_map when it was written (or I was using a governor).
See #1873.

Fix military upkeep tooltip

---

docs/Manuals/client-manual.rst

Goes along with PR #1871 for Back-port. No related issue.

Docs (stable): Update game menu options

---

client/citydlg.cpp

Fix a city dialog crash after minimizing

---

docs/Getting/compile.rst

Docs: add Fedora to compile.rst

---

dist/snapcraft.yaml

We cut `stable` branch before I did a snapcraft file. This is the file used to create the package today on snapcraft.io.

(stable): snapcraft.yaml for v3.0

---

dist/snapcraft.yaml

Update to core22 and supports `master` branch builds of snaps.

snapcraft.yaml for v3.1-dev (master)

---

client/views/view_units.cpp
client/views/view_units.h

fix uwt table on units view to show all units

---

client/views/view_units.cpp
client/views/view_units.h

Fix units view to show when observing

---

client/views/view_economics.cpp
client/views/view_economics.ui

Do some other cleanup items too such as making the icon bigger, centering it in the cell and set alternating row colors. 
Closes #1818

Remove extra column in econ view

---

.github/workflows/build.yaml
client/views/view_economics.cpp
client/views/view_units.cpp
client/views/view_units.ui

With the work done in #1913, wanted to set units view to match. Also fixed the potential memory leak issue raised in the former PR.  No related issue for this PR.

Units and Econ View Updates

---

README.md

Remove reference to dead freecivweb.com

---

.readthedocs.yaml
docs/conf.py

Last two PR's failing. This fixes the conf file.

Fix docs/conf.py + update copyright

---

.github/workflows/build.yaml
.gitignore
README.md
flake.nix

Supersedes #1897 (I can't edit the branch): Removed the MacOS attempt (stuck on building KArchive) and switched the build to weekly.

Nix packaging and CI

---

server/unittools.cpp

team mates can see same unit info as player owner

---

client/views/view_units.cpp

Bug introduced in #1923. No related issue.

Shift unit upkeep icons over one

---

docs/Manuals/Advanced/fc21-uri.rst
docs/Manuals/Advanced/index.rst

Document usage of fc21:// protocol handler

---

data/multiplayer.serv
data/multiplayer/README.multiplayer
data/multiplayer/buildings.ruleset
data/multiplayer/cities.ruleset
data/multiplayer/effects.ruleset
data/multiplayer/game.ruleset
data/multiplayer/governments.ruleset
data/multiplayer/nations.ruleset
data/multiplayer/styles.ruleset
data/multiplayer/techs.ruleset
data/multiplayer/terrain.ruleset
data/multiplayer/units.ruleset

Associated with output from pyciv. Part of https://github.com/longturn/freeciv21/issues/1452 and https://github.com/longturn/freeciv21/issues/1453.

Multiplayer helptext updates for RTD

---

docs/Contributing/style-guide.rst

Grammar update to style guide

---

client/client_main.cpp
server/civserver.cpp
utility/shared.cpp

Replace three strings mentioning Freeciv

---

client/views/view_map.cpp
client/views/view_map.h

Also refactor the widget slightly to improve code quality and rely more on Qt.
Closes #1901.

Prevent the tile info tooltip from getting too wide

---

dist/flatpak.yaml
dist/snapcraft.yaml

Took opportunity to clean up a few errors with the `flatpak.yaml` file and fixed issue raised on `snapcraft.yaml`
We should get an account setup on flathub.org "soon". I'll update the snap package once this PR is merged.
Closes #1964

(stable) Flatpak and Snap updates

---

data/civ1/effects.ruleset
data/civ2/effects.ruleset
data/civ2civ3/effects.ruleset
data/civ2civ3/nations.ruleset
data/classic/effects.ruleset
data/classic/nations.ruleset
data/default/nation_intelligence_effects.ruleset
data/experimental/effects.ruleset
data/experimental/nations.ruleset
data/multiplayer/effects.ruleset
data/multiplayer/nations.ruleset
data/royale/buildings.ruleset
data/royale/effects.ruleset
data/royale/governments.ruleset
data/royale/nations.ruleset
data/royale/units.ruleset
data/sandbox/effects.ruleset
data/sandbox/nations.ruleset

Fix gettext translation string errors

---

docs/Manuals/Program/freeciv21-game-manual.rst
docs/Manuals/Program/freeciv21-server.rst
docs/Manuals/Program/index.rst
docs/Manuals/Server/command-line.rst
docs/Manuals/Server/commands.rst
docs/Manuals/index.rst
docs/conf.py

Part of #1947 
Draft PR right now to get some feedback. To test locally, run this from the Freeciv21 source root directory: `sphinx-build -b man docs build/docs/man`. Then open the created man page with `man ./build/docs/man/freeciv21-server.6`

Manual Pages from Sphinx

---

client/client_main.cpp
docs/Manuals/Program/freeciv21-client.rst
docs/Manuals/Program/freeciv21-game-manual.rst
docs/Manuals/Program/freeciv21-manual.rst
docs/Manuals/Program/freeciv21-server.rst
docs/Manuals/Program/index.rst
docs/Manuals/Server/command-line.rst
docs/conf.py
server/civserver.cpp
tools/civmanual.cpp

freeciv21-client and manual man pages

---

docs/Manuals/Program/freeciv21-manual.rst
docs/Manuals/Program/freeciv21-modpack-qt.rst
docs/Manuals/Program/freeciv21-modpack.rst
docs/Manuals/Program/index.rst
docs/conf.py
tools/fcmp/mpcmdline.cpp

Manual pages for modpack installer tools

---

cmake/AutoRevision.txt

CI got confused with the 3.0 patch released so manually updating the file.

Update AutoRevision.txt to 3.1-alpha.2

---

dist/snapcraft.yaml

Update stable snap to v3.0.1

---

.github/workflows/build.yaml
cmake/FreecivDependencies.cmake
cmake/FreecivInstall.cmake
docs/CMakeLists.txt
docs/Manuals/Program/freeciv21-ruleup.rst
docs/Manuals/Program/index.rst
docs/conf.py

Closes #1947 
- Adds final page for freeciv21-ruleup
- Add sphinx to the list of packages to install in CI
- Updates the install target to include the manual pages on Linux

Manual Pages

---

README.md

Fix broken link and add Flathub to README

---

docs/Modding/Tilesets/terrain.rst

Docs: Remove duplicated links

---

common/city.cpp

Remove spurious qCritical()

---

dist/snapcraft.yaml

Closes #1735
Part of this might be good for `stable`

Use scriptlet to get current version for snapcraft.yaml

---

client/citydlg.cpp

Fix suggested by daavko.
See #2041.

Fix changing specialists for city sizes >= 40

---

data/nation/american.ruleset

Added Martha Washington, George H. W. Bush, Bill Clinton and Hillary Clinton to list of rulers and removed Alexander Hamilton. Added Vermont, California, and Texas to list of civil war nations.

Updated America.ruleset

---

common/vision.cpp

Coverity CID 1528899.
Closes #2071.

Don't use array new to create vision sites

---

client/CMakeLists.txt
client/utils/collated_sort_proxy.cpp
client/utils/collated_sort_proxy.h
client/views/view_nations.cpp
client/views/view_nations.h

Enable natural sort in the nations view

---

client/control.cpp
client/mapctrl.cpp
client/views/view_map.cpp
client/views/view_map.h

Fix jumping to the next city when switching while in the city view

---

dist/net.longturn.freeciv21.client.metainfo.xml

Task 30 in the back port. Manually bump the version in the metainfo file.

Bump stable client meta file to 3.0.2

---

.github/workflows/build.yaml
data/tests/CMakeLists.txt
server/tests/CMakeLists.txt

Fix tests with multi-config build generators

---

cmake/FreecivInstall.cmake
docs/Contributing/eval-pull-request.rst
docs/Contributing/visual-studio.rst
scripts/eval-pr

... And other things.
Relies on #2098 to be merged first.

A little better support for Windows Clang

---

client/client_main.cpp
client/renderer.cpp
utility/cmake_fc_config.h.in
utility/shared.cpp

This PR contains two small clean-ups spotted while working on #2101 (the PRs will conflict).

Two small clean-ups

---

.github/workflows/build.yaml

No related issue. Part of release process.

Update vcpkgGitCommitId prior to release

---

.github/workflows/build.yaml

Build wasm only weekly

---

.github/workflows/release.yaml

- Add support for workflow_dispatch
- Add support for a weekly run of the package
- Fix the Qt package

CI/CD - Release.yaml update

---

dist/snapcraft.yaml

Bring `snapcraft.yaml` up to current stable

snapcraft.yaml - bring to stable 3.0.2

---

client/page_main.cpp
client/page_main.ui

Thanks @blabber for the suggestion. No related issue.

Move add-ons button to be with options

---

client/page_main.ui
data/themes/gui-qt/Classic/resource.qss
data/themes/gui-qt/NightStalker/resource.qss

Standardize buttons on start screen

---

common/helpdata.cpp

Wording suggested by soundnfury on Discord.
See https://discord.com/channels/378908274113904641/1198212662018981888

Improve the auto-generated help for combat rounds

---

dist/net.longturn.freeciv21.client.metainfo.xml
dist/snapcraft.yaml

Looks like I had a old commit in my fork. Let's go ahead and merge with the meta file update and I'll push another PR for snap once we tag the release.

bump stable to 3.0.3

---

client/audio/audio.cpp
client/menu.cpp
client/menu.h
client/tileset/tilespec.cpp
cmake/FreecivBuildOptions.cmake

Also fix two issues where the client would not refresh when content on disk changed after the client was opened. This allows the client to see changes after content is downloaded with the modpack installer. See #2158

Add an option to add Modpacks from the Game menu

---

dist/snapcraft.yaml

The snap has been refreshed already.

snapcraft.yaml - update to 3.0.3 on stable

---

dist/snapcraft.yaml

No related issue. Hoping to automate this soon.

Update snap package to 3.1-alpha.5

---

docs/Getting/compile.rst

Docs: Document CMake option FREECIV_ENABLE_MANPAGES

---

dist/net.longturn.freeciv21.metainfo.xml.in
dist/snapcraft.yaml

Develop your civilization from humble roots to a global empire. 
Closes #2182

New Slogan

---

docs/Contributing/eval-pull-request.rst

Found while reading https://longturn.readthedocs.io/en/latest/Contributing/eval-pull-request.html

Add a missing space in eval-pull-request.rst

---

client/views/view_map_common.cpp

Fix an alloc-dealloc mismatch in tile links handling

---

dist/net.longturn.freeciv21.client.metainfo.xml

Bump stable to v3.0.4

---

client/tileset/tilespec.cpp

Introduced by #2252. Fix is more of a patch than an actual solution.
Closes  #2257
Co-authored-by: Louis Moureaux <m_louis30@yahoo.com>

fix assertion pterrain failed bug

---

README.md

New Slogan on the README

---

dist/snapcraft.yaml

No issue. Part of release process.

Bring snap up to 3.1-beta.1

---

.github/workflows/release.yaml

No related issue. Came up on Discord.

Release: Ensure source archives get the freeciv21 directory

---

.gitignore

I was running valgrind for profiling and got a few files that I'd like git to ignore

Ignore valgrind files

---

.github/workflows/build.yaml
CMakePresets.json
common/aicore/cm.cpp
common/city.cpp

No related issue. The CI has been failing for awhile.

Fix compile on Windows Clang

---

.github/workflows/build.yaml

vcpkgid for 3.1-beta.2 release

---

docs/Getting/compile.rst

No related issue, setting up a dev env for snapcraft helped me find the error

Update compile installation for Debian/Ubuntu

---

.github/workflows/release.yaml

Release Action Updates

---

AUTHORS
common/featured_text.cpp
common/featured_text.h
server/unittools.cpp

Include both the veteran rank name and number in sentry message

---

server/unittools.cpp

Fixes bug introduced by 255ac0f

fix wrong unit being linked to stack kill message

---

docs/Playing/faq.rst

Documents the changed behavior in diplomatic relations introduced by #2266.

Add documentation for alliance protection measures

---

.github/workflows/build.yaml
dist/net.longturn.freeciv21.client.metainfo.xml

Update to support release 3.0.5

---

dependencies/sol2/sol/sol.hpp

Closes #2306
back port candidate

Sol2 patch for clang 19

---

client/goto.cpp

Draw waypoints immediately after adding them

---

client/climisc.cpp
client/control.cpp
client/control.h
client/gui_main.cpp
client/qtg_cxxside.h
common/fc_types.h
common/unittype.h

Spotted by @blabber. I also removed dead code spotted while doing the change.

Rename MAX_NUM_UNITS to MAX_NUM_UNIT_TYPES

---

dist/snapcraft.yaml

Snap update for 3.0.5 for stable branch.

Update snap for 3.0.5

---

docs/Contributing/release.rst

Give attribution to new contributors at release

---

.github/workflows/release.yaml

Bugfix release.yaml for location of freeciv21-server.cmd

---

docs/Contributing/game-admin.rst

Update game admin guide

---

client/tileset/tilespec.cpp

Requested by jwrober and TriClad on Discord.

Improve the error message for missing extra styles in tilesets

---

.gitignore
server/scripting/api_server_edit.cpp
server/scripting/api_server_edit.h
server/scripting/tolua_server.pkg

Closes #2485 
Also sneakily added `City:resize` alias for `edit.resize_city` since I spotted it was missing.

Added Lua edit.remove_city

---

docs/Manuals/Server/options.rst
docs/Modding/Rulesets/effects.rst

Questions asked by Corbeau on Discord.

Improve the documentation of Rapture_Grow

---

client/repodlgs_common.cpp

Reported by Coverity.
Closes #2488

Move list of cities instead of copying it

---

docs/Manuals/Game/start-screen.rst
docs/Manuals/Server/options.rst
docs/Playing/LT-Guide/first-turn.rst
docs/Playing/LT-Guide/index.rst
docs/Playing/LT-Guide/intro.rst
docs/Playing/how-to-play.rst
docs/Playing/index.rst

This is step 1 of many to keep PR reviews short.
Part of #487

New LT Gamer's Guide: Part 1

---

docs/Contributing/release.rst
docs/Contributing/stable-branch.rst
docs/_static/theme_overrides.css

Update release process based on findings from 3.0 to 3.1

---

data/default/default.lua
server/citytools.cpp
server/scripting/api_server_edit.cpp
server/scripting/script_server.cpp

Moved city looting to default.lua

---

docs/Playing/LT-Guide/final-notes.rst
docs/Playing/LT-Guide/first-turn.rst
docs/Playing/LT-Guide/index.rst
docs/Playing/LT-Guide/late-game.rst
docs/Playing/LT-Guide/mid-game.rst
docs/Playing/LT-Guide/twenty-turns.rst
docs/glossary.rst

On top of #2510. This is the final piece.
Closes #487

New LT Gamer's Guide: Part 3

---

cmake/FreecivInstall.cmake

No related issue. We started getting GH Action failures this week.

Fix file glob issue in recent cmake for msys2 builds

---

README.md

Simple addition to README, almost identical to FreeBSD instructions.

add install info for OpenBSD

---

client/CMakeLists.txt
client/citydlg.cpp
client/editor/map_editor.cpp
client/editor/map_editor.h
client/editor/map_editor.ui
client/mapctrl.cpp
client/page_game.cpp
client/page_game.h
client/shortcuts.cpp
client/shortcuts.h
docs/Manuals/Game/shortcut-options.rst
translations/core/POTFILES.in

Step 1 of probably 100.
Start of #580

New Map Editor Widget

---

client/editor/map_editor.cpp
client/editor/map_editor.h
client/editor/map_editor.ui
client/mapctrl.cpp
client/tileset/layer_editor.cpp
data/icons/32x32/close.svg
data/icons/32x32/editor-inspect.svg
data/icons/32x32/editor-tile.svg

Step 2 of ...
Part of #580 
Draft mode right now. Sending edit mode to the server causes a nasty assertion failure. Need to fix that.

New Map Editor 2

---

client/dialogs.cpp
client/dialogs.h

Since this is a destructive action, better be sure.

Ask for confirmation before recycling units

---

data/themes/Classic/resource.qss
data/themes/NightStalker/resource.qss

No related issue. Noticed some formatting issues while trying to do QSS for Map Editor.
Additionally fix a font color issue on Classic theme for combo boxes.
Suggest this for back port.

Cleanup Theme QSS

---

client/editor/map_editor.cpp
client/editor/map_editor.h

Map Editor: Finish Players Combo

---

client/attribute.cpp
client/tileset/layer_water.cpp
server/generator/startpos.cpp
server/unittools.cpp
tools/civmanual.cpp
utility/support.cpp

I ran an ASan autogame without problems.
Closes #2496 .

Fix a bunch of Coverity issues

---

docs/Manuals/Advanced/fc21-uri.rst
docs/README

No related issue. Came up on Discord.

Update fc21 links page

---

ai/default/aiunit.cpp
client/tileset/layer_city.cpp
client/tileset/layer_city_size.cpp
client/tileset/layer_editor.cpp
client/tileset/layer_fog.cpp
client/tileset/layer_goto.cpp
client/tileset/layer_grid.cpp
client/tileset/layer_units.cpp
client/views/view_map_common.cpp

Fix Coverity issues

---

utility/fcbacktrace.cpp
utility/fciconv.cpp
utility/genlist.cpp
utility/log.cpp
utility/shared.cpp
utility/version.cpp

Includes for Utility directory. On top of https://github.com/longturn/freeciv21/pull/2561, Part of https://github.com/longturn/freeciv21/issues/2464

Utility Includes Refactor

---

docs/Coding/debug-windows.rst
docs/Coding/index.rst

No related issue. I thought it good to document the steps that led to us finding #2567

Windows Console Debug

---

client/dialogs.cpp
utility/support.cpp

Fix even more coverity issues

---

utility/bitvector.cpp
utility/bitvector.h
utility/distribute.cpp
utility/inputfile.cpp
utility/inputfile.h
utility/iterator.cpp
utility/log.cpp
utility/log.h
utility/netfile.cpp
utility/netfile.h
utility/rand.cpp
utility/rand.h

A better/proper implementation of IWYU
Part of #2464 
Other than Qt still issuing warnings, all other missing include warnings are gone.

Includes refactor: utility 2

---

utility/astring.cpp
utility/astring.h
utility/bugs.cpp
utility/bugs.h
utility/capability.cpp
utility/fcbacktrace.cpp
utility/fciconv.cpp
utility/fciconv.h
utility/fcintl.cpp
utility/fcintl.h
utility/fcthread.cpp
utility/fcthread.h
utility/genhash.cpp
utility/genhash.h
utility/genlist.cpp
utility/tests/test_paths.cpp

A better/proper implementation of IWYU
Part of #2464 
Other than Qt still issuing warnings, all other missing include warnings are gone.

Includes refactor: utility 1

---

client/control.cpp
client/control.h
client/editor.cpp
client/editor.h
client/editor/map_editor.cpp
client/editor/map_editor.h
client/editor/map_editor.ui
client/editor/tool_tile.cpp
client/editor/tool_tile.h
client/editor/tool_tile.ui
client/mapctrl.cpp
client/mapctrl_common.cpp
client/views/view_map_common.cpp
client/views/view_map_common.h
common/networking/connection.cpp

Part of #2547 
This PR gets us the population of the first 5 attributes of a selected tile. I have it in draft right now as I'm needing some help with Qt layouts. The StackedWidget wasn't working. I went back to a vertical layout, which "works", but doesn't look right.

Map Editor: Editor Tool Tile Phase 1

---

docs/Coding/guidelines.rst

Update guidelines for header includes

---

client/citydlg.ui

Fix context menus on governor presets in city dialog

---

client/citydlg.cpp
client/dialogs.cpp
client/diplodlg.cpp
client/gotodlg.cpp
client/mapctrl.cpp
client/top_bar.cpp
client/unitselect.cpp
client/views/view_cities.cpp
client/views/view_nations.cpp
client/views/view_research.cpp

Change all calls to QCursor::pos() to specify a screen

---

server/report.cpp

Use the demographic class for the score log

---

common/aicore/aiactions.cpp
common/aicore/aiactions.h
common/aicore/aisupport.cpp
common/aicore/aisupport.h
common/aicore/caravan.cpp
common/aicore/caravan.h
common/aicore/citymap.cpp
common/aicore/citymap.h
common/aicore/cm.cpp
common/aicore/cm.h
common/aicore/path_finding.cpp
common/aicore/path_finding.h
common/aicore/pf_tools.cpp
common/aicore/pf_tools.h

See #2464. This set includes common/aicore. There are some NOLINT comments that I am hoping to be able to come back and correct after all the other common includes are refactored.

Includes Refactor: Common 1 (aicore)

---

ai/default/daiactions.cpp
common/achievements.cpp
common/achievements.h
common/actions.cpp
common/actions.h
common/ai.cpp
common/ai.h
common/base.cpp
common/base.h
common/borders.cpp
common/borders.h

See #2464. This set is the first 10 files in `common`, plus one in `ai` that needed a fix to keep compiling working.

Includes Refactor: Common 2

---

.github/workflows/build.yaml
utility/support.cpp

Had a syntax error in the workflow file due to a misunderstanding of the docs.

Fix running actions

---

README.md
docs/Contributing/msys2.rst
docs/Getting/compile.rst

docs: Bring docs up to speed with Qt6

---

.github/workflows/build.yaml
.github/workflows/release.yaml
dist/snapcraft.yaml.in

I expect this to be squashed. Took a bit of troubleshooting in my fork to get it to work.
Closes #2619

Fix snapcraft.yaml for Qt6

---

server/unittools.cpp

Recommending backport to stable.
Closes #2621

Fixed 'nuke_exploded' signal lua script segfault

---

client/chatline.cpp
client/citydlg.cpp
client/hudwidget.cpp
client/optiondlg.cpp
client/themes.cpp
client/views/view_cities.cpp

This updates some functions that are deprecated in Qt 6 to their new name. I only did a few easy ones that required no thinking.

Update some functions deprecated in Qt6

---

client/widgets/decorations.cpp

While here, replace deprecated methods in the changed file.
Closes #2637

Scale move_widget icon according to device scaling

---

.github/workflows/build.yaml
ai/default/daimilitary.h
ai/tex/texai.c
ai/tex/texaicity.c
ai/threaded/threadedai.c
client/views/view_map_common.cpp
common/aicore/path_finding.cpp
common/clientutils.cpp
common/events.cpp
common/game.h
common/map.h
docs/Contributing/dev-env.rst
docs/Contributing/pull-request.rst
docs/Getting/compile.rst
server/aiiface.cpp
server/diplomats.cpp
server/savegame/savecompat.cpp
server/score.cpp
tools/ruledit/tab_enablers.cpp
utility/bitvector.h
utility/log.h
utility/shared.h
utility/speclist.h
utility/specpq.h
utility/specvec.h
utility/support.h

Move to clang-format-17

---

common/scriptcore/api_game_methods.cpp
common/scriptcore/api_game_methods.h
common/scriptcore/tolua_game.pkg
server/scripting/api_server_edit.cpp
server/scripting/api_server_edit.h
server/scripting/tolua_server.pkg
server/unittools.cpp
server/unittools.h

Allow retrieving and modifying unit hitpoints in Lua

---

.luarc.json
.readthedocs.yaml
common/scriptcore/tolua_common_a.lua
docs/Modding/Rulesets/script.rst
docs/Modding/index.rst
docs/conf.py
docs/requirements.txt

Added support for Lua docs in sphinx

---

client/views/view_map_common.cpp

Fixes: 2408738725242bd2be7b37761dc5f7e9eafa1cbc.

[stable] Fix macro to select Windows version of anim_delay

---

server/scripting/tolua_server.pkg

Fixed Lua HP edit aliases

---

server/scripting/stubs/server.lua

Add server.setting.get to Lua API docs

---

common/player.cpp
common/player.h
common/scriptcore/api_game_find.cpp
common/scriptcore/api_game_find.h
common/scriptcore/api_game_methods.cpp
common/scriptcore/api_game_methods.h
common/scriptcore/luascript_types.h
common/scriptcore/stubs/game.lua
common/scriptcore/tolua_common_z.lua
common/scriptcore/tolua_game.pkg
common/team.cpp
common/team.h
docs/Modding/Rulesets/script.rst

Closes #2801
Test using: `/lua cmd log.debug("%s", find.team(0))` etc

Added teams to Lua API

---

common/helpdata.cpp
data/helpdata.txt

While here, change the alignment of the table in "Terrain Alterations/Road", as suggested by  @lmoureaux.
Part of #2778.

Markdownify strategy tactics
